### PR TITLE
Fix for issue 201: Added EmbeddedInstance to datatype in Wiki generation script

### PR DESCRIPTION
**Pull request by ykuijs**
This PR fixes issue #201

Adds EmbeddedInstance to the datatype in Wiki generation script

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/202)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DscResource.DocumentationHelper/WikiPages.psm1, line 75 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/202#-KzlsQVN3fST7QJDvEBT:-KzlsQVN3fST7QJDvEBU:bnbeyb3) ([raw file](https://github.com/powershell/dscresource.tests/blob/af05e0441121c825314fbaa9418e41c7b97dc577/DscResource.DocumentationHelper/WikiPages.psm1#L75)):*
> "MSFT_Credential"

Can we change this to single quotes? There no actually specific style guide around this, but all other style guidelines use single quotes when there are no variables to evaluate in the string.

---

*[DscResource.DocumentationHelper/WikiPages.psm1, line 77 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/202#-KzlsRgVcNHBBG5Ulagc:-KzlsRgVcNHBBG5Ulagd:bv3xpog) ([raw file](https://github.com/powershell/dscresource.tests/blob/af05e0441121c825314fbaa9418e41c7b97dc577/DscResource.DocumentationHelper/WikiPages.psm1#L77)):*
> "PSCredential"

Can we change this to single quotes?

I see there are some other places in this file that should change as well, but I won't comment on those. But if you would like to fix them as well (where applicable), to be consequent throughout the file, it would be nice. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/202)*

**Comment by ykuijs** [comment]
I have updated the quotes where possible. Some strings had variables in them, which requires double quotes for them to be expanded.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DscResource.DocumentationHelper/WikiPages.psm1, line 75 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/202#-KzlsQVN3fST7QJDvEBT:-KzoU7Q6NXCuRRK6CDv8:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/af05e0441121c825314fbaa9418e41c7b97dc577/DscResource.DocumentationHelper/WikiPages.psm1#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> "MSFT_Credential"

Can we change this to single quotes? There no actually specific style guide around this, but all other style guidelines use single quotes when there are no variables to evaluate in the string.
</blockquote></details>

Done.

---

*[DscResource.DocumentationHelper/WikiPages.psm1, line 77 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/202#-KzlsRgVcNHBBG5Ulagc:-KzoU83J7aZAyXrftR2r:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/af05e0441121c825314fbaa9418e41c7b97dc577/DscResource.DocumentationHelper/WikiPages.psm1#L77)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> "PSCredential"

Can we change this to single quotes?

I see there are some other places in this file that should change as well, but I won't comment on those. But if you would like to fix them as well (where applicable), to be consequent throughout the file, it would be nice. :smile: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/202#-:-KzoU8yfJLXYJB7YUNdd:bkyhco1)*

**Comment by johlju** [comment]
@ykuijs Did you forget to push the changes? Can't see any new commit.

**Comment by ykuijs** [comment]
It's one of those days...... ;-)

**Comment by johlju** [comment]
:lgtm:

@ykuijs looking good. :)

@kwirkykat when you have a chance, can you look this one over and merge?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/202#-:-KzrERU14fShTWs8lEtV:b-9uy7f4)*

**Comment by ykuijs** [comment]
@kwirkykat Any idea when this PR will be merged?

**Pull request merged**
