### PR TITLE
Suppress warning in PSSA with custom rules - Fixes #176

### LINKED ISSUE #176: PSScriptAnalyzer writes unnecessary warning when using custom rules
When running PSSA Custom rules it outputs a warning. This is probably PSScriptAnalyzer that is doing something (doing a `Write-Host` or similar? Just guessing). 
If it is PSScriptAnalyzer, is it worth opening up a issue in that repo?

More information from @PlagueHO in PR #162.

``` 
A command that prompts the user failed because the host program or the command type does not
support user interaction. The host was attempting to request confirmation with the following message: The
Update-Help cmdlet downloads the most current Help files for Windows PowerShell modules, and installs 
them on your computer. For more information about the Update-Help cmdlet, see 
http://go.microsoft.com/fwlink/?LinkId=210614.
```

_Opening this issue to track this._

### PR DESCRIPTION
**Pull request by PlagueHO**
When using custom rules in PSSA the Get-Help cmdlet gets called by PSSA. This causes a warning to be thrown in AppVeyor. This warning does not cause a failure or error, but causes additional bloat to the analyzer output. To suppress this the registry key `HKLM:\Software\Microsoft\PowerShell\DisablePromptToUpdateHelp` should be set to 1 when running in AppVeyor.

See this line from PSSA for more information:
https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/ScriptAnalyzer.cs#L1120

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/181)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[TestHelper.psm1, line 776 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/181#-KqYiAO37XItzyWo0IyV:-KqYiAO37XItzyWo0IyW:b-nrzfmj) ([raw file](https://github.com/powershell/dscresource.tests/blob/65eec7d794a10192b915f0485920e646f2a82734/TestHelper.psm1#L776)):*
> https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/ScriptAnalyzer.cs#L1120

Maybe reference to the method name GetExternalRule() also? If the line number changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/181)*

**Comment by PlagueHO** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[TestHelper.psm1, line 776 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/181#-KqYiAO37XItzyWo0IyV:-Kq_L-Yc1qkm2d9km7uO:b4dxzlc) ([raw file](https://github.com/powershell/dscresource.tests/blob/65eec7d794a10192b915f0485920e646f2a82734/TestHelper.psm1#L776)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/ScriptAnalyzer.cs#L1120

Maybe reference to the method name GetExternalRule() also? If the line number changes?
</blockquote></details>

Done. And in README.MD.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/181)*

**Comment by johlju** [comment]
:lgtm:

And I know @PlagueHO has tested this, since he sent me a DM on Twitter about the result. :)

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/181#-:-KqbBrJhNCLehMuQeD6U:bqbznhf)*

**Comment by johlju** [comment]
@kwirkykat When you have time can you look this one over and merge?

**Comment by PlagueHO** [comment]
@johlju - I fixed up the merge conflicts. Can you check this one over when you get a chance?

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/181#-:-KrAkitkRuSO892uLBGQ:bnfp4nl)*

**Comment by PlagueHO** [comment]
Hi @johlju - I've fixed the merge conflicts. Can you check sign this off again please? Thanks sir!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/181#-:-KrGrt9luevCMmIq2y_b:bnfp4nl)*

**Comment by PlagueHO** [comment]
@kwirkykat , @mbreakey3 - are either of you able to merge this for me when you get a moment?

**Comment by PlagueHO** [comment]
Thank you @kwirkykat :grin:

**Pull request merged**
