### PR TITLE
Added test function for Class based resources and adjusted test logic…

### PR DESCRIPTION
**Pull request by bgelens**
… appropriately

This will test the psm1 file containing Class based resources for parse errors but skips the schema check.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/75)

### CODE REVIEW

**Comment by bgelens** [comment]
Just ran against DSC Class resource. See results: https://ci.appveyor.com/project/bgelens/dockerdsc/build/0.0.0.5

**Comment by kwirkykat** [comment]
I like it :smile: Just a few comments, but nothing major 

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[Meta.Tests.ps1, line 205 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUstFFpe3V1Sb1EPB-n:-KUstFFpe3V1Sb1EPB-o:b-r7y6f1) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/Meta.Tests.ps1#L205)):*
> -fileName

Since FileName is a parameter, it should be capitalized.
```
-FileName
```

---

*[Meta.Tests.ps1, line 251 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUstMmesjgYt4aOy4CY:-KUstMmesjgYt4aOy4CZ:b-r7y6f1) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/Meta.Tests.ps1#L251)):*
> -fileName

Since FileName is a parameter, it should be capitalized.
```
-FileName
```

---

*[TestHelper.psm1, line 525 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUssFp2IBXehirhzlA3:-KUssFp2IBXehirhzlA4:bj0a8qv) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/TestHelper.psm1#L525)):*
> param(
>         [Parameter(ValueFromPipeline=$True,Mandatory=$True)]
>         [string]$fileName
>     )

The parameter name here needs to be capitalized.
To match the DSC Resource Kit [style guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters) (I know there are a lot of them sorry), the param block should look like this:

```
param
(
    [Parameter(ValueFromPipeline = $true, Mandatory = $true)]
    [String] $FileName
)
```

---

*[TestHelper.psm1, line 528 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUsspOQsanu_MWBN0Jx:-KUsspORGYrDbyynogXm:bex1lha) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/TestHelper.psm1#L528)):*
> $fileName

Since this is a parameter, FileName should be capitalized here as well.
```
$FileName
```

---

*[TestHelper.psm1, line 530 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUss-ekqkqOLSfZHYIz:-KUss-ekqkqOLSfZHYJ-:b-94cp3h) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/TestHelper.psm1#L530)):*
> $result = foreach

If you just return true from inside the foreach loop, you don't need to catch the result
```foreach (...```

---

*[TestHelper.psm1, line 534 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUsrnIjQLjh7FEpL3cz:-KUsrnIjQLjh7FEpL3d-:b-hmd193) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/TestHelper.psm1#L534)):*
> $true

```return $true```

---

*[TestHelper.psm1, line 539 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUsrj1ck4pYzNLLkGp1:-KUsrj1ck4pYzNLLkGp2:b-kwf5iu) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/TestHelper.psm1#L539)):*
> if ($result)
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>     {
>         $true
>     }
>     else
>     {
>         $false
>     }
</details>

if you just return true in the foreach loop above this can all be replaced with:
```return $false```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-:-KUstUigSYo-ccj1-6Gj:br9hucg)*

**Comment by bgelens** [comment]
Fixed the issues. I changed the parameter name to Path as it makes more sense and adjusted the functions code to be more condensed.

**Comment by kwirkykat** [comment]
@bgelens Almost there! Just forgot to change param name in the help comment

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[TestHelper.psm1, line 525 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUssFp2IBXehirhzlA3:-KUwyqkjp09SIBVN1Rzz:bkh3tlf) ([raw file](https://github.com/powershell/dscresource.tests/blob/908f2416b3c7095e1fa253aaf3c2c1794fdcfa1d/TestHelper.psm1#L525)):*
The param block still doesn't quite match:

> (ValueFromPipeline=$True, Mandatory=$True)

```
(ValueFromPipeline = $true, Mandatory = $true)
```

> [string]

```
[String]
```

Sorry to be nitpicky about it, but since you have another typo to fix might as well do this at the same time.

---

*[TestHelper.psm1, line 513 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-KUwyhObMP8q_vOmsKmQ:-KUwyhObMP8q_vOmsKmR:b-fibojf) ([raw file](https://github.com/powershell/dscresource.tests/blob/9cff337f1417c0dee3aaa2b50e199ccad457b084/TestHelper.psm1#L513)):*
> fileName

Forgot to change the parameter name here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-:-KUwz_nchP_ee_GwiFPf:b-miwj3q)*

**Comment by bgelens** [comment]
Hope this is it :-)

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/75#-:-KUxIYhXs0o0e_eRCdpy:bnfp4nl)*

**Pull request merged**
