### PR TITLE
Add function to run tests more consistently

### PR DESCRIPTION
**Pull request by TravisEz13**
Tested here:
https://github.com/TravisEz13/xWindowsUpdate/commit/b4b3156a4d47eb4b7793a1be51da3ea8ecc4f3c8
Results here:
https://ci.appveyor.com/project/TravisEz13/xwindowsupdate

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/87)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @TravisEz13:

This looks like it is replicating much of the functionality in PR #85.

How will this work with resources that use a test harness (e.g. SharePointDsc and xNetworking - as well as xSQLServer soon)?

This PR does seem to be in conflict with much of discussion that has been happening in these PR's:
https://github.com/PowerShell/DscResources/issues/246
https://github.com/PowerShell/DscResources/issues/180
https://github.com/PowerShell/DscResources/issues/205
https://github.com/PowerShell/DscResources/issues/244
https://github.com/PowerShell/xNetworking/issues/177

I'd suggest that this is looked at in conjunction with the HQRM modules SharePointDsc and xNetworking before it is merged :cry: Sorry to throw my oar in!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[TestRunner.psm1, line 137 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/87#-KcEgcsgevnXLyOEfxYU:-KcEgcsh5J3Gmrm01Wvi:byfhtnj) ([raw file](https://github.com/powershell/dscresource.tests/blob/cb949903e3057a652dd2bbf56792bdba8f9ae19e/TestRunner.psm1#L137)):*
> ```PowerShell
> 
> #>
> function Push-TestArtifact
> ```

I don't think this Module is the correct place for this function. This should be added to AppVeyor.psm1 as it is an AppVeyor only cmdlet. AppVeyor.psm1 was added in #85 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/87#-:-KcEeti4ywfLmhP2Jkp2:b-3s7rr8)*

**Comment by TravisEz13** [comment]
Reviewing what has been done in the SharePointDsc... I think this idea of a test harness is counter to the idea of HQRM.  We want to have a common, reliable test harness.  If functionality is required above and beyond Pester that is not specific to the module (reviewing SharePoint's harness most of it is not,) it should be added to a common module.

We should not have different harnesses in each resource.

AppVeyor.psm1 is not currently part of the code.  I think the module, as is, is too small to be factored into multiple modules.  I was planning the refactoring in later updates.

I disagree reviewing the discussion is most of the threads.  I think the creation of test harnesses was due to the lack of such functionality in the central repro.

**Comment by TravisEz13** [comment]
I filed #88 to give you an idea of all the work involved in this project.

**Comment by TravisEz13** [comment]
reviewing #85 it looks like it might have achieved the first goal in #88.  Let's discuss.

**Comment by PlagueHO** [comment]
What I guess I'm hoping for is some consistent plan or instruction for sharing all the common tests and code between all the different repos that works for all repositories (including SharePointDsc and xNetworking). I really don't like code replication and there is a huge amount of it across the tests, AppVeyor and deployment code - my PR was intended to help address that.

There is so much tech debt being introduced every time the test/deploy process is changed that if we reduce the amount of code replication in the test/deploy code across the resources then we reduce the amount of tech debt being added. This means that adding "code coverage" or additional common test types cost us all less in the long run. So I do think that it would be much more cost effective (tech debt wise) to add the shared test/deploy code before adding code coverage changes.

Plus making these test/deploy processes consistent makes it so much easier to maintain.

I'm not totally sure why the Test Harness was used by SharePointDsc (@BrianFarnhill could you clarify?), but @TysonJHayes has copied this over to xNetworking. xSQLServer and xStorage are both also being moved over to this as well. If the test harness method is going to be in conflict with what you're doing then shouldn't this be addressed before making this change?

Anyway, I completely agree with your goals in #88. What I'm hoping is that it can be made to work for xNetworking, SharePointDsc, xSQLServer and xStorage as well as combined with the work I've been doing unifying the common tests and AppVeyor code.

I'll leave this discussion to the rest of the community as I've got a lot of other stuff on right now and am happy to go with whatever you all think is best (you're the experts :grin:)

**Comment by TravisEz13** [comment]
#90 replaces this PR

**Pull request closed without merging**
