### PR TITLE
Test-PublishMetadata: Add Processing for InvalidGUID Error from Test-ScriptFileInfo

### LINKED ISSUE #330: Test-PublishMetadata: Exception Raised If the Example being tested has an invalid GUID
#### Details of the problem, bug, or enhancement

If `Test-PublishMetadata` is run against a DSC example that contains file metadata with an invalid GUID, an exception is thrown.

Example: PowerShell/xActiveDirectory#409

#### Verbose logs showing the problem (if applicable)

```powershell
Test-PublishMetadata -Path invalid_example_config.ps1
InvalidGuid,Test-ScriptFileInfo
At \DscResource.Tests\DscResource.GalleryDeploy\DscResource.GalleryDeploy.psm1:302 char:17
+                 throw $_
+                 ~~~~~~~~
    + CategoryInfo          : OperationStopped: (InvalidGuid,Test-ScriptFileInfo:String) [], RuntimeException
    + FullyQualifiedErrorId : InvalidGuid,Test-ScriptFileInfo
```

#### Suggested solution to the issue

Add processing for this error to the `Test-PublishMetdadata` function so that only a warning is shown, and improve the unknown error throw by outputting the file details as well as the error.

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR adds processing to `Test-PublishMetaData` for the `InvalidGUID` error from `Test-ScriptFileInfo`. It also improves the unknown error message by adding file path information to the error message and updates the tests.

The `DscResource.GalleryDeploy/en-US/DscResource.GalleryDeploy.strings.psd1` strings were also aligned for readability.

#### This Pull Request (PR) fixes the following issues

- Fixes #330 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/331)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@X-Guardian, can you resolve the conflicts on this one?

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/331)* status: all files reviewed, 1 unresolved discussion (waiting on @X-Guardian)

___
*[CHANGELOG.md, line 5 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/331#-LiqeGhc7c2agzLyurSX:-LiqeGhdBTSwdVtlhiQg:bkn9ho6) ([raw file](https://github.com/powershell/dscresource.tests/blob/9a4672556e78bbda1572ea56c6073bc06c1c0184/CHANGELOG.md#L5)):*
> ```Markdown
> ## Unreleased
> 
> - Added processing to `Test-PublishMetaData` for the InvalidGUID error from Test-ScriptFileInfo ([issue #330](https://github.com/PowerShell/DscResource.Tests/issues/330)).
> ```

Can you check the length of this line? It looks like it should actually fail markdown tests.

**Review by X-Guardian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/331)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 5 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/331#-LiqeGhc7c2agzLyurSX:-LiqhX1Z-bs7Y7h8aXAY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/9a4672556e78bbda1572ea56c6073bc06c1c0184/CHANGELOG.md#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you check the length of this line? It looks like it should actually fail markdown tests.
</blockquote></details>

Done.

**Comment by PlagueHO** [comment]
Hi @X-Guardian - sorry - one more conflict (I merged your other one).

**Review by PlagueHO — APPROVED** [review]
FYI: rather than merging Dev to resolve commit use the Rebase method (see https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts). This results in a cleaner Git commit history.

Great stuff though @X-Guardian

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/331#-:-LivROqf9d0C-JF8ntG8:bycrep4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/331#-:-LivRtIC8WzccXyyGscT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
