### PR TITLE
Complete Unit tests for Wiki Generation and Support for new Example Format - Fixes #247

### LINKED ISSUE #247: Improve Wiki Generation to Handle Example Format used in Gallery Publish
The new Example Gallery publish function (https://github.com/PowerShell/DscResource.Tests#deploy) requires Example files to be in a slightly different format than the Wiki auto generation: https://github.com/PowerShell/DscResource.Tests/blob/dev/DscResource.DocumentationHelper/WikiPages.psm1

The Wiki Auto generation needs to be adjusted to also support the Example format required by the gallery publish function. This will require allowing .DESCRIPTION or .SYNOPSIS instead of .EXAMPLE and also to ignore the #requires lines.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds unit test coverage for the Wiki Generation functions and refactors the functions to make them easier to test. It also adds support for the changes to the example format required by the auto example publish code.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/250)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I have tested these changes against the following auto-generation repos (both harness and non-harness):
NetworkingDsc: https://ci.appveyor.com/project/PlagueHO/networkingdsc/build/artifacts
SharepointDsc: https://ci.appveyor.com/project/PlagueHO/sharepointdsc-r23cy/build/artifacts
WSManDsc: https://ci.appveyor.com/project/PlagueHO/wsmandsc/build/artifacts

**Comment by johlju** [comment]
@PlagueHO I think the tests fail because in AppVeyor when code is checkout out the line break is LF, but locally they are CRLF. So maybe just replace all CR from the strings before the compare? 
I saw this problem in example publishing whee I had to change the autocrlf, so that's an option too. See the second Note-quote in this section; https://github.com/PowerShell/DscResource.Tests#powershell-gallery-api-key

**Comment by PlagueHO** [comment]
I've run into this before too - and it's always a real pain to fix. Fixing this by manipulating the CRLF in the tests seems like it'll be pretty brittle. I feel like it might just be better to use a .gitattributes file in the repo to force EOL to CRFL. This does fix the problem.

**Comment by PlagueHO** [comment]
@johlju - should be good to go now!

**Comment by johlju** [comment]
@PlagueHO Merged

**Pull request merged**
