### PR TITLE
Added unit tests to increase code coverage

### PR DESCRIPTION
**Pull request by johlju**
- Added a wrapper Set-PSModulePath for setting $env:PSModulePath to be able to
  write unit tests for the helper functions with more code coverage.
- Minor typos and cleanup in helper functions.
- Fixed a bug in Install-DependentModule when calling the helper function using
  a specifik version to install. Now Get-Module will no longer throw an error
  that it does not have a parameter named 'Version'.
- Added unit test for helper function in TestHelper to increase code coverage.

This was tested OK here; https://ci.appveyor.com/project/johlju/psdscresources/build/2.4.11.0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/206)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO would you mind doing the initial review on this one? This is mostly unit tests to increase coverage, but had to fix some helper functions as well.

**Comment by johlju** [comment]
Ah... I was hoping to see the new code coverage on this one, but seems CodeCov is having a bad day or something else has gone wrong on it's way there. 

The codeCoveUpload.log says:
```
[41mError:[0m[91m Missing repository upload token[0m
```

That worked a few days ago when last PR was merged, so this must be a temporary thing.
https://ci.appveyor.com/project/PowerShell/dscresource-tests/build/0.2.103.0/artifacts

**Comment by PlagueHO** [comment]
Sure thing @johlju - would be happy to! I'll get it done later today.

**Comment by PlagueHO** [comment]
Wow! Amazing work there @johlju - those tests are fantastic. Also, I didn't know about the `-TestCases` parameter in `It` - this will be very useful for me in future. Reviews where you learn new tricks are the best reviews.

Anyway, just some minor issues.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 528 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OJicr-KN35ag6naQd:-L4OJicr-KN35ag6naQe:b-vak3vk) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/README.md#L528)):*
> ```Markdown
> * Minor typos and cleanup in helper functions.
> * Fixed a bug in Install-DependentModule when calling the helper function using
>   a specifik version to install. Now Get-Module will no longer throw an error
> ```

specifik -> specific

---

*[TestHelper.psm1, line 1212 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OKFVOJWuoFKXA2HMh:-L4OKFVOJWuoFKXA2HMi:bdg33kr) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/TestHelper.psm1#L1212)):*
> ```PowerShell
>         {
>             $requiredModuleExist = `
>                 Get-Module $getModuleParameters |
> ```

Shouldn't this be `Get-Module @getModuleParameters`? I think this may appear to work because Get-Module does accept a Hashtable parameter.

---

*[TestHelper.psm1, line 1219 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OKKkmrvnvRpmmIfVD:-L4OKKkmrvnvRpmmIfVE:bdg33kr) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/TestHelper.psm1#L1219)):*
> ```PowerShell
>         else
>         {
>             $requiredModuleExist = Get-Module $getModuleParameters
> ```

Shouldn't this be `Get-Module @getModuleParameters`? I think this may appear to work because Get-Module does accept a Hashtable parameter.

---

*[TestHelper.psm1, line 1408 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OKl2qcqDEuJX39hC7:-L4OKl2qcqDEuJX39hC8:bxxyan6) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/TestHelper.psm1#L1408)):*
> ```PowerShell
> 
>     .PARAMETER Path
>         A string with all the path separated by semi-colon.
> ```

'A string with all the path separated by semi-colon.' -> 'A string with all the paths separated by semi-colons.'

---

*[Tests/Unit/TestHelper.Tests.ps1, line 927 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4ONuBQzF-IHO7PtUSf:-L4ONuBQzF-IHO7PtUSg:bnhv7v1) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/Tests/Unit/TestHelper.Tests.ps1#L927)):*
> ```PowerShell
>                     $TestType,
> 
>                     # String containing a resource type; Mof och Class.
> ```

Swedish? :grin: och -> or

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-:-L4OOKM0G0xzx2q1nZgc:b6t5blf)*

**Comment by johlju** [comment]
Thanks for the review. Found a bug in the test for `Install-DependentModule`. Changed `-eq` -> `-ne`. Was working, but would have left $env:APPVEYOR when run on a local machine. 
WOnder if this test should be an integration test instead, what do you think? :thinking: 

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[README.md, line 528 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OJicr-KN35ag6naQd:-L4P_r-YRUBX477Og8eh:blbno9r) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/README.md#L528)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

specifik -> specific
</blockquote></details>

Done. Some Swedish got in there :smile: 

---

*[TestHelper.psm1, line 1212 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OKFVOJWuoFKXA2HMh:-L4Pa00QG4kenkUiJGS6:b-376vyo) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/TestHelper.psm1#L1212)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Shouldn't this be `Get-Module @getModuleParameters`? I think this may appear to work because Get-Module does accept a Hashtable parameter.
</blockquote></details>

Done. Good catch!

---

*[TestHelper.psm1, line 1219 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OKKkmrvnvRpmmIfVD:-L4PaHd5D3zwPQ1RHMc6:b-376vyo) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/TestHelper.psm1#L1219)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Shouldn't this be `Get-Module @getModuleParameters`? I think this may appear to work because Get-Module does accept a Hashtable parameter.
</blockquote></details>

Done. Good catch!

---

*[TestHelper.psm1, line 1408 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4OKl2qcqDEuJX39hC7:-L4PaRhkYjzwCcxSH5Sy:boyexb3) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/TestHelper.psm1#L1408)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

'A string with all the path separated by semi-colon.' -> 'A string with all the paths separated by semi-colons.'
</blockquote></details>

Done. Thanks!

---

*[Tests/Unit/TestHelper.Tests.ps1, line 927 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-L4ONuBQzF-IHO7PtUSf:-L4PaSi_NtBeiQk98X0K:bye2poa) ([raw file](https://github.com/powershell/dscresource.tests/blob/857544294f84f05b30ac74eb5046dc83d4ef1a66/Tests/Unit/TestHelper.Tests.ps1#L927)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Swedish? :grin: och -> or
</blockquote></details>

Done. Yes, Swedish again :laughing: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-:-L4PbCruvqpF-bzONzot:bqmow5w)*

**Comment by johlju** [comment]
Btw, test cases are pretty cool and can really shorten the tests :) but I saw that very quickly that one has to add evaluation logic to the tests depending on code path in the function being tested. :/

**Comment by johlju** [comment]
Latest change is tested here: 
https://ci.appveyor.com/project/johlju/sqlserverdsc/build/9.0.329.0
https://ci.appveyor.com/project/johlju/psdscresources/build/2.4.12.0

**Comment by PlagueHO** [comment]
Awesome work @johlju ! :lgtm:

As a side note, we should probably looking at reducing the number of style violation warnings in PSDscResources module: https://ci.appveyor.com/project/johlju/psdscresources/build/2.4.12.0#L671 - that one should probably have a special effort made to meet the style guidelines.

Perhaps one day when I have time I'll do some work correcting all those :grin:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/206#-:-L4SPOLdvAPzdiw_dodD:bacpm59)*

**Comment by johlju** [comment]
Thanks for reviewing @PlagueHO. I saw the warnings in PSDScResources all week. Was itching in my fingers to fix those :laughing: But one thing at a time. :wink:

**Comment by PlagueHO** [comment]
@johlju - haha yeah - one thing at a time. I've been itching to try and pull xWebAdministration in line at some point. I've nearly finished making xNetworking HQRM so once that is complete I might start over there or PSDscResources.

**Comment by johlju** [comment]
@kwirkykat do you have time to look over this an merge so I can get the other two PR rebased? I was waiting for the releases to be finished before gently ask again 😄 Thanks Katie!

**Pull request merged**
