### PR TITLE
Removes DscResource.Tests unit and integration tests from lists of tests when running in another repo - Fixes #189

### LINKED ISSUE #189: Do not run DscResources.Tests unit tests during testing of other repositories
Currently when tests are run in other repositories, they are also running the unit tests for the DscResource.Tests repository. I suggest we look at removing that when testing other repositories. The unit tests for DscResource.Tests take time to finish too which are impacting the time it takes to finish the repos tests (we have a 60 minute window here). 

It also doesn't cause problems in repos, like in PR https://github.com/PowerShell/xNetworking/pull/263.
See error: https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.694.0#L2998

### PR DESCRIPTION
**Pull request by johlju**
- When common tests are running on another repository than DscResource.Tests the
  DscResource.Tests unit and integration tests are removed from the list of tests
  to run (issue #189).

- Tested OK
  - here: https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.259.0#L25
  - here (with run in order): -
 https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.925.0#L42
  _Note: This fails some unrelated tests because of issue #191_
  - And this PR should run all unit tests correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/190)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Whenever you have a chance, can you review this one?

**Comment by PlagueHO** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[AppVeyor.psm1, line 284 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz5z8pgZCaXdJRu9uA:-Ksz5z8pgZCaXdJRu9uB:biyh71h) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/AppVeyor.psm1#L284)):*
> ```PowerShell
>                 of tests to run. Issue #189.
>             #>
>             if( -not (Test-IsRepositoryDscResourceTests))
> ```

Add space after `if`

---

*[TestHelper.psm1, line 1336 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz6hMfezNx5sZ8WJ-d:-Ksz6hMfezNx5sZ8WJ-e:b-x7o28v) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/TestHelper.psm1#L1336)):*
> ```PowerShell
>     )
> 
>     <#
> ```

Nitpick non-blocking: Why not add this code comment into the `.NOTES` for the function?

---

*[TestHelper.psm1, line 1357 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz7IlsrTeLNp52rq0j:-Ksz7IlsrTeLNp52rq0k:btdusia) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/TestHelper.psm1#L1357)):*
> ```PowerShell
>     $moduleRootFilePath = Split-Path -Path $PSScriptRoot -Parent
> 
>     $moduleManifestExistInModuleRootFilePath = Get-ChildItem -Path $moduleRootFilePath -Filter '*.psd1'
> ```

Do you think it would be possible to improve this test by actually testing for the existence of `Meta.Tests.ps1` instead of the absence of a manifest? As I wonder if this is a safer indicator to determine if we're in the DSCResource.Tests folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/190)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[TestHelper.psm1, line 1357 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz7IlsrTeLNp52rq0j:-Kt1WoJfSYayxBIqVrGd:bycuhxq) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/TestHelper.psm1#L1357)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Do you think it would be possible to improve this test by actually testing for the existence of `Meta.Tests.ps1` instead of the absence of a manifest? As I wonder if this is a safer indicator to determine if we're in the DSCResource.Tests folder.
</blockquote></details>

We are not looking if we are in the DscResource.Tests folder, but it it is the DscResource.Tests repository project being tested or not. Would love to have a better way to determine if we are running tests for the DscResource.Tests.

There is two scenarios

1. Testing DscResource.Tests; path `C:\Projects\DscResource.Tests`, or `V:\Source\GitHub\DscResource.Tests` (or any other path used by users).
1. Testing xStorage; path `C:\Projects\xStorage\DscResource.Tests`, or `V:\Source\GitHub\xStorage\DscResource.Tests` (or any other path used by users).

In both these scenarios, when the tests are run, the $PSScriptRoot is set to the root of the the above path, set to the DscResource.Tests folder. So we can't use the current folder to determine if we are running in scenario 1 or 2, for example see if Meta.Tests.ps1 exists, because that would be true for both scenarios.
What it currently does, is to got to the parent folder to see if there is a module manifest, if the module manifest exist then it will assume scenario 2, if the module manifest does not exist it will assume scenario 2. 

I don't see your suggestion working. :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/190)*

**Comment by johlju** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[AppVeyor.psm1, line 284 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz5z8pgZCaXdJRu9uA:-Kt1fMhqtxORkst4rSru:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/AppVeyor.psm1#L284)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Add space after `if`
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1336 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz6hMfezNx5sZ8WJ-d:-Kt1fO_QBMc6z768xkMZ:b-p3bqke) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/TestHelper.psm1#L1336)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick non-blocking: Why not add this code comment into the `.NOTES` for the function?
</blockquote></details>

Done. Added more text as well (from the review comment). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/190)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[TestHelper.psm1, line 1357 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-Ksz7IlsrTeLNp52rq0j:-Kt3D0bznyZb2YKA8PfB:bgro9gi) ([raw file](https://github.com/powershell/dscresource.tests/blob/a630afb73c5ef91e6900ff90ee67a7cc85e8a5c6/TestHelper.psm1#L1357)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We are not looking if we are in the DscResource.Tests folder, but it it is the DscResource.Tests repository project being tested or not. Would love to have a better way to determine if we are running tests for the DscResource.Tests.

There is two scenarios

1. Testing DscResource.Tests; path `C:\Projects\DscResource.Tests`, or `V:\Source\GitHub\DscResource.Tests` (or any other path used by users).
1. Testing xStorage; path `C:\Projects\xStorage\DscResource.Tests`, or `V:\Source\GitHub\xStorage\DscResource.Tests` (or any other path used by users).

In both these scenarios, when the tests are run, the $PSScriptRoot is set to the root of the the above path, set to the DscResource.Tests folder. So we can't use the current folder to determine if we are running in scenario 1 or 2, for example see if Meta.Tests.ps1 exists, because that would be true for both scenarios.
What it currently does, is to got to the parent folder to see if there is a module manifest, if the module manifest exist then it will assume scenario 2, if the module manifest does not exist it will assume scenario 2. 

I don't see your suggestion working. :/
</blockquote></details>

Ah no - I misunderstood the actual intent of the function - so that was my fault. I understand now.

I'm just thinking about the test process of the harness type modules, but I think this should work for them as well.

I tested this against a harness type module and it works well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-:-Kt3DTn3g2y_1esyhyy-:bnfp4nl)*

**Comment by johlju** [comment]
@PlagueHO Can you sign off on the README.md after rebase?

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/190#-:-KtQZa3l98SFCcMB0ieZ:bnfp4nl)*

**Pull request merged**
