### PR TITLE
Improved Wiki documentation generation to address more example file types - Fixes #256

### LINKED ISSUE #256: Wiki Content Generated Incorrectly when Examples Include PSScriptInfo Block
When the examples include a PSScriptInfo block in the header the Wiki Content pages are generated incorrectly. The PSScriptInfo is left in the file:

image

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR improves the Wiki generation code to handle more example formats - specifically the format required to be published to the PS Gallery.

This also adds a lot more unit testing over the code.

#### This Pull Request (PR) fixes the following issues

- Fixes #256

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju and @ykuijs - would you mind reviewing when you have time? I've added a specific test based around an example in SharePointDsc to validate that it hasn't broken Wiki generation for SharePointDsc (or NetworkingDsc & ComputerManagementDsc) - which haven't yet moved to the new publishing format.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/306)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
This looks good to me, then tests passes, but would it be possible to see the actual output (artifact) from a test run in for example SharePointDsc? It that output looks good, then I say just merge this. :slightly_smiling_face: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/306#-:-LSj0COp-fLnp_B1nJWu:b3ugu1n)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[package-lock.json, line 0 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/306#-LSiz1ZO9wgGwiDLf-q_:-LSiz1ZO9wgGwiDLf-qa:bommcat) ([raw file](https://github.com/powershell/dscresource.tests/blob/ba88ea516bbe8ebf0b36a0595405bbf44f0bf8ff/package-lock.json#L0)):*
Not sure we should add this file. Maybe we should add this filename to the .gitignore file instead?

**Review by PlagueHO — COMMENTED** [review]
Great idea! I had planned to do that but got distracted. Generating the output now! I'll paste in here when the CI is finished.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/306#-:-LT6VT285P8raB8TNLGB:bkxv1eh)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[package-lock.json, line  at r1](https://reviewable.io/reviews/powershell/dscresource.tests/306#-LSiz1ZO9wgGwiDLf-q_:-LT6WNN50mkjrJIMIPO8:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ba88ea516bbe8ebf0b36a0595405bbf44f0bf8ff/package-lock.json#L)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not sure we should add this file. Maybe we should add this filename to the .gitignore file instead?
</blockquote></details>

Done.

**Review by johlju — COMMENTED** [review]
It failed on the spell checking for the word 'gitignore'. This is the down side of spell checking. :/
https://ci.appveyor.com/project/PowerShell/dscresource-tests/builds/20838139#L278

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/306#-:-LT9-GEB-oUYaTHctAuK:b-h3m3q3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PlagueHO** [comment]
Here are all the examples:
- CertificateDsc: https://ci.appveyor.com/api/buildjobs/nwdq3c5qhkpme2or/artifacts/CertificateDsc_2.3.56.0_wikicontent.zip
  - Screenshot: 

image

- NetworkingDsc: https://ci.appveyor.com/api/buildjobs/20dnp7395b0rss61/artifacts/NetworkingDsc_3.1.48.0_wikicontent.zip
  - Screenshot:
 
image

- SharepointDsc: https://ci.appveyor.com/api/buildjobs/y8eej8ae6jrxq8hf/artifacts/SharePointDsc_2.4.0.3_wikicontent.zip
  - Screenshot:
image

@johlju - should be good to go :grin:

**Review by johlju — COMMENTED** [review]
:lgtm:

Awesome work on this! 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/306#-:-LTC1pGK7Y4aiHXsgxeh:b-3c7yn7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PlagueHO** [comment]
@ykuijs - are you OK with me merging this one (as SharePointDsc etc) are the only other repos that could be affected by this one (although I hope I've done a decent job to check all will be good :grin:)

**Comment by ykuijs** [comment]
@PlagueHO Sure, go ahead!

**Comment by PlagueHO** [comment]
Thanks @ykuijs !

**Pull request merged**
