### PR TITLE
DscResource.Tests run it's own unit tests on it self - Fixes #170

### LINKED ISSUE #170: Run common tests on DscResource.Tests repository
I think we need to add so that we run common tests on this repository. This would prevent issue like #169.

### PR DESCRIPTION
**Pull request by johlju**
- Added so that DscResource.Tests is testing it self with it's own common tests (issue #170).
- Change README.md to resolve lint error MD029 and MD036.
- Added module manifest for manifest common tests to pass.

**NOTE 1: This one is dependent on that AppVoyer is activated for this repository.**
**NOTE 2: This one is dependent on PR #174.**

This has been tested here (against PR #174); https://ci.appveyor.com/project/johlju/dscresource-tests/build/0.2.25.0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/175)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@johlju AppVeyor is hooked up to this repo now. It won't pass until this PR with the appveyor.yml goes through though

**Comment by kwirkykat** [comment]
@johlju Closing and re-opening PR to trigger AppVeyor

**Comment by johlju** [comment]
@kwirkykat Tests will fail until PR #174 is merged. I will fix review comments tomorrow. Didn't have time today. :)

**Comment by johlju** [comment]
@kwirkykat This one is rebased and ready for review. I also shortened the PR title, since it was a bit to long.

**Comment by johlju** [comment]
@kwirkykat Do you have time to review this one so we can get the tests going in this repo? 😄

**Pull request merged**
