### PR TITLE
Resolves #31, Added test and fixer for text files ending with new lines

### LINKED ISSUE #31: Add test for having a new line at the end of a file
This has come up a number of times in peer review and would be nice to automate.

### PR DESCRIPTION
**Pull request by dcrreynolds**

### CODE REVIEW

**Comment by PlagueHO** [comment]
I like this! LGTM.

**Comment by vors** [comment]
LGTM. But we need to make sure all current repos are passing this test, before merging it.

Would be good to have a comment about motivation for this test, so people can read explanation. In the form of comment on the test, or maybe inside the warning text, ever works.

**Comment by dcrreynolds** [comment]
Would something like the sample output below provide enough detail? A tool could be made that would run the test in this repo against the existing DSC resources to help us determine what would fail when we update the test. 

WARNING: To improve consistency across multiple environments and editors each text file is required to end with a new line.
WARNING: C:\example.ps1 does not end with a new line. Use Fixer 'Add-NewLine'

**Comment by KarolKaczmarek** [comment]
we have module for running all tests here: https://github.com/PowerShell/DscResource.Tests/blob/master/TestRunner.psm1

Proposed warning looks good

**Comment by TravisEz13** [comment]
Sorry I merged this change but then reverted it.  This might break projects that are currently passing.  

1. We could run it on everything and fix all the issues
2. Add the test, make it always pass but print a warning.  After we think we have fixed enough of the projects

**Comment by KarolKaczmarek** [comment]
@dcrreynolds Could you run all the tests (script in my previous comment) to see how many modules need to be fixed and provide the list here? Fixing those should be pretty quick. Feel free to resend this PR since we can't reopen it after reverting.

**Pull request merged**
