### PR TITLE
AppVeyor: Added failure message to be published to "Tests-view" - Fixes #138

### LINKED ISSUE #138: When tests fail the Tests-view in AppVeyor is not updated with the error message
Suggest we update change to that error message and stack trace are also submitted to AppVeyor after test run.

Example screenshot:
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.558.0/tests

image

### PR DESCRIPTION
**Pull request by johlju**
- Changes to AppVeyor
  -  Added so that any error message for each test are also published to the AppVeyor "Tests-view".

There was some spaces that was removed as well when I saved the file in VS Code (have auto-trim enabled). So there are a few rows that was changes because of that.

This branch was used to mock fails: 
https://github.com/johlju/xSQLServer/tree/appveyor-test

Test run here and example in screenshot:
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.558.0/tests

image

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/137)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Do you mind taking a look at this? 😄

**Comment by PlagueHO** [comment]
@johlju - of course! It will be a pleasure. I'll review after work tonight! :grin:

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/137#-:-KjBUq_Iz5qPTIIxiJIs:bnfp4nl)*

**Comment by johlju** [comment]
@mbreakey3 @kwirkykat Could you look over this and merge it when ever you have a chance? 

@PlagueHO Thanks for the review! 😄

**Comment by mbreakey3** [comment]
Looks good, can you just update the readme?

**Comment by johlju** [comment]
Ah sorry, of course! I did not remember we had an  unreleased section there. :) It will be there in a bit.

**Comment by johlju** [comment]
@mbreakey3 Updated unreleased section! 😄

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/137#-:-KjK-37kgkJXZTGvib3k:bnfp4nl)*

**Pull request merged**
