### PR TITLE
Preparation to be able to run common tests against this module

### PR DESCRIPTION
**Pull request by johlju**
- Changes to DscResource.Tests
  - Fixed so that code coverage can be scan for code even if there is no DSCResource folder.
  - Added workaround for AppVeyor replaces punctuation in folder structure for DscResource.Tests.
  - Remove the $repoName variable and replace it with $moduleName. It was duplicate.

**NOTE: This must be merged before PR #175, which is dependent on this one.**

These changes has been tested for DscResource.Tests to be able to test it self here; https://ci.appveyor.com/project/johlju/dscresource-tests/build/0.2.16.0

These changes has been tested so they don't change anything for other modules. Tested here; 
https://ci.appveyor.com/project/johlju/xsqlserver

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/174)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Just the two issues to look into. The minor suggestions around grammar are non-blocking :grin: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[AppVeyor.psm1, line 225 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy4pio0BbEg2byIHnr:-Kpy4pipI2jXJkY--L4y:bnlksl9) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/AppVeyor.psm1#L225)):*
> ```PowerShell
> 
>                 # Only add code path for DSCResources if they exist.
>                 if (Test-Path -Path "$env:APPVEYOR_BUILD_FOLDER\DSCResources" )
> ```

I think this will break codecoverage generation for the autodocumentation type resources (xNetworking, SharePointDsc etc). This is because those repos have the path "$env:APPVEYOR_BUILD_FOLDER\Modules\<ModuleName>\DSCResources\" (e.g. "$env:APPVEYOR_BUILD_FOLDER\Modules\xNetworking\DSCResources\")

You could check for either path, but a more effective way of determining

---

*[Meta.Tests.ps1, line 21 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy6pJbvr1LOKBjhfag:-Kpy6pJbvr1LOKBjhfah:b-gjv7fz) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/Meta.Tests.ps1#L21)):*
> ```PowerShell
> <#
>     This is a workaround to be able to test DscResource.Tests module.
>     Because the name has a punctuation in the name, AppVeyor replaces
> ```

Should be: Because the name has punctuation in the name, AppVeyor replaces

---

*[Meta.Tests.ps1, line 28 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy6JCy8tk1KRcSU7CM:-Kpy6JCy8tk1KRcSU7CN:b5cei80) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/Meta.Tests.ps1#L28)):*
> ```PowerShell
>     and all other modules, then this could be removed.
> #>
> if( $moduleName -eq 'dscresource-tests')
> ```

Please add space after `if` and remove after (

---

*[README.md, line 398 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy8cHIfuL4x8VJczYU:-Kpy8cHIfuL4x8VJczYV:b9tk4in) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/README.md#L398)):*
> ```Markdown
> * Fixed so that code coverage can be scan for code even if there is no DSCResource
>   folder.
> * Added workaround for AppVeyor replaces punctuation in folder structure for
> ```

Should be: Added workaround for AppVeyor that replaces punctuation in folder structure for

---

*[README.md, line 400 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy8j7Wg-GDCfYm9zqt:-Kpy8j7Wg-GDCfYm9zqu:bu88jd0) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/README.md#L400)):*
> ```Markdown
> * Added workaround for AppVeyor replaces punctuation in folder structure for
>   DscResource.Tests.
> * Remove the $repoName variable and replace it with $moduleName. It was duplicate.
> ```

Could be: Remove the $repoName variable and replace it with $moduleName as it was a duplicate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-:-Kpy8ymdLOTspVw4Riu7:b81gc40)*

**Comment by johlju** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[AppVeyor.psm1, line 225 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy4pio0BbEg2byIHnr:-Kq6mLF8MCN8zLX4xqHc:baminr3) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/AppVeyor.psm1#L225)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this will break codecoverage generation for the autodocumentation type resources (xNetworking, SharePointDsc etc). This is because those repos have the path "$env:APPVEYOR_BUILD_FOLDER\Modules\<ModuleName>\DSCResources\" (e.g. "$env:APPVEYOR_BUILD_FOLDER\Modules\xNetworking\DSCResources\")

You could check for either path, but a more effective way of determining
</blockquote></details>

Done.

Sorry, should have tested it!

Tested here for the "Default"-model: https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.159.0
Tested here for the "Harness"-model: https://ci.appveyor.com/project/johlju/xnetworking/build/3.1.4.0

---

*[Meta.Tests.ps1, line 21 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy6pJbvr1LOKBjhfag:-Kq6moqN0lgeKcsMVN14:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/Meta.Tests.ps1#L21)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be: Because the name has punctuation in the name, AppVeyor replaces
</blockquote></details>

Done.

---

*[Meta.Tests.ps1, line 28 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy6JCy8tk1KRcSU7CM:-Kq6mq5mKVB3-GBc3xT4:behvxxt) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/Meta.Tests.ps1#L28)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please add space after `if` and remove after (
</blockquote></details>

Done.

Fixed a bunch of these in the files in this PR (was more in other files, but did not want to fix those in this PR). Reviewable is not showing white-space changes so visible, but here they are; https://github.com/PowerShell/DscResource.Tests/pull/174/commits/2c6d10789fedd575ad5f7364a26213f9ed604780

---

*[README.md, line 398 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy8cHIfuL4x8VJczYU:-Kq6uWcmljtBZp70AcKu:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/README.md#L398)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be: Added workaround for AppVeyor that replaces punctuation in folder structure for
</blockquote></details>

Done.

---

*[README.md, line 400 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy8j7Wg-GDCfYm9zqt:-Kq6uXzpnR6plM524bJf:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/README.md#L400)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could be: Remove the $repoName variable and replace it with $moduleName as it was a duplicate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/174)*

**Comment by PlagueHO** [comment]
Fantastic stuff here!

:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[AppVeyor.psm1, line 225 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-Kpy4pio0BbEg2byIHnr:-Kq6vfssLc_elvFW15qO:b2vlteo) ([raw file](https://github.com/powershell/dscresource.tests/blob/99858da97c129c4cf32d9f3052c9aad7709daece/AppVeyor.psm1#L225)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.

Sorry, should have tested it!

Tested here for the "Default"-model: https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.159.0
Tested here for the "Harness"-model: https://ci.appveyor.com/project/johlju/xnetworking/build/3.1.4.0
</blockquote></details>

All good! Looks great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/174#-:-Kq6w0LFQLDfwBsiMXOR:b-slr93t)*

**Comment by johlju** [comment]
@kwirkykat or @mbreakey3 Can you review and merge this one, so we can get the tests going in PR #175?
Tests will fail until we get PR #175 merged, and PR #175 i dependent on this one.

**Pull request merged**
