### PR TITLE
CodeCovIo: Using codecov.exe instead of the python script

### LINKED ISSUE #203: CodeCov Upload Error Message
An [error](https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.786.0#L4671) has recently started appearing during upload of the code coverage results to CodeCov.io. _This error appears to not actually prevent upload or fail the build, so is not critical._

The error occurs when calling the `codecov` Python script from [this line](https://github.com/PowerShell/DscResource.Tests/blob/dev/DscResource.CodeCoverage/CodeCovIo.psm1#L335) of the `CodeCovIo` module.

The output of the `codecov` python can be seen in the `CodeCovUpload.log` artifact stored in the [AppVeyor build artifacts](https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.786.0/artifacts). This shows no errors:

```text

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.10

[90m==>[0m Detecting CI provider
    AppVeyor Detected
[90m==>[0m Preparing upload
    Error running `cd 'C:\projects\xnetworking' && git ls-files`: None
[31mXX>[0m Skip processing gcov
[90m==>[0m Collecting reports
[31mXX>[0m Searching for reports disabled
    Targeting specific files
    [32m+[0m C:\Users\appveyor\AppData\Local\Temp\1\codeCov.json bytes=1015201
[90m==>[0m Uploading
    .url https://codecov.io
    .query service=appveyor&commit=287671eeb0117d7374e8102aaf6c329c9d9a7607&package=py2.0.10&branch=dev&build=bsjueksk050yjjm6&job=PowerShell%2Fxnetworking%2F3.1.786.0&pr=291&slug=PowerShell%2FxNetworking
    Pinging Codecov...
    Uploading to S3...
[92m    https://codecov.io/github/PowerShell/xNetworking/commit/287671eeb0117d7374e8102aaf6c329c9d9a7607[0m
```

It also shows the artifact being uploaded. The result can also be seen in CodeCov.io.

The error seems to occur or be outputted into the error stream somewhere in this Python code:
https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py

The last changes to this code was made 5 days ago. looking back through AppVeyor logs, this error started appearing at least 4 days ago but not more than 6 days ago - so this would track with the recent changes made to the CodeCov Python.

This is occurring in all repos that process and upload code coverage.

### PR DESCRIPTION
**Pull request by johlju**
- Changes to CodeCovIo
  - Fix codecov no longer generates an error message when uploading test
    coverage (issue #203).

Fixes #203 

Tested here: https://ci.appveyor.com/project/PowerShell/dscresource-tests/build/0.2.163.0#L1684
tested here (this PR): https://ci.appveyor.com/project/PowerShell/dscresource-tests/build/0.2.163.0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/223)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Can you review this when you have a chance?

**Comment by PlagueHO** [comment]
Awesome! So cool that this works! :grin:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[DscResource.CodeCoverage/CodeCovIo.psm1, line 332 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/223#-LBUu-C2DApCct0LWkFO:-LBUu-C2DApCct0LWkFP:b-6mpz58) ([raw file](https://github.com/powershell/dscresource.tests/blob/2078034765f7b648f725ec57dbf05a646b6b8867/DscResource.CodeCoverage/CodeCovIo.psm1#L332)):*
> ```PowerShell
>     }
> 
>     & choco install codecov | Out-Null
> ```

Doesn't a `-y` parameter need to be added here to suppress the confirmation prompt?

---

*[DscResource.CodeCoverage/CodeCovIo.psm1, line 334 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/223#-LBUt6AC1eqU7cYSvSQA:-LBUt6AC1eqU7cYSvSQB:b645t1r) ([raw file](https://github.com/powershell/dscresource.tests/blob/2078034765f7b648f725ec57dbf05a646b6b8867/DscResource.CodeCoverage/CodeCovIo.psm1#L334)):*
> ```PowerShell
>     & choco install codecov | Out-Null
> 
>     <#
> ```

Does putting the options from codecov need to be added? It seems like we could just be pulled from codecov if we needed it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/223#-:-LBUvDVSByUrdynwy9F1:b-drs0tk)*

**Comment by johlju** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[DscResource.CodeCoverage/CodeCovIo.psm1, line 332 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/223#-LBUu-C2DApCct0LWkFO:-LBVIwcn1ErF4JntBoY2:bqhigjr) ([raw file](https://github.com/powershell/dscresource.tests/blob/2078034765f7b648f725ec57dbf05a646b6b8867/DscResource.CodeCoverage/CodeCovIo.psm1#L332)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Doesn't a `-y` parameter need to be added here to suppress the confirmation prompt?
</blockquote></details>

Done. It did work, but let's add that just in case. Also added so the output is added to the uploadResult log so any problems can be found.
or should we make that a separate log maybe? 'CodecovDownloadLog' maybe?

---

*[DscResource.CodeCoverage/CodeCovIo.psm1, line 334 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/223#-LBUt6AC1eqU7cYSvSQA:-LBVIhA5CyAG-0wR4kz6:bps5sse) ([raw file](https://github.com/powershell/dscresource.tests/blob/2078034765f7b648f725ec57dbf05a646b6b8867/DscResource.CodeCoverage/CodeCovIo.psm1#L334)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Does putting the options from codecov need to be added? It seems like we could just be pulled from codecov if we needed it.
</blockquote></details>

Done. Agreed. It was documented well on their site or in the GitHub repo, but they reference looking at the code, so I linked to the site instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/223)*

**Comment by johlju** [comment]
See the artifact https://ci.appveyor.com/project/PowerShell/dscresource-tests/build/0.2.164.0/artifacts the codecovUpload log now shows both codecov being dowloaded and installed and code coverage being uploaded. See review comment for question. :)

**Comment by johlju** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DscResource.CodeCoverage/CodeCovIo.psm1, line 334 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/223#-LBUt6AC1eqU7cYSvSQA:-LBVoF9m5hbxcHiX0eCB:b-4swxyb) ([raw file](https://github.com/powershell/dscresource.tests/blob/2078034765f7b648f725ec57dbf05a646b6b8867/DscResource.CodeCoverage/CodeCovIo.psm1#L334)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Agreed. It was documented well on their site or in the GitHub repo, but they reference looking at the code, so I linked to the site instead.
</blockquote></details>

Done. Should have said. "It was not documented well..." :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/223)*

**Comment by PlagueHO** [comment]
Awesome stuff @Johlju - can't wait to get this into Master!

:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DscResource.CodeCoverage/CodeCovIo.psm1, line 334 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/223#-LBUt6AC1eqU7cYSvSQA:-LBZjrJf53B5Z5A6LJUd:b-6x8438) ([raw file](https://github.com/powershell/dscresource.tests/blob/2078034765f7b648f725ec57dbf05a646b6b8867/DscResource.CodeCoverage/CodeCovIo.psm1#L334)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Should have said. "It was not documented well..." :)
</blockquote></details>

It is documented reasonably well in the `codecov --help`too. But all good linking to the site.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/223#-:-LBZk90l2t38pYQEUYmq:bk8yvmh)*

**Comment by PlagueHO** [comment]
into Dev I mean!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/223#-:-LBZkGN80jf6ScUkeNmt:b-45quf5)*

**Pull request merged**
