### PR TITLE
Get-MofSchemaObject: Rewrite function to use DscClassCache ImportClasses

### PR DESCRIPTION
**Pull request by danielboth**
#### Pull Request (PR) description
This is a rewrite of the Get-MofSchemaObject function. Instead of parsing text this uses the ImportClasses method of [Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache] to parse the schema.mof. The output is a 1-1 copy (as close as possible) of what the text based parsing used to produce.

#### This Pull Request (PR) fixes the following issues
None

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [X] Unit tests added/updated.
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354)

### CODE REVIEW

**Comment by danielboth** [comment]
Have been writing some tests as well, here the updated function differs from the current one, the current one would fail like this:

```
 [-] Should get property MultipleValues with all correct properties 12ms
   Expected strings to be the same, but they were different.
   Expected length: 11
   Actual length:   6
   Strings differ at index 6.
   Expected: 'StringArray'
   But was:  'String'
   86:             $property.DataType | Should -Be $DataType

 [-] Should get property Credential with all correct properties 7ms
   Expected strings to be the same, but they were different.
   Expected length: 8
   Actual length:   6
   Strings differ at index 0.
   Expected: 'Instance'
   But was:  'String'
   86:             $property.DataType | Should -Be $DataType
```

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354)* status: all files reviewed, 4 unresolved discussions (waiting on @danielboth)

___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 38 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdKtaX-KHstnKqJ6wS:-LsdKtaX-KHstnKqJ6wT:b-e4h7by) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L38)):*
> ```PowerShell
> 
>         $filePath = (Resolve-Path -Path $FileName).Path
>         $tempFilePath = Join-Path -Path $env:TEMP -ChildPath "$((New-Guid).Guid).tmp"
> ```

Nitpick, non-blocking: Could be worth prefixing the filename with something to indicate it belongs to this process (E.g. DscMofHelper_Guid)
___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 43 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdO5Af3aTfeNcaULVx:-LsdO5Af3aTfeNcaULVy:bllh6q7) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L43)):*
> ```PowerShell
>         Set-Content -LiteralPath $tempFilePath -Value $rawContent -ErrorAction Stop
> 
>         #.NET methods don't like PowerShell drives
> ```

Can you add space after #?
___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 61 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdOUZZ2ybN6Ux90zOK:-LsdOUZZ2ybN6Ux90zOL:bqs9sdq) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L61)):*
> ```PowerShell
>     finally
>     {
>         Remove-Item -LiteralPath $tempFilePath -Force
> ```

Should assign this to $null because `Remove-Item` returns objects.
___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 68 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdaSS7AX-aOn6H8Fqk:-LsdaSS7AX-aOn6H8Fql:b-sp8yp) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L68)):*
> ```PowerShell
>         $state = switch ($property.flags)
>         {
>             {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::Key}      {'Key'}
> ```

Nitpick, non-blocking: This doesn't align to style guide, but I don't think we've got a style example that quite aligns here and my thoughts are that this is pretty readable this way. @Johlju? Do we try and get this to align to style guide or leave it?
___
*[Tests/Unit/MofHelper.Tests.ps1, line 8 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-Lsda4r-0SlxaKx52cba:-Lsda4r03aUBuSiodFyt:bj8nrqx) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/Tests/Unit/MofHelper.Tests.ps1#L8)):*
> ```PowerShell
> 
> InModuleScope -ModuleName 'MofHelper' {
> ```

Can you remove blank line?

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354)* status: all files reviewed, 4 unresolved discussions (waiting on @danielboth)

___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 68 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdaSS7AX-aOn6H8Fqk:-LsfS5pN6ZO3n2cUNuSn:b-4lnh4e) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L68)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick, non-blocking: This doesn't align to style guide, but I don't think we've got a style example that quite aligns here and my thoughts are that this is pretty readable this way. @Johlju? Do we try and get this to align to style guide or leave it?
</blockquote></details>

I have written such code like any other switch statement. If this was a "normal" switch statement it would be written like this

```powershell
$state = switch
{
    'hello'
    {
         'key'
    }
}
```

So the code would be written

```powershell
        $state = switch ($property.flags)
        {
            {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::Key}      
            {
                'Key'
            }
           
            {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::Required}
            {
                'Required'
            }
            
            {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::ReadOnly}
            {
                'Read'
            }
            
            default                                                             
            {
                'Write'
            }
        }
``` 

I don't mind the way it looks now, but if we add a custom rule to this I think the rule would be written to enforce the braces like written above, because we can't write to complex rules. :thinking: 

But we can resolve that when that days comes. So @danielboth suggest to leave as-is for now. :slightly_smiling_face:

**Comment by johlju** [comment]
@PlagueHO Remember we can't merge this just yet. @gaelcolas does not want any changes to DscResource.Tests just now since he is in the process of changing the pipeline. 🙂 

@gaelcolas do you want/need this change implemented (merged) "now" to help you, or should we hold off until you are done?

**Review by danielboth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354)* status: all files reviewed, 4 unresolved discussions (waiting on @PlagueHO)

___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 43 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdO5Af3aTfeNcaULVx:-LsfUCdj5opNpc9rdClH:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add space after #?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 61 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdOUZZ2ybN6Ux90zOK:-LsfUEZQEV3gxFfKdzbk:b-slccto) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L61)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should assign this to $null because `Remove-Item` returns objects.
</blockquote></details>

That's our friend New-Item, Remove-Item does not return objects.
___
*[DscResource.DocumentationHelper/MofHelper.psm1, line 68 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-LsdaSS7AX-aOn6H8Fqk:-LsfUTuF52q0AOFSOKw1:bhd387j) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/DscResource.DocumentationHelper/MofHelper.psm1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I have written such code like any other switch statement. If this was a "normal" switch statement it would be written like this

```powershell
$state = switch
{
    'hello'
    {
         'key'
    }
}
```

So the code would be written

```powershell
        $state = switch ($property.flags)
        {
            {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::Key}      
            {
                'Key'
            }
           
            {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::Required}
            {
                'Required'
            }
            
            {$_ -band [Microsoft.Management.Infrastructure.CimFlags]::ReadOnly}
            {
                'Read'
            }
            
            default                                                             
            {
                'Write'
            }
        }
``` 

I don't mind the way it looks now, but if we add a custom rule to this I think the rule would be written to enforce the braces like written above, because we can't write to complex rules. :thinking: 

But we can resolve that when that days comes. So @danielboth suggest to leave as-is for now. :slightly_smiling_face: 
</blockquote></details>

Ok, will leave this for now.
___
*[Tests/Unit/MofHelper.Tests.ps1, line 8 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/354#-Lsda4r-0SlxaKx52cba:-LsfW5kfEAjD8dUIPpif:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/8cd5881e6b8eba4b60a6598e41a26d892a830477/Tests/Unit/MofHelper.Tests.ps1#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove blank line?
</blockquote></details>

Done.

**Comment by johlju** [comment]
Looks like @PlagueHO already talked to @gaelcolas about this in Slack so it sounded like it can be merged when the review is done.

**Comment by gaelcolas** [comment]
That's fine, I'm more on the pssa rules side right now

**Review by PlagueHO — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354#-:-Lt8ya_56SHPksRZguOA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/354)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
