### PR TITLE
Add common test to test the length of the relative file path

### LINKED ISSUE #188: Need a common tests to test the length of the relative file paths
A relative file path cannot exceed 120 characters to be able to compile a configuration in Azure Automation.

See more in issue https://github.com/PowerShell/DscResources/issues/310.

### PR DESCRIPTION
**Pull request by johlju**
- Added a common tests to test the length of the relative file path so the paths
  are not exceeding the current path hard limit in Azure Automation (issue #188).

Fixes #188 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/271)

### CODE REVIEW

**Comment by johlju** [comment]
Tested OK here:
CertificateDsc (test skipped when opt-out): https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.10.0#L59
SqlServerDsc (opt-in): https://ci.appveyor.com/project/johlju/sqlserverdsc?fullLog=true#L149

**Comment by johlju** [comment]
@PlagueHO Another one ready for review, if you have time, no hurry. 🙂

**Comment by davetheunissen** [comment]
For what its worth, I tested this locally and confirmed that it does what it says on the box.

**Comment by johlju** [comment]
@davetheunissen Thank you so much for testing it!

**Pull request merged**
