### PR TITLE
Updated Invoke-AppveyorInstallTask with informational messages

### LINKED ISSUE #293: AppVeyor: Get-PackageProvider output a lot of unnecessary information
We update the NuGet package provider

https://github.com/PowerShell/DscResource.Tests/blob/a522ade40d959fc931dfc9eb2a4ec096b7e3afb1/AppVeyor.psm1#L42-L46

Recently it has started to output a lot of (unnecessary) information. 

https://ci.appveyor.com/project/johlju/xpsdesiredstateconfiguration?fullLog=true#L24
```
Name                    : NuGet
ProviderName            : NuGet
Features                : {[supports-powershell-modules, System.Collections.Generic.List`1[System.String]], [file-extensions, System.Collections.Generic.List`1[System.String]], [uri-schemes, 
                          System.Collections.Generic.List`1[System.String]], [magic-signatures, System.Collections.Generic.List`1[System.String]]}
Version                 : 2.8.5.210
ProviderPath            : C:\Program Files\WindowsPowerShell\Modules\PackageManagement\fullclr\Microsoft.PackageManagement.NuGetProvider.dll
SupportedFileExtensions : {nupkg}
SupportedUriSchemes     : {http, https, file}
DynamicOptions          : {Destination, ExcludeVersion, Scope, SkipDependencies...}
FastPackageReference    : 
Source                  : 
Status                  : 
SearchKey               : 
FullPath                : 
PackageFilename         : 
FromTrustedSource       : False
Summary                 : 
SwidTags                : {NuGet}
CanonicalId             : 
Metadata                : {}
SwidTagText             : <?xml version="1.0" encoding="utf-16" standalone="yes"?>
                          <SoftwareIdentity
                            name="NuGetProvider"
                            version="2.8.5.210"
                            versionScheme="multipartnumeric"
                            media="(windows) and (PackageManagement) and (min-PackageManagement.api:2)" xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd"></SoftwareIdentity>
Dependencies            : {}
IsCorpus                : 
VersionScheme           : multipartnumeric
TagVersion              : 
TagId                   : 
IsPatch                 : 
IsSupplemental          : 
AppliesToMedia          : (windows) and (PackageManagement) and (min-PackageManagement.api:2)
Meta                    : {}
Links                   : {}
Entities                : {}
Payload                 : 
Evidence                : 
Culture                 : 
Attributes              : {name,version,versionScheme,media,xmlns}
```

Suggest handling the output, so it just outputs the necessary information, like ProviderName and Version

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Updated Invoke-AppveyorInstallTask to provide better informational messages
  when installing each prerequisite (issue #293).
- Added unit tests for Invoke-AppveyorInstallTask.

The updated informational messages can be seen in the PR test run:
https://ci.appveyor.com/project/PowerShell/dscresource-tests/build/0.2.383.0#L16

#### This Pull Request (PR) fixes the following issues
- Fixes #293 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/294)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO I rebased this one, so it's ready for review again.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Great stuff @johlju - just a couple of minor queries.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/294#-:-LV-jLq-CJYd4v8vIAd3:beh8p0s)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[AppVeyor.psm1, line 53 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/294#-LV-iLaC85eR69uN2eOx:-LV-iLaDDPWIUAuYJIY9:b6cwxl) ([raw file](https://github.com/powershell/dscresource.tests/blob/d54d11e9ed39311f603e0e1f60225585d1614536/AppVeyor.psm1#L53)):*
> ```PowerShell
>     Install-Module -Name PowerShellGet -Force -Repository PSGallery
> 
>     Write-Info -Message 'Installing nuget.exe v3.4.4 to enable package creation.'
> ```

I'm not sure we should mention the version of Nuget that is being installed as this is likely to get out of sync if someone was to change the behavior of Install-NugetExe. Better approach would be either to not mention the version number in the info message or to allow the Install-NugetExe to accept a -RequiredVersion parameter that allowed us to force a specific version.
___
*[CHANGELOG.md, line 16 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/294#-LV-j3Xt2JsxjCgeYyRy:-LV-j3Xt2JsxjCgeYyRz:buvxtof) ([raw file](https://github.com/powershell/dscresource.tests/blob/d54d11e9ed39311f603e0e1f60225585d1614536/CHANGELOG.md#L16)):*
> ```Markdown
> - Changes to AppVeyor.psm1
>   - Updated Invoke-AppveyorInstallTask to provide better informational messages
>     when installing each prerequisite
> ```

Add full stop at the end here?

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/294)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[AppVeyor.psm1, line 53 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/294#-LV-iLaC85eR69uN2eOx:-LV2qoYY98jgTjgRKYXw:b-486ysk) ([raw file](https://github.com/powershell/dscresource.tests/blob/d54d11e9ed39311f603e0e1f60225585d1614536/AppVeyor.psm1#L53)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'm not sure we should mention the version of Nuget that is being installed as this is likely to get out of sync if someone was to change the behavior of Install-NugetExe. Better approach would be either to not mention the version number in the info message or to allow the Install-NugetExe to accept a -RequiredVersion parameter that allowed us to force a specific version.
</blockquote></details>

Done. Agree, went with refactoring of the helper function, plus new tests for that. I think it's important to know what version is installed in the build log. :slightly_smiling_face: 
___
*[CHANGELOG.md, line 16 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/294#-LV-j3Xt2JsxjCgeYyRy:-LV2rBaJ7Pn3WSXnSNvF:b-xavaap) ([raw file](https://github.com/powershell/dscresource.tests/blob/d54d11e9ed39311f603e0e1f60225585d1614536/CHANGELOG.md#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Add full stop at the end here?
</blockquote></details>

The full stop is end of the closing parenthesis for the issue reference. See [rendered makrdown](https://github.com/PowerShell/DscResource.Tests/blob/6c41706f2e96960bd7410c51a386025fdb981164/CHANGELOG.md).
But if we want to have the full stop before the opening parenthesis then we should change the others as well. Not sure what the proper grammatically way is. :thinking:  But I'm open to either way. :slightly_smiling_face:

**Comment by johlju** [comment]
@PlagueHO I think this is ready for review again. I updated the verbose messages and move some of the text inside the helper function too.

**Review by PlagueHO — APPROVED** [review]
Great stuff @Johlju. :lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/294#-:-LV6_cWe451MMGb_ymsm:b-qkx6z6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
