### PR TITLE
Removed the reference to the function ConvertTo-SpaceIndentation - Fixes #4

### LINKED ISSUE #4: ConvertTo-SpaceIndentation Breaks Files in Some Cases
Recently when I submitted a pull request for changes to the xExchange module, the automated tests failed on a couple files, and suggested running Get-TextFilesList | ConvertTo-SpaceIndentation to fix them. I decided to run this against the entire module, instead of just the files it suggested. After doing so and resubmitting the pull request, I got failures in multiple files that weren't otherwise modified other than running these commands against them. The failures are reported here:

https://ci.appveyor.com/project/PowerShell/xexchange/build/1.0.35

One of the files that broke is located here:

https://github.com/PowerShell/xExchange/blob/dev/DSCResources/MSFT_xExchMailboxDatabase/MSFT_xExchMailboxDatabase.psm1

### PR DESCRIPTION
**Pull request by johlju**
- Changes to common tests
  - Removed the reference to the function ConvertTo-SpaceIndentation from the warning message in the test that checks for tabs in module files. The function ConvertTo SpaceIndentation does not exist anymore (issue #4).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/155)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 371 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/155#-KosJW7jpe48vPeTTlYq:-KosJW7jpe48vPeTTlYr:b-1sp1bn) ([raw file](https://github.com/powershell/dscresource.tests/blob/c869679b5421ee533acf92c5ba13ba3b228a6069/README.md#L371)):*
> ```Markdown
> * Removed the reference to the function ConvertTo-SpaceIndentation from the warning
>   message in the test that checks for tabs in module files. The function
>   ConvertTo-SpaceIndentation does not exist anymore (issue #4).
> ```

Not a blocking nitpick: You include the link to the issue here (e.g. [Issue 4](https://github.com/PowerShell/DscResource.Tests/issues/4) )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/155)*

**Comment by johlju** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 371 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/155#-KosJW7jpe48vPeTTlYq:-KousYLqS5aQ_A0fzG6a:b4kdca7) ([raw file](https://github.com/powershell/dscresource.tests/blob/c869679b5421ee533acf92c5ba13ba3b228a6069/README.md#L371)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not a blocking nitpick: You include the link to the issue here (e.g. [Issue 4](https://github.com/PowerShell/DscResource.Tests/issues/4) )
</blockquote></details>

Done.

I saw @kwirkykat removing # from the release notes (for xSQLServer) published to PowerShell Gallery, so maybe we should not add # and links to README.md/CHANGELOG.md to help Katie with releases (if she needs to clean the entries).
What do you say @kwirkykat is this OK adding reference to issues like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/155)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/155#-:-KouzpMkOLJrEyoJRlg9:bnfp4nl)*

**Comment by kwirkykat** [comment]
@johlju The release script removes any '#' signs from the release notes. It also replaces any single quote (') characters with double quotes instead. This is because the release notes need to go in the module manifest to be posted on the PowerShell Gallery. The manifest is a .psd1 file that interprets '#' as the beginning of a comment. The single quotes also mess up the grouping of the ReleaseNotes string in the module manifest.

These two steps are all done automatically by a script so it's no trouble at all referring to the issues with the '#' character here. But thanks for asking 🙂

**Comment by johlju** [comment]
@kwirkykat Ah good! 😄  I was afraid I got you more work when I started adding issue number to the entires in the change log.

**Comment by johlju** [comment]
Rebased.

**Pull request merged**
