### PR TITLE
Hashtable check - quick fix for LF end of line 

### PR DESCRIPTION
**Pull request by SSvilen**
#### Pull Request (PR) description
This PR extends the Measure-Hashtable function to cover LF end of line.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/355)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @SSvilen, I'm just going to check this against ComputerManagementDsc and NetworkingDsc and see if it resolves the issues. We will also need to copy this change over into https://github.com/dsccommunity/DscResource.AnalyzerRules.

**Comment by PlagueHO** [comment]
Hi @SSvilen - I'm scratching my head over this one. All hash tables are failing the validation check when run in AppVeyor - but are fine when run locally.

See: https://ci.appveyor.com/project/PowerShell/networkingdsc?fullLog=true#L1293
https://github.com/PowerShell/NetworkingDsc/blob/dev/DSCResources/MSFT_DefaultGatewayAddress/MSFT_DefaultGatewayAddress.psm1#L60

Is it possible that there is an issue with the CRLF? I'm actually wondering if the problem is in this line:
https://github.com/PowerShell/DscResource.Tests/blob/dev/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1110

The split is using `CR` rather than `CRLF` which might be a problem. I've not had time to dig into this further however.

**Review by SSvilen — COMMENTED** [review]
Hi @PlagueHO - as I mentioned [here](https://github.com/PowerShell/ComputerManagementDsc/pull/288) there are some funky stuff going on on the Appveyor build server. The problem is actually [here](https://github.com/PowerShell/DscResource.Tests/blob/509bc4c26e47e19affc2c9f05d182f0e726072b9/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113) - the check whether or not the hashtable starts correctly is failing. That's what this PR is for - I've added a [check](https://github.com/PowerShell/DscResource.Tests/blob/fc41c12a292fd5a691050ed19fd77d8c404042f8/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113), which should work against LF formatted files.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/355#-:-LtKDeiL5dihRvDzXEgc:b-61qtie)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1113 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/355#-LtKFYzoEkeEc6_kauxi:-LtKFYzoEkeEc6_kauxj:b8hton6) ([raw file](https://github.com/powershell/dscresource.tests/blob/fc41c12a292fd5a691050ed19fd77d8c404042f8/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113)):*
> ```
> $hashtableLines[0] -notmatch '@{')
> ```

A LF formatted files does not have \r at the end of the line.

**Comment by PlagueHO** [comment]
Hi @SSvilen - the comment I made above (see https://github.com/PowerShell/DscResource.Tests/pull/355#issuecomment-552167007) was actually when I tried using your new branch. It doesn't look like it resolves the problem :cry: E.g. I ran NetworkingDsc and ComputerManagementDsc against your branch with the updated RegEx (https://github.com/PowerShell/DscResource.Tests/blob/fc41c12a292fd5a691050ed19fd77d8c404042f8/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1113) and it still fails.

So I'm thinking there must be something else going on - which is why I'm wondering about the split.

The reason I query the split, is that on a file with CRLF line endings, that split will result in all of the strings in the array (except entry 0) beginning with a `\n` - which might mess up the RegEx matches on [1]. I'm just guessing though.

**Comment by SSvilen** [comment]
That is strange, because I tested it on the AppVeyor server directly.. I'll give it a try tonight again..

**Comment by SSvilen** [comment]
Hi @PlagueHO,

I actually tested NetworkingDsc against this fix and it passes all appveyor tets. 
What I changed is:
1. Fix a cople of hahtable styling violations
2. In appveyor.yaml I changed the source of DSCResources.Tests to my branch
[Here](https://github.com/PlagueHO/NetworkingDsc/compare/dev...SSvilen:dev) are the changes.

The tests results are [here](https://ci.appveyor.com/project/SSvilen/networkingdsc/build/tests).

Is there anything else I should test?

**Comment by PlagueHO** [comment]
Hi @SSvilen - I definitely am not sure what was going on. But you're right - it appears this has fixed the issue. Sorry about the confusion. Must have too many branches going at the moment!

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/355)* status: all files reviewed, 2 unresolved discussions (waiting on @SSvilen)

___
*[CHANGELOG.md, line 85 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/355#-LtT9T7K2gGBJgpN97Lo:-LtT9T7L0McirTzpWLH3:b-tyxmmm) ([raw file](https://github.com/powershell/dscresource.tests/blob/fc41c12a292fd5a691050ed19fd77d8c404042f8/CHANGELOG.md#L85)):*
> ```Markdown
> - Added Measure-Hashtable function to check if a hashtable is correctly formatted.
>   - Empty hashtables with white space are ignored.
>   - Fix issues with LF
> ```

Can you add a full stop at the end of this line?

**Review by PlagueHO — COMMENTED** [review]
@gaelcolas - I'm planning on merging this once it's through. We'll need to replicate this one over in https://github.com/dsccommunity/DscResource.AnalyzerRules, but it is pretty small so shouldn't be a problem.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/355#-:-LtT9cpW4ECW-cD1eYaT:b-fauh3b)* status: all files reviewed, 2 unresolved discussions (waiting on @SSvilen)

**Review by PlagueHO — APPROVED** [review]
:lgtm:

@gaelcolas - are you good with me merging this one?

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/355#-:-LtTdUKv4dp5bSFyfOfi:be52pct)* status: all files reviewed, 1 unresolved discussion

**Review by PlagueHO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/355)* status: all files reviewed, 1 unresolved discussion (waiting on @SSvilen)

**Pull request merged**
