### PR TITLE
Changes to PSSA custom rule 'ParameterAttribute'

### PR DESCRIPTION
**Pull request by johlju**
- Extended the parameter custom rule to also validate the Mandatory attribute.

Tested OK here:
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.825.0#L789

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/178)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO can you do an initial review of this one, since you did the first custom rule. I thought it was appropriate to extend the existing custom rule for this one. But I could make a separate rule if that is better.

**Comment by johlju** [comment]
Added to check for `Mandatory = $false`.

Tested OK here:
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.828.0#L789

**Comment by PlagueHO** [comment]
Great job @Johlju - I was meaning to add this myself, but I have a whole lot of work for my day job to catch up on! I will try to make time to sort out that Update-Help one though!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 115 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/178#-KqAeHBb3I_gKy10lIzc:-KqAeHBb3I_gKy10lIzd:bxjdyds) ([raw file](https://github.com/powershell/dscresource.tests/blob/8b02ab64fbe4b268475ce0fa7bc09c68593e0697/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L115)):*
> ```PowerShell
>                                 )
>                         }
>                         elseif ($parameterAst.Attributes.NamedArguments.Extent.Text -cne 'Mandatory = $true')
> ```

This won't match `Mandatory=$true` - which is technically valid (although I like the spaces, but I'm not sure it is a rule?). Maybe use a regex match?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/178#-:-KqAdwGojwzdPEyZIWGE:b-j2ii2k)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 115 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/178#-KqAeHBb3I_gKy10lIzc:-KqCCY3oFrrGvBW9FGWm:b-4m6908) ([raw file](https://github.com/powershell/dscresource.tests/blob/8b02ab64fbe4b268475ce0fa7bc09c68593e0697/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L115)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This won't match `Mandatory=$true` - which is technically valid (although I like the spaces, but I'm not sure it is a rule?). Maybe use a regex match?
</blockquote></details>

This was on purpose, because there is not a "Good"-example in the style guideline having it as `Mandatory=$true`.
I  would rather have it like this, unless we add a new "Good"-example to the style guideline? :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/178)*

**Comment by johlju** [comment]
@kwirkykat this is ready for review, after rebase, tests are passing.

@PlagueHO can you review the last file after rebase?

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/178#-:-Kr59_RcN-coNuPM4QOz:bnfp4nl)*

**Pull request merged**
