### PR TITLE
Adds PSSA Tests for Statement Capitalization

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

- Added PowerShell Script Analyzer rules to check the following
  statements are in lower case: `if`,`foreach`,`do`,`while`,`for`,
  `try`,`catch`,`enum`,`class` ([issue #224](https://github.com/PowerShell/DscResource.Tests/issues/224)).

#### This Pull Request (PR) fixes the following issues

- Partially addresses #244

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this?

I'm running this branch against:

- ActiveDirectoryCSDsc (no violations): 
- CertificateDsc (no violations): https://ci.appveyor.com/project/PlagueHO/certificatedsc?fullLog=true
- ComputerManagementDsc (no violations): https://ci.appveyor.com/project/PlagueHO/computermanagementdsc?fullLog=true#L658
- DFSDsc (no Violations): https://ci.appveyor.com/project/PlagueHO/dfsdsc
- FileContentDsc
- FSRMDsc
- iSCSIDsc
- NetworkingDsc (no violations): https://ci.appveyor.com/project/PlagueHO/networkingdsc
- SqlServerDsc (picked up one issue): https://ci.appveyor.com/project/PlagueHO/sqlserverdsc/build/job/fba8b0a7g9lds6cj?fullLog=true#L1773
- StorageDsc (no violations): https://ci.appveyor.com/project/PlagueHO/storagedsc
- WmiNamespaceSecurityDsc
- WSManDsc 
- xActiveDirectory (no violations): https://ci.appveyor.com/project/PlagueHO/xactivedirectory?fullLog=true
- xBitlocker  (no violation): https://ci.appveyor.com/project/PlagueHO/xbitlocker#L329
- xExchange (one violations - will submit PR): https://ci.appveyor.com/project/PlagueHO/xexchange/builds/25959684?fullLog=true#L1203
- xPSDesiredStateConfiguration (no violations): https://ci.appveyor.com/project/PlagueHO/xpsdesiredstateconfiguration/build/job/q1kdj5wa4wc885u1

Others are being tested at the moment - but suspect a few of them will show issues.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333)* status: all files reviewed, 8 unresolved discussions (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 313 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5Ok4F1Z5waPZwLWvW:-Lj5Ok4F1Z5waPZwLWvX:b-96nswq) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L313)):*
> ```
> ($localizedData.StatementsContainsUpperCaseLetter -f 'if')
> ```

No need for parentheses around this . Throughout.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 314 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5QO5d-PZikX5UFNh4:-Lj5QO5d-PZikX5UFNh5:be7sqw5) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L314)):*
> ```
> $script:diagnosticRecord -as $diagnosticRecordType
> ```

This is getting duplicated a lot now, I was looking at it to see if we could add it once, but not sure if any attempt is gonna save and lines or characters. Let's leave it for some other time.  :slightly_smiling_face: 
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 257 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5R52f1_rNo22s4g5h:-Lj5R52f1_rNo22s4g5i:b-sr48ss) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L257)):*
> ```
> .EXAMPLE
> ```

I think example normally goes at the end of the comment-based help? Before .NOTES :thinking: 
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 267 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5RFeN0ibKOFqArJs8:-Lj5RFeN0ibKOFqArJs9:b-eiwlc4) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L267)):*
> ```
>    .NOTES
> ```

This looks indented wrong.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 282 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5RjHv8Dp72KWFLEO3:-Lj5RjHv8Dp72KWFLEO4:bgz6bzl) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L282)):*
> ```
> $statementBlockRows = Get-StatementBlockAsRows @PSBoundParameters
> ```

Is this returning one or more rows? How does that work with the regex below? :thinking: 
Or is the naming of the variable wrong?
___
*[DscResource.AnalyzerRules/en-US/DscResource.AnalyzerRules.psd1, line 11 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5SHBkA8u8xyzJWALI:-Lj5SHBkA8u8xyzJWALJ:b-dbw792) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/en-US/DscResource.AnalyzerRules.psd1#L11)):*
> ```
> {0}-Statement
> ```

Maybe `statement`(lower-case 's'), or `The statements of '{0}' should...`
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1065 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5T3z6CPndxD27uRNT:-Lj5T3z75xV5IQIsRUMa:b9b0zvb) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1065)):*
> ```
> ($localizedData.StatementsContainsUpperCaseLetter -f 'If')
> ```

Should not need parentheses around this. 
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1208 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5TDIe8p7Bp1-aXM0R:-Lj5TDIe8p7Bp1-aXM0S:bc5ekov) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1208)):*
> ```
> It 'Should not write an error record' {
> ```

Help me out here, I'm not remembering, why should this not write an error record. Does it not? Is the description wrong on all these? :thinking: 
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1220 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5TAIM2p0K-H4tWT0e:-Lj5TAINEZ0GjytA3tj6:b-j16q78) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1220)):*
> ```
> ($localizedData.StatementsContainsUpperCaseLetter -f 'if')
> ```

Should not need parentheses around this.  Throughout.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333)* status: all files reviewed, 9 unresolved discussions (waiting on @PlagueHO)

___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3236 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5U72V1-KjOf_c4obs:-Lj5U72V1-KjOf_c4obt:bkjxni7) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3236)):*
> ```
> [Void]
> ```

Should be `[void]` lowercase 'v'?

**Review by PlagueHO — COMMENTED** [review]
@Johlju - Should be all fixed.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333#-:-Lj5r_iK8PcBrSV-OxaR:b-3mjmnn)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 313 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5Ok4F1Z5waPZwLWvW:-Lj5pDNe6iVjcAu5nGwS:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L313)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ($localizedData.StatementsContainsUpperCaseLetter -f 'if')
> ```

No need for parentheses around this . Throughout.
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 314 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5QO5d-PZikX5UFNh4:-Lj5pFe0AG1_RTxiTRIG:b-o6l4id) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L314)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $script:diagnosticRecord -as $diagnosticRecordType
> ```

This is getting duplicated a lot now, I was looking at it to see if we could add it once, but not sure if any attempt is gonna save and lines or characters. Let's leave it for some other time.  :slightly_smiling_face: 
</blockquote></details>

There does look like there could be some refactoring we could do. But happy to leave it to later.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 257 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5R52f1_rNo22s4g5h:-Lj5pLn732xW0XN1Yn93:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L257)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> .EXAMPLE
> ```

I think example normally goes at the end of the comment-based help? Before .NOTES :thinking: 
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 267 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5RFeN0ibKOFqArJs8:-Lj5pMN8E5PS3B76MkQE:b-s6e6j9) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L267)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>    .NOTES
> ```

This looks indented wrong.
</blockquote></details>

Fixed and throughout.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 282 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5RjHv8Dp72KWFLEO3:-Lj5pVpF7H-q9G8-lJBS:b-bdqlb4) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L282)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $statementBlockRows = Get-StatementBlockAsRows @PSBoundParameters
> ```

Is this returning one or more rows? How does that work with the regex below? :thinking: 
Or is the naming of the variable wrong?
</blockquote></details>

I've fixed this - the conversion to StatementBlockRows wasn't required - I added it when I was debugging but forgot to remove it.
___
*[DscResource.AnalyzerRules/en-US/DscResource.AnalyzerRules.psd1, line 11 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5SHBkA8u8xyzJWALI:-Lj5qav73QPU7qY07b9c:b-g6vzsk) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/DscResource.AnalyzerRules/en-US/DscResource.AnalyzerRules.psd1#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> {0}-Statement
> ```

Maybe `statement`(lower-case 's'), or `The statements of '{0}' should...`
</blockquote></details>

I've reworded it in a different way because the "The statements of 'if' should..." read in an odd way. Now it should be "'If' statements should not..."
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1065 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5T3z6CPndxD27uRNT:-Lj5rOfI3UnHx9TAWZkI:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1065)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ($localizedData.StatementsContainsUpperCaseLetter -f 'If')
> ```

Should not need parentheses around this. 
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1208 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5TDIe8p7Bp1-aXM0R:-Lj5rRLN9OUxvR5bCJfN:bwrf49q) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1208)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> It 'Should not write an error record' {
> ```

Help me out here, I'm not remembering, why should this not write an error record. Does it not? Is the description wrong on all these? :thinking: 
</blockquote></details>

Oops. Copy/paste problem. Fixed.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1220 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5TAIM2p0K-H4tWT0e:-Lj5rWcO8mnymFbkq8wN:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1220)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ($localizedData.StatementsContainsUpperCaseLetter -f 'if')
> ```

Should not need parentheses around this.  Throughout.
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3236 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5U72V1-KjOf_c4obs:-Lj5rYtu-AQhLhIOULTJ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3236)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [Void]
> ```

Should be `[void]` lowercase 'v'?
</blockquote></details>

Done.

**Review by johlju — COMMENTED** [review]
:lgtm:

Two comments looks like wasn't fixed, but does not need to hold up the PR. You may fix them if you like. :)

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333#-:-Lj6Fqu69o3koVv_J8BX:b7ktzfq)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1065 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5T3z6CPndxD27uRNT:-Lj6Fly9DcFPXQ0wgJh-:b-sq2aiv) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1065)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seeing this. :slightly_smiling_face:  But leaving it as satisfied, fix it if you like or merge if you like. :slightly_smiling_face: 
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1220 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5TAIM2p0K-H4tWT0e:-Lj6F_ky1wqljlr1BGeA:b1d4p9t) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1220)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seeing this. :slightly_smiling_face:  But leaving it as satisfied, fix it if you like or merge if you like. :slightly_smiling_face:

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1065 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5T3z6CPndxD27uRNT:-Lj895dxCvRNNK5cLBZL:b-v7m6ry) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1065)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Still seeing this. :slightly_smiling_face:  But leaving it as satisfied, fix it if you like or merge if you like. :slightly_smiling_face: 
</blockquote></details>

I changed the ones inside the function but not these ones because it breaks (e.g. the -f is seen as a parameter of Should).
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1220 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5TAIM2p0K-H4tWT0e:-Lj89EJq8gN0ck9N3ruQ:b-v7m6ry) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1220)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Still seeing this. :slightly_smiling_face:  But leaving it as satisfied, fix it if you like or merge if you like. :slightly_smiling_face: 
</blockquote></details>

I changed the ones inside the function but not these ones because it breaks (e.g. the -f is seen as a parameter of Should).

**Review by johlju — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333#-:-LjAH0Eu402AIF3FonMA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 1065 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/333#-Lj5T3z6CPndxD27uRNT:-LjAGjIX-shkU3p1ostt:b8219is) ([raw file](https://github.com/powershell/dscresource.tests/blob/a24cefba8d9c9be3bfadde897717900d2a5eb60c/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L1065)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I changed the ones inside the function but not these ones because it breaks (e.g. the -f is seen as a parameter of Should).
</blockquote></details>

Yeah right, my bad. I did know this. :slightly_smiling_face:

**Comment by johlju** [comment]
@gaelcolas Can you label this on hold - waiting for @PlagueHO to go through all repos to make sure none will be affected by this change.

**Comment by PlagueHO** [comment]
Yep- sorry it's taking so long. I'm planning on writing a short script to automate this so I can rerun it when I add further checks (which we will no doubt).

**Comment by PlagueHO** [comment]
The following repositories will need to be tested against these new checks:
image

**Comment by PlagueHO** [comment]
Can you review the final file on this one @johlju? I'll merge once [this PR](https://github.com/PowerShell/xExchange/pull/416) for xExchange is through.

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/333#-:-LjjAbpV9jQXw5wR9PFP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
