### PR TITLE
Added support for example to have mandatory parameters

### LINKED ISSUE #224: Common Test Examples: Error message when missing the configuration named 'Example' has wrong text
This error message

https://github.com/PowerShell/DscResource.Tests/blob/f1f2623aeec122c02635447b1d4e9413e2d7d923/Meta.Tests.ps1#L675

Should maybe read

```
throw "The example '$exampleDescriptiveName' does not contain a configuration named 'Example'." 
```

### PR DESCRIPTION
**Pull request by johlju**
- Changes to example common tests
  - Added support for example to have mandatory parameters.
  - Updated to support all credential parameters regardless of name.
  - Added support to use the same name both for filename and configuration name.
    Supporting filenames starting with or without a numeric value and a dash,
    e.g '99-MyExample.ps1', or 'MyExample.ps'. Any filename starting with a
    numeric value followed by a dash will be removed. This is to support
    configurations to be able to compile in Azure Automation, but still support
    auto-documentation.

This is part of resolving issue #234.
Fixes #224  

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/237)

### CODE REVIEW

**Comment by johlju** [comment]
Tested OK here: 
SharePointDsc: https://ci.appveyor.com/project/johlju/sharepointdsc/build/2.4.0.9?fullLog=true#L11443
SqlServerDsc: https://ci.appveyor.com/project/johlju/sqlserverdsc/build/9.0.506.0?fullLog=true#L1431

**Comment by johlju** [comment]
Added a bit more functionality to this than I first intended. This will resolve all issues with the examples validation tests that is needed for preparation for issue #234.

Tested OK here, some examples fails because they have issues that I haven't resolved yet, but those that are green have the same configuration name as the filename; https://ci.appveyor.com/project/johlju/xpsdesiredstateconfiguration/build/6.0.58.0?fullLog=true#L1823. 

@PlagueHO Could you please review this one? Would be awesome if I could get this merged. I need it for next step. 😃

**Comment by PlagueHO** [comment]
Definitely.  Will get to it after work tonight.

**Comment by johlju** [comment]
@PlagueHO Thanks! 👍

**Comment by PlagueHO** [comment]
Good stuff there @johlju - just some really minor bits!

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 5 unresolved discussions (waiting on @johlju)

---

*[Meta.Tests.ps1, line 658 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRJh8mBVi7Yb6g5UMu:-LFRJh8mBVi7Yb6g5UMv:b-fqa06a) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L658)):*
> ```PowerShell
>                             #>
>                             $commandName = @()
>                             $commandName += 'Example'
> ```

BTW, why not:
```powershell
$commandName = @('Example')
```

Instead of the two previous commands?

---

*[Meta.Tests.ps1, line 677 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRKIdWCbBrr7bd3K_D:-LFRKIdWCbBrr7bd3K_E:bq4916g) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L677)):*
> ```PowerShell
> 
>                                     # Remove any common parameters that are available.
>                                     $commandParameters = $exampleCommand.Parameters.Keys | Where-Object -FilterScript {
> ```

Could these two Where-Object cmds be combined into one like:
```powershell
Where-Object -FilterScript {
    ($_ -notin [System.Management.Automation.PSCmdlet]::CommonParameters) -and `
    ($_ -notin [System.Management.Automation.PSCmdlet]::OptionalCommonParameters)
}
```

It is getting a bit late though so my logic might be off!

---

*[Meta.Tests.ps1, line 701 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRKjrkE4vOeKDvkIU0:-LFRKjrkE4vOeKDvkIU1:b-tq7kmg) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L701)):*
> ```PowerShell
>                                             <#
>                                                 Check for mandatory parameters.
>                                                 Assume the parameters are all on the 'all' parameter set.
> ```

all on the -> all in the

---

*[Meta.Tests.ps1, line 707 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRKsrm6hwFQQXBeLnn:-LFRKsrm6hwFQQXBeLno:b-oiqlbn) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L707)):*
> ```PowerShell
>                                             {
>                                                 <#
>                                                     Convert '1' to the type that the parameter expect.
> ```

expect -> expects

---

*[TestHelper.psm1, line 1725 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRLYwLAVyMI4LrA5Uv:-LFRLYwLAVyMI4LrA5Uw:b-x2cltw) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/TestHelper.psm1#L1725)):*
> ```PowerShell
>     <#
>         Resource modules using auto-documentation uses a numeric value followed
>         by a dash ('-') to be able to control the order of the exampled in
> ```

exampled -> example

---

*[Tests/Unit/TestHelper.Tests.ps1, line 1377 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRLBjk6Ijearq9yHkf:-LFRLBjk6Ijearq9yHkg:b-yqd45f) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Tests/Unit/TestHelper.Tests.ps1#L1377)):*
> ```PowerShell
> 
>     Describe 'TestHelper\Get-PublishFileName' {
>         Context 'When filename start with a numeric value followed by a slash (-)' {
> ```

start -> starts

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/237#-:-LFRLgFi99EfIU_FyGMe:b-4kii2w)*

**Comment by johlju** [comment]
Review status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @PlagueHO)

---

*[Meta.Tests.ps1, line 658 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRJh8mBVi7Yb6g5UMu:-LFRORK89OGpVN1Eqfzg:bf18l2t) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L658)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

BTW, why not:
```powershell
$commandName = @('Example')
```

Instead of the two previous commands?
</blockquote></details>

Done. Haha, one should not code when it's late! :wink: 

---

*[Meta.Tests.ps1, line 677 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRKIdWCbBrr7bd3K_D:-LFROacOA2Z5Rc2ht5ot:bz205vh) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L677)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could these two Where-Object cmds be combined into one like:
```powershell
Where-Object -FilterScript {
    ($_ -notin [System.Management.Automation.PSCmdlet]::CommonParameters) -and `
    ($_ -notin [System.Management.Automation.PSCmdlet]::OptionalCommonParameters)
}
```

It is getting a bit late though so my logic might be off!
</blockquote></details>

Done. Using two Where-Object looked so wrong when I did it yesterday night :laughing: 

---

*[Meta.Tests.ps1, line 701 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRKjrkE4vOeKDvkIU0:-LFROq-m0--CG22Pgi7G:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L701)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

all on the -> all in the
</blockquote></details>

Done.

---

*[Meta.Tests.ps1, line 707 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRKsrm6hwFQQXBeLnn:-LFROqD3Cnkjw1d9YAfJ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Meta.Tests.ps1#L707)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

expect -> expects
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1725 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRLYwLAVyMI4LrA5Uv:-LFROqd8DFcS_HabKjqG:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/TestHelper.psm1#L1725)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

exampled -> example
</blockquote></details>

Done.

---

*[Tests/Unit/TestHelper.Tests.ps1, line 1377 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/237#-LFRLBjk6Ijearq9yHkf:-LFROr4z-EauIYhXTPts:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/68a4cdcc57cd84d93f3990f8c5f66d26085d2438/Tests/Unit/TestHelper.Tests.ps1#L1377)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

start -> starts
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/237)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/237#-:-LFRTgBW4jlFxn7H6KLR:bnfp4nl)*

**Comment by johlju** [comment]
@PlagueHO Thank you!! 🙇

**Pull request merged**
