### PR TITLE
Improve Autodocumentation Code to Indicate when a parameter is an Array - Fixes #135

### LINKED ISSUE #135: Improve Autodocumentation Code to Indicate when a parameter is an Array
The Autodocumentation code doesn't produce a parameter list that indicates when parameters can be arrays:
image

This should be easy enough to resolve. I'll take a look and submit a PR.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR causes a [] to be added after the data type for any array type properties in the autodocumentation code.

Identified in https://github.com/PowerShell/xNetworking/issues/198

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/136)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/136#-:-KgFIwa7QP8KfmYpaPak:bnfp4nl)*

**Comment by PlagueHO** [comment]
@kwirkykat - any chance of a review and a merge on this one? :grin:

**Comment by PlagueHO** [comment]
Hi @johlju - I don't suppose you could resolve these ones when you get a chance. When I fixed the merge conflicts it required a review. Thank you!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/136#-:-KjJbRyI2lv3VeUt7D-S:bnfp4nl)*

**Comment by johlju** [comment]
@mbreakey3 or @kwirkykat can you look this over and merge it?

**Pull request merged**
