### PR TITLE
Change Wiki Generation to create valid Markdown Files - Fixes #130

### LINKED ISSUE #130: DocumentationHelper produces Wiki Markdown that violates Markdown Rules
The _Parameters_ and _Examples_ headers are produced as Emphasis rather than Headers which violates MD036.

MD041 is also violated because a H1 is not the first line of the file.

Will submit a PR to fix this.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR contains the following changes:
* Fixed Wiki Generation to create Markdown that does not violate markdown rules
* Removed violation of markdown rules from Readme.md

I also fixed up all the Markdown violations in the Readme.md

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/131)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@BrianFarnhill , @johlju - do you guys have any thoughts on this one? This will allow the MD that is produced by the auto doc gen code to make MD that doesn't violate the MD rules.

**Comment by PlagueHO** [comment]
I've added another fix to this. See this issue in xNetworking:
https://github.com/PowerShell/xNetworking/issues/194

Essentially -replace was used (which matches on Regex) which would cause the replace to not actually work in some cases.

**Comment by BrianFarnhill** [comment]
🥇 Looks good to me

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/131#-:-KgFNBiaWLfoeqI5rNxL:bnfp4nl)*

**Comment by PlagueHO** [comment]
@kwirkykat - any chance of a review and a merge on this one? :grin:

**Comment by PlagueHO** [comment]
@mbreakey3 - any chance you could take a look at this one for me? It is causing corrupt display of some MD files in xNetworking (and potentially any others using auto documentation generation). Thank you 🥇

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/131#-:-KiW2e0yg1KuTiHZ129o:bnfp4nl)*

**Pull request merged**
