### PR TITLE
Added the ability to skip common test for debug purpose

### LINKED ISSUE #219: Temporary override common test for debugging purposes
I spend a lot of time waiting for AppVeyor to run tests (in my fork) when debugging errors in integration tests for example. The time spent adds up when I need to wait for the common test to run until my test that I'm debugging is run. 

There are no easy way of overriding it today, so I wondering if we could add a environment variable to the appveyor.yml that is evaluated in the Meta.Tests.ps1, and if found, skips all tests. 

```yml
environment:
  OverrideCommonTests: True
``` 

This should _only_ be used for debugging purposes and not for any modules wanting to be HQRM.

Would that work, or are there a better option?

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Changes to Meta.Tests.ps1
  - Added the ability to temporary skip common test for
    debugging purposes (issue #219).

#### This Pull Request (PR) fixes the following issues
- Fixes #219 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/299)

### CODE REVIEW

**Comment by johlju** [comment]
Tested OK here:
SqlServerDsc (skip common test): https://ci.appveyor.com/project/johlju/sqlserverdsc#L148
This PR (not skipping): https://ci.appveyor.com/project/PowerShell/dscresource-tests/build/0.2.396.0

**Comment by johlju** [comment]
@PlagueHO no hurry with this one, but when you have a few minutes over, could you look at this PR? 

I'm gonna start looking at adding more integration test to SqlServerDsc, so would be great to have this functionality when I need to debug those tests (quicker debug testing in AppVeyor). 🙂

**Comment by PlagueHO** [comment]
Doh! Will get onto this tonight!

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/299)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[README.md, line 304 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjg1E5YCI2VKsToIr:-LOMjg1E5YCI2VKsToIs:b-nofybg) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L304)):*
> ```Markdown
> test runs.
> 
> To temporarily skip the common tests, the environment variable `SkipAllCommonTests`
> ```

Is it worth mentioning that this should not be used in any PR's that are being merged to master? Or is this just self-evident?
___
*[README.md, line 316 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjubG93Pd4zH_uKyr:-LOMjubG93Pd4zH_uKys:b-t7oo5v) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L316)):*
> ```Markdown
> ```
> 
> Or as the first PowerShell line to run when AppVeyor is starting testing.
> ```

If adjusting the AppVeyor.yml file then we should point out that care needs to be taken to ensure this isn't committed in a PR to master.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/299)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @PlagueHO and @johlju)

___
*[README.md, line 304 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjg1E5YCI2VKsToIr:-LOOeC9UCqgcSfLogmZx:b-181j0i) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L304)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it worth mentioning that this should not be used in any PR's that are being merged to master? Or is this just self-evident?
</blockquote></details>

Done. Added a notice about this. Is it good enough?
___
*[README.md, line 316 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjubG93Pd4zH_uKyr:-LOOeHeF647-xWhSS9ye:b-lk8s4d) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L316)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If adjusting the AppVeyor.yml file then we should point out that care needs to be taken to ensure this isn't committed in a PR to master.
</blockquote></details>

I could add a meta test that fail the test run if the environment variable is set and the environment variable `APPVEYOR_PULL_REQUEST_NUMBER` is set to a number. 
Theoretically it should fail a test on PR runs, but not on branch runs (pushing to owns fork).
What do you think? Worth try it out?

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/299)* status: all files reviewed, 2 unresolved discussions (waiting on @PlagueHO and @johlju)

___
*[README.md, line 304 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjg1E5YCI2VKsToIr:-LORSafD6qUy-i4Zq3DZ:bzh9kyl) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L304)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Added a notice about this. Is it good enough?
</blockquote></details>

Yes, I think so. We will need to be careful and just see if this ends up being a problem though and add a test if it does.
___
*[README.md, line 316 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjubG93Pd4zH_uKyr:-LORSkIC-6HrsmCeM1rK:b-k1q3vt) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L316)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I could add a meta test that fail the test run if the environment variable is set and the environment variable `APPVEYOR_PULL_REQUEST_NUMBER` is set to a number. 
Theoretically it should fail a test on PR runs, but not on branch runs (pushing to owns fork).
What do you think? Worth try it out?
</blockquote></details>

I think let's see how things go as is and if it one slips through then add a test. I expect this setting won't get used a huge amount so it is low risk.
___
*[README.md, line 310 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LORSXDt2foZTLSncK-8:-LORSXDt2foZTLSncK-9:b-8ef6uk) ([raw file](https://github.com/powershell/dscresource.tests/blob/81c7e8ebc71bf8fbbf63ccf6f9dce1ae566e50b9/README.md#L310)):*
> ```Markdown
> 
> >**Note:** This environment variable should not be merged, or
> >a commit pushed, into the branches `dev` or `master`. This environment
> ```

No need for this comma.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/299)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[README.md, line 304 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LOMjg1E5YCI2VKsToIr:-LOTX6qr-L7D0hS5HvD0:bepqvej) ([raw file](https://github.com/powershell/dscresource.tests/blob/412585f4acfca4d0ce96984eabdc33215dddc2d9/README.md#L304)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Yes, I think so. We will need to be careful and just see if this ends up being a problem though and add a test if it does.
</blockquote></details>

Done. Agree.
___
*[README.md, line 310 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/299#-LORSXDt2foZTLSncK-8:-LOTXA2c08PKegYaS8Lm:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/81c7e8ebc71bf8fbbf63ccf6f9dce1ae566e50b9/README.md#L310)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

No need for this comma.
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/299#-:-LOWfVHy91xfeEnPYvlP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@PlagueHO Thanks for this! Will help a lot!

**Pull request merged**
