### PR TITLE
Outputs a warning when a repository does not have a Tests folder

### LINKED ISSUE #296: Fails with an error if there are no tests in a repository
When a repository not yet contain tests (or a Tests folder), the test framework fails with an error. 
I suggest we add a check if there are tests, and outputs a warning if there are no tests.

```
Get-ChildItem : Cannot find path 'C:\projects\xchrome\Tests' because it does not exist.
At C:\projects\xchrome\DscResource.Tests\AppVeyor.psm1:216 char:27
+ ... tionFiles = Get-ChildItem -Path $testsPath -Include '*.config.ps1' -R ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\xchrome\Tests:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```
https://ci.appveyor.com/project/PowerShell/xchrome/build/1.1.58.0

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Now outputs a warning when a repository does not have a Tests
  folder (issue #296).

#### This Pull Request (PR) fixes the following issues
- Fixes #296 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/298)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Hi @johlju - so sorry I missed this! Trying to spend my holidays catching up on all these PR's and other bits and pieces. Just some minor tweaks (I fixed the conflict for you).

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/298#-:-LU9eaps2dRg_AIkA0nj:by2wav)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[AppVeyor.psm1, line 219 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/298#-LU9eGTo-kSsutz-80Sr:-LU9eGTp7Zt16t9Et3m7:b30ocp2) ([raw file](https://github.com/powershell/dscresource.tests/blob/220588a488e4ea6a4f98923f9db398b19afd5039/AppVeyor.psm1#L219)):*
> ```PowerShell
>     {
>         $configurationFiles = Get-ChildItem -Path $testsPath -Include '*.config.ps1' -Recurse
>         foreach ($configurationFile in $configurationFiles)
> ```

Can you add a blank line before this one?
___
*[Tests/Unit/AppVeyor.Tests.ps1, line 153 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/298#-LU9eQsB3Wt3RjGKgOvf:-LU9eQsB3Wt3RjGKgOvg:b-u9vpya) ([raw file](https://github.com/powershell/dscresource.tests/blob/220588a488e4ea6a4f98923f9db398b19afd5039/Tests/Unit/AppVeyor.Tests.ps1#L153)):*
> ```PowerShell
>         }
> 
>         Context 'When there are no Tests folder' {
> ```

When there are no -> When there _is_ no

**Review by johlju — COMMENTED** [review]
Same here, trying to catch up on PR's and responding to issues. :slightly_smiling_face: 

Happy new year my friend! :smile: 

I had to rebase so that switched the location of the change log entry.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/298#-:-LV7fD4f3xBAcPlbmnKy:b-kdj9ky)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[AppVeyor.psm1, line 219 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/298#-LU9eGTo-kSsutz-80Sr:-LV7fUiD60ZFE9QrwDCC:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/220588a488e4ea6a4f98923f9db398b19afd5039/AppVeyor.psm1#L219)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this one?
</blockquote></details>

Done.
___
*[Tests/Unit/AppVeyor.Tests.ps1, line 153 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/298#-LU9eQsB3Wt3RjGKgOvf:-LV7faYY1OibGsT1mPoZ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/220588a488e4ea6a4f98923f9db398b19afd5039/Tests/Unit/AppVeyor.Tests.ps1#L153)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

When there are no -> When there _is_ no 
</blockquote></details>

Done.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Hi @Johlju - just one tiny nitpick then merge time.

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/298#-:-LVPtZeI7XXRzbApjUag:b-wilr4p)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[CHANGELOG.md, line 24 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/298#-LVPtOzJ4gVa9fMyLdOZ:-LVPtOzJ4gVa9fMyLdO_:b-esrnzq) ([raw file](https://github.com/powershell/dscresource.tests/blob/e6cd1fe0f1dd44fcffdc643f4e1f81adb10dae03/CHANGELOG.md#L24)):*
> ```Markdown
> - Changes to TestHelper.psm1
>   - Updated `Install-NuGetExe` to have a new parameter `RequiredVersion`.
>     Also the `Uri` parameter no longer takes the entire download URL but
> ```

Also the -> Also, the

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/298)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 24 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/298#-LVPtOzJ4gVa9fMyLdOZ:-LVS8sydE0g-tZoDvOQj:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e6cd1fe0f1dd44fcffdc643f4e1f81adb10dae03/CHANGELOG.md#L24)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Also the -> Also, the
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/298#-:-LVUqBuF2Oradxvn-owZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
