### PR TITLE
Added CodeCoverage for Class based resources - Fixes #173

### LINKED ISSUE #173: Pester code coverage does not account for the DSCClassResources folder
Currently code coverage only scan these folders for code.

```
"$env:APPVEYOR_BUILD_FOLDER\*.psm1"
"$env:APPVEYOR_BUILD_FOLDER\DSCResources\*.psm1"
"$env:APPVEYOR_BUILD_FOLDER\DSCResources\**\*.psm1"
```

### PR DESCRIPTION
**Pull request by limiteddenial**
* Added ```Invoke-AppveyorTestScriptTask``` cmdlet functionality for CodeCoverage for Class based resources ([issue #173](https://github.com/PowerShell/DscResource.Tests/issues/173))
* Added tests for module ```AppVoyer.psm1``` and tested ```Invoke-AppveyorTestScriptTask``` to verify it adds all the folders needed for CodeCoverage when running ```Invoke-Pester```

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/212)

### CODE REVIEW

**Comment by johlju** [comment]
Great work on this one! Glad to see this issue being fixed! :smile:  Just a few minor style comments.

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[AppVeyor.psm1, line 256 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K0B3R8ZyvKyDN2YUq:-L7K0B3R8ZyvKyDN2YUr:b7f0vz7) ([raw file](https://github.com/powershell/dscresource.tests/blob/651c66b1180a7bd8b05520b0f0b0820f2ed23f38/AppVeyor.psm1#L256)):*
> ```PowerShell
>                 # Define the folders to check, if found add the path for codecoverage
>                 $possibleModulePaths = @(
>                     "DSCResources",
> ```

Please use single quote on this string, and on the string below. 

---

*[AppVeyor.psm1, line 262 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K2SYclSnYj35s4Dqn:-L7K2SYclSnYj35s4Dqo:byvzg9f) ([raw file](https://github.com/powershell/dscresource.tests/blob/651c66b1180a7bd8b05520b0f0b0820f2ed23f38/AppVeyor.psm1#L262)):*
> ```PowerShell
>                 foreach ($possibleModulePath in $possibleModulePaths)
>                 {
>                     if(Test-Path -Path $MainModulePath\$possibleModulePath)
> ```

Please add a space between if and parenthesis (`if (`).

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 15 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K6LdAEWIbF88bxggI:-L7K6LdAEWIbF88bxggJ:b-pb5sbu) ([raw file](https://github.com/powershell/dscresource.tests/blob/a3dc69040a2c4ee463b74d362eb329019ff04163/Tests/Unit/AppVeyor.Tests.ps1#L15)):*
> ```PowerShell
>         Function Resolve-CoverageInfo { }
>         Function Invoke-UploadCoveCoveIoReport { }
>         Describe 'Invoke-AppveyorTestScriptTask' { 
> ```

Can we add the module to the description, i.e `'AppVeyor\Invoke-AppveyorTestScriptTask'`.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 15 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K7wPK7euWIDbxmr7N:-L7K7wPK7euWIDbxmr7O:bh69ouf) ([raw file](https://github.com/powershell/dscresource.tests/blob/a3dc69040a2c4ee463b74d362eb329019ff04163/Tests/Unit/AppVeyor.Tests.ps1#L15)):*
> ```PowerShell
>         Function Resolve-CoverageInfo { }
>         Function Invoke-UploadCoveCoveIoReport { }
>         Describe 'Invoke-AppveyorTestScriptTask' { 
> ```

Non-blocking personal opinion. Would it be possible to add a blank row before this row and in the code below where appropriate to create a natural separation of code blocks. It would be easier to review. 

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 16 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K78sP2_tMKpsjk5tS:-L7K78sP2_tMKpsjk5tT:b-cxiynn) ([raw file](https://github.com/powershell/dscresource.tests/blob/a3dc69040a2c4ee463b74d362eb329019ff04163/Tests/Unit/AppVeyor.Tests.ps1#L16)):*
> ```PowerShell
>         Function Invoke-UploadCoveCoveIoReport { }
>         Describe 'Invoke-AppveyorTestScriptTask' { 
>             context 'CodeCoverage' {
> ```

This context block seems unnecessary. If this should be kept, then please change the description to what scenario is being tested 'When...' . Also, change to `Context` - upper 'C'.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 22 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K7_1U4iESFidOIRg-:-L7K7_1U4iESFidOIRg0:bbr4ajg) ([raw file](https://github.com/powershell/dscresource.tests/blob/a3dc69040a2c4ee463b74d362eb329019ff04163/Tests/Unit/AppVeyor.Tests.ps1#L22)):*
> -MockWith { }

This is not necessary when no code is being mocked. The `-MockWith { }` can be removed. Throughout. 

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 3 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K5GMFIQQNCanT-8_Y:-L7K5GMFIQQNCanT-8_Z:byvzg9f) ([raw file](https://github.com/powershell/dscresource.tests/blob/651c66b1180a7bd8b05520b0f0b0820f2ed23f38/Tests/Unit/AppVeyor.Tests.ps1#L3)):*
> ```PowerShell
> $script:ModuleName = 'AppVeyor'
> $script:moduleRootPath = Split-Path -Path (Split-Path -Path $PSScriptRoot -Parent) -Parent
> if($null -eq $env:APPVEYOR_BUILD_FOLDER)
> ```

Please add a space between if and parenthesis (`if (`).

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 7 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-L7K3Xl2_Dr2e91huHh_:-L7K3Xl2_Dr2e91huHha:b-20gw3v) ([raw file](https://github.com/powershell/dscresource.tests/blob/651c66b1180a7bd8b05520b0f0b0820f2ed23f38/Tests/Unit/AppVeyor.Tests.ps1#L7)):*
> ```PowerShell
>     $env:APPVEYOR_BUILD_FOLDER = 'C:\projects\dscresource-tests'
> }
> Describe "$($script:ModuleName) Unit Tests" {
> ```

This is non-blocking since there is not guideline for this, just my personal opinion, and an attempt for the tests to be similar. :smile: 

I suggest we don't do the Describe-blocks recursive, I think it is mean that the Context blocks can be made recursive. It do work this way though, but I have seen it giving strange output in the Pester result object. Could we instead start with InModuleScope as proposed in these tests (currently in PR).
https://github.com/johlju/DscResource.Tests/blob/da656f5b41d00ac402b0d5f643d4feba7b2d5931/Tests/Unit/TestHelper.Tests.ps1

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/212#-:-L7K8guv4VtLNwxuL72S:brnrq1t)*

**Comment by johlju** [comment]
@limiteddenial to be able to merge this change you need to have sign the CLA.

**Comment by johlju** [comment]
Just a few tiny review comments left, then this looks good for me. 

@limiteddenial When you are done with the review comments, please go into Reviewable (the purple button in the PR description) and write 'Done' on all the comments, then press the green Publish button and the comments will be sent back to GitHub. We know then that you are finished with the change, and also make it possible for me to acknowledge (resolve) the review comment. :smile: 
The previous review comments I resolved by withdrawing the comment when I saw that the change was made, so all good with them. :smile: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 18 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nvjNE8WewhSltQc0o:-L7nvjNE8WewhSltQc0p:b-9c7bse) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L18)):*
> direcotries

minor typo:" directories"

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 27 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nw6FeB99LWJzhr3MX:-L7nw6FeB99LWJzhr3MY:blvvo6n) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L27)):*
> $False

`$false` (lower 'f')

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 28 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nwCfUYvO1_QUjovj3:-L7nwCfUYvO1_QUjovj4:b7uf717) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L28)):*
> "file.Tests.ps1"

Can we use single quotes here?

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 32 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nwLwZszAR_8Sn_V4G:-L7nwLwZszAR_8Sn_V4H:b8ndkt7) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L32)):*
> ```PowerShell
>                 Mock -CommandName Resolve-CoverageInfo
>                 Mock -CommandName Invoke-Pester -MockWith { return $pesterReturnedValues }
>                 Mock -CommandName Invoke-Pester -MockWith { return $pesterReturnedValues } -ParameterFilter {$CodeCoverage -contains "$env:APPVEYOR_BUILD_FOLDER\DSCClassResources\**\*.psm1"}
> ```

Could we use a space after the opening brace and before the closing brace, for all occurrences, to be consequent? Throughout the file.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 73 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nyfzDF2yF07OZ5mFV:-L7nyfzDF2yF07OZ5mFW:b-9c7bse) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L73)):*
> direcotries

minor typo:" directories"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-:-L7nwweQJSHV5CjMDQSz:b-6mbliv)*

**Comment by limiteddenial** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 18 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nvjNE8WewhSltQc0o:-L7oPU0dncwpSLYGZ2_i:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L18)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> direcotries

minor typo:" directories"
</blockquote></details>

Done.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 27 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nw6FeB99LWJzhr3MX:-L7oPT8cC-lauhGNmfbb:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $False

`$false` (lower 'f')
</blockquote></details>

Done.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 28 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nwCfUYvO1_QUjovj3:-L7oPSQqPtv7FLcD7OB0:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L28)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> "file.Tests.ps1"

Can we use single quotes here?
</blockquote></details>

Done.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 32 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nwLwZszAR_8Sn_V4G:-L7oPUsT-i5ZXNBr98E9:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L32)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could we use a space after the opening brace and before the closing brace, for all occurrences, to be consequent? Throughout the file.
</blockquote></details>

Done.

---

*[Tests/Unit/AppVeyor.Tests.ps1, line 73 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-L7nyfzDF2yF07OZ5mFV:-L7oPVWLVKkzuV-R6BS-:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/7a9851cb23568a879e8c07c5638f72e52bef0a41/Tests/Unit/AppVeyor.Tests.ps1#L73)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> direcotries

minor typo:" directories"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/212)*

**Comment by johlju** [comment]
:lgtm:

@kwirkykat suggest we merge this PR first, and I can then rebase my other PR's on top of this one.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/212#-:-L7sP6G6texWad-Q0GRJ:bz06n94)*

**Pull request merged**
