### PR TITLE
Add check for dependent modules in Examples and Warns user or installs - Fixes #157

### LINKED ISSUE #157: The test Common Tests - Validate Example Files will fail if other Resources are required
For example, in xCertificate one of the examples uses xWebAdministration. The example validation fails because the module isn't installed on AppVeyor.

E.g.
https://ci.appveyor.com/project/PlagueHO/xcertificate/build/2.3.74.0#L156

There are several ways this could be resolved that I can see:
1. In the AppVeyor.yml for xCertificate (or any other resource with this problem) import xWebAdministration. I don't think this is a good way to do it because tests will fail on a users computer if they also haven't imported the module.
2. Create a test harness like is done in SharePointDsc and xNetworking (and other repos) that ensures the test environment is configured. Still not ideal IMHO as it requires a test harness -which most repos don't have.
3. The best way might be to use the AST to identify any dependent resource modules and install them from the PSGallery in the code for the `Common Tests - Validate Example Files` tests itself. This would be the more elegant solution IMHO, but it will be a bit more code (I'm looking into this method at the moment).

Obviously this is a bit of an edge case as xCertificate seems to be the only repo with this problem.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds support to identify any dependent modules in Example files (that aren't the module being tested) and will either warn the user they're required (tests will still fail) or if running in AppVeyor will install the module from the PS Gallery.

I added a new function `Get-ResourceModulesInConfiguration` that does the work of extracting any resource modules required in a DSC Configuration. It uses the PowerShell AST for this, but I do have an alternate method using RegEx around that I could use if the AST method isn't to taste.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/158)

### CODE REVIEW

**Comment by johlju** [comment]
I really impressed how you think one step ahead and added the evaluation for Array string (xNetworking,xWebAdministration)!  :smile: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Meta.Tests.ps1, line 16 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxXTf-74fQ0YNYYZb_:-KoxXTf-74fQ0YNYYZba:b-kg4fbn) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L16)):*
> ```PowerShell
> 
> $moduleRootFilePath = Split-Path -Path $PSScriptRoot -Parent
> $moduleName = (Get-Item -Path $moduleRootFilePath).Name
> ```

Minor: Maybe use this for consistency? (think it gives the same expected behavior...?)

```
Split-Path -Path $moduleRootFilePath -Leaf
```

---

*[Meta.Tests.ps1, line 511 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxXA02NQvfA9xIL9nr:-KoxXA02NQvfA9xIL9ns:b-2oits5) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L511)):*
> rquired

Typo

---

*[Meta.Tests.ps1, line 536 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxYoU60ku3_PE7jJbn:-KoxYoU60ku3_PE7jJbo:b-suczdy) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L536)):*
> ```PowerShell
> 
>                                         Write-Verbose -Message "Installing module '$($requiredModule.Name)' required to test example." -Verbose
>                                         Install-Module @requiredModule -Scope CurrentUser
> ```

If this fails, does it throw an error message? If so add a catch so the user see whats worng.
If it doesn't. Maybe add a verification that the module is available before continuing? If it is not, throw an error?

---

*[Meta.Tests.ps1, line 542 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxYPA2oLox-Uh1qgwO:-KoxYPA2oLox-Uh1qgwP:b-q7j4z5) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L542)):*
> ```PowerShell
>                                         # Warn the user that the test fill fail
>                                         if ($requiredModule.ContainsKey('Version')) {
>                                             Write-Warning -Message "Example requires resource module '$($requiredModule.Name)' version $($requiredModule.Version) but it is not installed on this computer."
> ```

Minor: Could we build this string instead so we are not using the mostly the same string in two locations? Okay as-is 

---

*[Meta.Tests.ps1, line 548 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxYicwzscqMYjYhep-:-KoxYicwzscqMYjYhep0:b-iqa19c) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L548)):*
> ```PowerShell
>                                             Write-Warning -Message "Example requires resource module '$($requiredModule.Name)' but it is not installed on this computer."
>                                         }
>                                         Write-Warning -Message 'This test will fail until the required module is installed. Please install it from the PowerShell Gallery to enable these tests to pass.'
> ```

Blank row before this one.

---

*[TestHelper.psm1, line 939 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxZk1ZYM7zSS5vefZn:-KoxZk1ZYM7zSS5vefZo:bvviiku) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L939)):*
> ```PowerShell
> {
>     [CmdletBinding()]
>     [OutputType([Hashtable[]])]
> ```

Minor: [System.Collections.Hashtable[]]

---

*[TestHelper.psm1, line 955 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_4eU5IEkhidd9DL3:-Kox_4eU5IEkhidd9DL4:b-fkrf3u) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L955)):*
> ```PowerShell
>     # Get all the Import-DscResource module commands
>     $importDscResourceCmds = $dscConfigurationAST.EndBlock.FindAll( {
>         $args[0] -is [System.Management.Automation.Language.DynamicKeywordStatementAst] -and `
> ```

For readability, could we add this script block to a variable and use the variable here instead?

---

*[TestHelper.psm1, line 973 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_PmVbd0lf7_5HoyS:-Kox_PmVbd0lf7_5HoyT:b-9kl9h2) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L973)):*
> ```PowerShell
>             }
>             elseif ($element -is [System.Management.Automation.Language.StringConstantExpressionAst] -and `
>                 $element.Value -ne 'Import-DscResource')
> ```

Minor: Rather see this row start with `-and` and idented under $element in the previous row.

---

*[TestHelper.psm1, line 980 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_d4ugukAYW7JG3qB:-Kox_d4ugukAYW7JG3qC:b-bb1zv0) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L980)):*
> ```PowerShell
>                     {
>                         $moduleName = $element.Value
>                         break
> ```

This just breaks out of the switch, not the foreach? Is break needed her?

---

*[TestHelper.psm1, line 982 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_oJaHW6zNCBS-WVw:-Kox_oJaHW6zNCBS-WVx:bij9huc) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L982)):*
> ```PowerShell
>                         break
>                     } # ModuleName
>                     'ModuleVersion'
> ```

New row before this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-:-KoxaRD4K0Hex9UYdLFC:brc7izu)*

**Comment by PlagueHO** [comment]
Hehe thanks @Johlju - I actually have a few other needs for this code as well - so needed to support all ways Import-DscResource can be formatted.

I've made most of the changes as per your comments. Just going to point my xCertificate at the new one to make sure it still works correctly in AppVeyor.

---

Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[Meta.Tests.ps1, line 16 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxXTf-74fQ0YNYYZb_:-KpCYYDd56wmeO0-3Tjo:b-4henty) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: Maybe use this for consistency? (think it gives the same expected behavior...?)

```
Split-Path -Path $moduleRootFilePath -Leaf
```
</blockquote></details>

I actually just moved this existing line (I didn't write it) so that I could get access to the value, but I think you're right - and it should probably be changed, but I'm reluctant to change it in this PR. This is just in case it breaks something BIG :grin: (e.g. every repo).

Might be better to keep this as a separate PR?

---

*[Meta.Tests.ps1, line 511 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxXA02NQvfA9xIL9nr:-KpCZ9K9CGRMIX1VcI8a:b-376vyo) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L511)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> rquired

Typo
</blockquote></details>

Done. Good catch!

---

*[Meta.Tests.ps1, line 536 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxYoU60ku3_PE7jJbn:-KpC_6IuYeJinaYmgulB:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L536)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If this fails, does it throw an error message? If so add a catch so the user see whats worng.
If it doesn't. Maybe add a verification that the module is available before continuing? If it is not, throw an error?
</blockquote></details>

Done.

---

*[Meta.Tests.ps1, line 542 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxYPA2oLox-Uh1qgwO:-KpC_7XFvLNk30tYadnr:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L542)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: Could we build this string instead so we are not using the mostly the same string in two locations? Okay as-is 
</blockquote></details>

Done.

---

*[Meta.Tests.ps1, line 548 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxYicwzscqMYjYhep-:-KpC_AxT9AebYhjlzuIg:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L548)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank row before this one.
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 939 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxZk1ZYM7zSS5vefZn:-KpC_FMW0_0AXnV_s8t0:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L939)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: [System.Collections.Hashtable[]]
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 955 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_4eU5IEkhidd9DL3:-KpC__KK2ThrsQOzPYem:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L955)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

For readability, could we add this script block to a variable and use the variable here instead?
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 973 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_PmVbd0lf7_5HoyS:-KpC_xN7zDWHzUUF6DcU:br4ihz1) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L973)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: Rather see this row start with `-and` and idented under $element in the previous row.
</blockquote></details>

Done...ish. Didn't do the alignment because it didn't work right with the indent.

---

*[TestHelper.psm1, line 980 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_d4ugukAYW7JG3qB:-KpCa4H7wHJqIp-Wu5_h:b-w8fkem) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L980)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This just breaks out of the switch, not the foreach? Is break needed her?
</blockquote></details>

You're right - sometimes get my languages mixed up :grin: Done.

---

*[TestHelper.psm1, line 982 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-Kox_oJaHW6zNCBS-WVw:-KpCaUpxYMLeXqn_lZcL:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/TestHelper.psm1#L982)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

New row before this one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-:-KpCXvFrmUn4mjZ0d0tG:b25aa1m)*

**Comment by PlagueHO** [comment]
@johlju - I have tried this out after making your suggested changes in my version of xCertificate: https://ci.appveyor.com/project/PlagueHO/xcertificate/build/2.3.78.0#L157

All looks good.

---

Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-:-KpCe1IJvabcnkDChKD3:b-frmqoc)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Meta.Tests.ps1, line 16 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-KoxXTf-74fQ0YNYYZb_:-KpERBhvcAxHnf3YChTD:b-dohtga) ([raw file](https://github.com/powershell/dscresource.tests/blob/c8d6cfb713e0312f91d0950e751ad9f64687964a/Meta.Tests.ps1#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I actually just moved this existing line (I didn't write it) so that I could get access to the value, but I think you're right - and it should probably be changed, but I'm reluctant to change it in this PR. This is just in case it breaks something BIG :grin: (e.g. every repo).

Might be better to keep this as a separate PR?

</blockquote></details>

Yes. Leave as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/158#-:-KpESbIF3r8jDAHCQvhp:bnfp4nl)*

**Comment by johlju** [comment]
@kwirkykat Whenever you have time, could you look this over?

**Comment by kwirkykat** [comment]
@mbreakey3 Can you merge this once it's rebased?

**Comment by PlagueHO** [comment]
Rebase complete! @johlju - could you sign off the files again please? Thanks sir!

**Comment by PlagueHO** [comment]
@Johlju - I'm not sure what has gone wrong with the rebase here. I'm going to recreate the PR because I haven't managed to fix it. Sorry about this!

**Comment by johlju** [comment]
@mbreakey3 so you have to merge PR #163 instead, which replaced this one, once the review comments are fixed.

**Pull request closed without merging**
