### PR TITLE
Fix Codecov bug with Harness-repos

### LINKED ISSUE #229: Codecov is no longer generate for "Harness"-model resource modules
The problem is that the parameter `CodeCoverage` is not used by the Harness-module repositories so line 913 will never be `$true`.

https://github.com/PowerShell/DscResource.Tests/blob/f1f2623aeec122c02635447b1d4e9413e2d7d923/AppVeyor.psm1#L911-L916

### PR DESCRIPTION
**Pull request by johlju**
- Updated AppVeyor.Tests
  - Mock for Resolve-CoverageInfo was removed since it was not used.
  - Moved importing of DscResource.CodeCoverage module to top of AppVeyor.psm1
    for easier mocking.
  - Added regression tests for issue #229.
- Changes to AppVeyor.psm1
  - Codecov is once again uploaded for "Harness"-model resource modules (issue #229).

Fixes #229

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/230)

### CODE REVIEW

**Comment by johlju** [comment]
Running tests against Default- and Harness-model.

**Comment by johlju** [comment]
Tested OK:
**SharePointDsc:** https://ci.appveyor.com/project/johlju/sharepointdsc/build/2.3.0.3#L13357
**StorageDsc:** https://ci.appveyor.com/project/johlju/storagedsc/build/2.9.1.0#L2740
**xDnsServer:** https://ci.appveyor.com/project/johlju/xdnsserver/build/1.7.3.0#L859

**Comment by johlju** [comment]
@PlagueHO or @ykuijs have wither of you time to review this one. Small one, mainly changed the ParameterSets and removed(moved a few rows. Biggest change was adding the regression test.

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/230#-:-LDHY2Dg4rv2tOLDty0V:bnfp4nl)*

**Pull request merged**
