### PR TITLE
Markdown tests: Disabled MD013 and MD024 and added option to override - Fixes #98

### LINKED ISSUE #98: Problem with markdown lint errors MD013 and MD024
In the xSQLServer repo the README.md currently have long lines and using the same header several times (like PSDscResource).

MD013
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.342.0#L864
MD024
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.342.0#L1139

We have three options as I see it (not taking in account changing the README.md).

1. Add MD013 and MD024 to the .markdownlint.json file in this module.
2. Change the code so it uses the .markdownlint.json in the module being tested if it exist. I guess this line need to do change https://github.com/PowerShell/DscResource.Tests/blob/dev/gulpfile.js#L21 with some logic :)
3. I workaround it by parsing in the additional MD013 and MD024 in the .markdownlint.json after cloning DscResource.Tests in AppVeyor.yml.

I personally like option 2.

### PR DESCRIPTION
**Pull request by johlju**
- Changes to common tests
  - Changed so that markdown lint rules MD013 and MD024 is disabled by default for the markdown common test.
  - Added an option to use a markdown lint settings file in the repository which will override the default markdown lint settings file in DscResource.Tests repository.

This fixes issue #98.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/146)

### CODE REVIEW

**Comment by johlju** [comment]
Tested overriding MD024 enabling the rule, by copying .markdownlint.json into the module repository and set the rule MD024 to true.

https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.709.0#L863

Tested using the default rule set, by not having a .markdownlint.json in the module repository.

https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.710.0#L863

**Comment by PlagueHO** [comment]
@johlju - I have this very problem in xComputerManagement! Great job!

So, is it correct to assume that the MD013 and MD024 are essentially now "Opt-in" rules? That means that if we have any repos that do want to enforce these rules because they already meet the MD013 and MD024 standards then we'll need to issue PR's to "Opt-in" to these settings?

I'm fine with this, but I just need to confirm that will be required because I'll need to make some PR's once this one goes through :grin:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[gulpfile.js, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGcw_7ehiPsEEh0Z9y:-KoGcw_7ehiPsEEh0Z9z:b-5omb8z) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/gulpfile.js#L24)):*
> ```JavaScript
>         {
>           "files": [file.path],
>           "config": require(process.argv[process.argv.indexOf("--settingspath") + 1])
> ```

Is it possible to default this parameter if it is not passed in? Pretty minor and is OK if it is difficult.

---

*[Meta.Tests.ps1, line 591 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGd67DeZWRQUW8exGu:-KoGd67EcaCo08AP3cst:b-1qo97j) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/Meta.Tests.ps1#L591)):*
> ```PowerShell
>         {
>             Write-Verbose -Message ('Using markdownlint settings file from repository folder ''{0}''.' -f $repoRootPath) -Verbose
>             $markdownlintSettingsFilePath = './../.markdownlint.json'
> ```

Can we use an absolute path here rather than a relative? I suspect this code will break on the auto-documentation repos (SharepointDsc, xNetworking etc).

---

*[README.md, line 82 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGdpyCviaqtP6Qi2nx:-KoGdpyCviaqtP6Qi2ny:b-lldd26) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L82)):*
> ```Markdown
> 
> It is possible to override the default behavior of the markdown validation test.
> By default the common tests is using the settings in the markdownlint settings file
> ```

By default the common tests use the settings in the markdownlint settings file

---

*[README.md, line 83 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGe0T_GCJdu18Z06Ig:-KoGe0T_GCJdu18Z06Ih:b-u3brvp) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L83)):*
> ```Markdown
> It is possible to override the default behavior of the markdown validation test.
> By default the common tests is using the settings in the markdownlint settings file
> [.markdownlint.json](/.markdownlint.json). If a the file '.markdownlint.json' exist
> ```

If the file ... exists 

---

*[README.md, line 84 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGe6Q5uGnP9lXLDf64:-KoGe6Q5uGnP9lXLDf65:bjutyy8) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L84)):*
> ```Markdown
> By default the common tests is using the settings in the markdownlint settings file
> [.markdownlint.json](/.markdownlint.json). If a the file '.markdownlint.json' exist
> in root path of module repository then that file will be used as the settings file.
> ```

in the root path of the module repository, then that file will be used as the settings file.

---

*[README.md, line 87 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGeE2lWaQdKjxr8sLb:-KoGeE2lWaQdKjxr8sLc:bni3l94) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L87)):*
> ```Markdown
> Please note that there are currently _only two markdown lint rules allowed to be
> overridden_, and that is lint rule MD013 (line length) and MD024 (Multiple headers
> with the same content). These are by default disabled, and can be enable by
> ```

These are disabled by default, and can be enabled by

---

*[README.md, line 88 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGeI6NgdUieVRepaFk:-KoGeI6NgdUieVRepaFl:bqyktuw) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L88)):*
> ```Markdown
> overridden_, and that is lint rule MD013 (line length) and MD024 (Multiple headers
> with the same content). These are by default disabled, and can be enable by
> individual repositories to enforce those lint rules.
> ```

lint -> linting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-:-KoGc2uKoaO6jCwFVau1:b-yxs3cw)*

**Comment by johlju** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[gulpfile.js, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGcw_7ehiPsEEh0Z9y:-KoICqHvJKCHKnJOzVX3:b-cgus49) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/gulpfile.js#L24)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to default this parameter if it is not passed in? Pretty minor and is OK if it is difficult.
</blockquote></details>

I gave it a shoot, my JavaScript knowledge is somewhat lacking :) I bet I would have put together half a Pester test on the time it took to make these rows :wink: 

I have not tested this yet. I can get AppVeyor to react to new pushes from my fork for some reason. I get back to this comment when this is tested.

---

*[Meta.Tests.ps1, line 591 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGd67DeZWRQUW8exGu:-KoIL8iuLZH0Rxm5YM_s:bz7hdor) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/Meta.Tests.ps1#L591)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we use an absolute path here rather than a relative? I suspect this code will break on the auto-documentation repos (SharepointDsc, xNetworking etc).
</blockquote></details>

.markdownlint.json should be put in the root folder in the repository, and DscResource.Tests clones into the root as well right? So this backs out from the cloned DscResource.Tests where the gulpfile.js exist, to the root folder.
This should work, unless DscResources.Tests is cloned into a deeper folder. Is it for Harness-model?

---

*[README.md, line 82 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGdpyCviaqtP6Qi2nx:-KoILeJD_XL9LIMtOoGS:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L82)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

By default the common tests use the settings in the markdownlint settings file
</blockquote></details>

Done.

---

*[README.md, line 83 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGe0T_GCJdu18Z06Ig:-KoILfQsnNN551ljGQSl:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L83)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If the file ... exists 
</blockquote></details>

Done.

---

*[README.md, line 84 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGe6Q5uGnP9lXLDf64:-KoILgabVyKGjkpiiO28:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L84)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

in the root path of the module repository, then that file will be used as the settings file.
</blockquote></details>

Done.

---

*[README.md, line 87 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGeE2lWaQdKjxr8sLb:-KoILhyBArP3WG6ccNLW:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L87)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

These are disabled by default, and can be enabled by
</blockquote></details>

Done.

---

*[README.md, line 88 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGeI6NgdUieVRepaFk:-KoILi_fSXKphuM07ogZ:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L88)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

lint -> linting
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146)*

**Comment by johlju** [comment]
Yes they will be Opt-In rules if this PR is accepted. Made this change according to comment https://github.com/PowerShell/DscResource.Tests/issues/98#issuecomment-279099164 by @kwirkykat. 
So yes, we need to add a .markdownlint.json file to each repo that needs to enable MD013 and MD024.

---

Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-:-KoIMNAvP_1peyFljc7y:bvjxjii)*

**Comment by johlju** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[gulpfile.js, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGcw_7ehiPsEEh0Z9y:-KoIlrEJ2ba5tXLKv9qM:b-racins) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/gulpfile.js#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I gave it a shoot, my JavaScript knowledge is somewhat lacking :) I bet I would have put together half a Pester test on the time it took to make these rows :wink: 

I have not tested this yet. I can get AppVeyor to react to new pushes from my fork for some reason. I get back to this comment when this is tested.
</blockquote></details>

I got this working for both xStorage and xSQLServer on the command line, but not in AppVeyor (xStorage don't find the duplicated header I created). Need to check on this tomorrow. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146)*

**Comment by PlagueHO** [comment]
No problem from me about adding the .markdownlint.json to each repo - they're actually already there mostly, but will just need to have rules enabled. Great job again!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gulpfile.js, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGcw_7ehiPsEEh0Z9y:-KoJ50I84OTTvFktebcT:bsgy1r4) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/gulpfile.js#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I got this working for both xStorage and xSQLServer on the command line, but not in AppVeyor (xStorage don't find the duplicated header I created). Need to check on this tomorrow. 
</blockquote></details>

No worries - I think this will be because of the harness model. The Harness model does clone DSCResource.Tests into a folder that isn't the root of the repo. I'm happy to try this out tonight on one of the harness repos (by pointing it to your version of this repo).

---

*[Meta.Tests.ps1, line 591 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGd67DeZWRQUW8exGu:-KoJ5Lw9dwU3I7vmxQen:bf8knvv) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/Meta.Tests.ps1#L591)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

.markdownlint.json should be put in the root folder in the repository, and DscResource.Tests clones into the root as well right? So this backs out from the cloned DscResource.Tests where the gulpfile.js exist, to the root folder.
This should work, unless DscResources.Tests is cloned into a deeper folder. Is it for Harness-model?
</blockquote></details>

I think the Harness model does clone to a different folder - but this change should now work. I'll test it out tonight on your fork.

---

*[README.md, line 88 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGeI6NgdUieVRepaFk:-KoJ5WNR-kU_aUiM8SGP:b48g4fi) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L88)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for putting up with my corrections :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-:-KoJ5f4EJ8Knyc1nZ-QS:b2b361p)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gulpfile.js, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGcw_7ehiPsEEh0Z9y:-KoJE1VOryk_1Q02S-c1:b-rjpksv) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/gulpfile.js#L24)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

No worries - I think this will be because of the harness model. The Harness model does clone DSCResource.Tests into a folder that isn't the root of the repo. I'm happy to try this out tonight on one of the harness repos (by pointing it to your version of this repo).
</blockquote></details>

Done.

Yeah, it works. Luckily I went for a a break with dinner and some TV, and when I got back for the community call I saw what mistake I did. For debugging purposes I wanted to check if the commit prior to your review worked on xStorage so I let git checkout that particular commit, and I forgot to revert that. :laughing:  

---
Added a duplicate header to test this in xStorage.

Markdown test using default file (no duplicate header found)
https://ci.appveyor.com/project/johlju/xstorage/build/2.9.17.5#L1564

Markdown test using specific .markdownlint.json file to opt-in (duplicate header found)
https://ci.appveyor.com/project/johlju/xstorage/build/2.9.16.5#L1564

---

*[Meta.Tests.ps1, line 591 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGd67DeZWRQUW8exGu:-KoJHELMehGDI63_wW1G:bb6un1j) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/Meta.Tests.ps1#L591)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think the Harness model does clone to a different folder - but this change should now work. I'll test it out tonight on your fork.
</blockquote></details>

Done

---

*[README.md, line 88 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGeI6NgdUieVRepaFk:-KoJHGVl91IH8kfRahbc:b-geb4wv) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/README.md#L88)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Thanks for putting up with my corrections :grin:
</blockquote></details>

I happy for the corrections :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146)*

**Comment by johlju** [comment]
@PlagueHO Do you have time to sign off on this one? Or find more problems 😉

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Meta.Tests.ps1, line 591 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-KoGd67DeZWRQUW8exGu:-KofCbbzFieVont9NCTD:bx4jvo8) ([raw file](https://github.com/powershell/dscresource.tests/blob/a768d3765ca39ee67d79f91cac01139d735495b3/Meta.Tests.ps1#L591)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I've tested this out as well on xNetworking and all looks good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/146#-:-KofCidKexGoz9958rSG:bnfp4nl)*

**Comment by johlju** [comment]
@kwirkykat Whenever you have time, could you review this one? 😄

**Pull request merged**
