### PR TITLE
Fix test with AppVeyor WMF5 images

### PR DESCRIPTION
**Pull request by pvs043**
Fix issue #217

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/221)

### CODE REVIEW

**Comment by johlju** [comment]
@pvs043 Thank you for resolving this issue! The change looks good to me, but could you add an entry to the change log under the Unreleased section. The entry should say what changed and why.

Unreleased section: https://github.com/PowerShell/DscResource.Tests/blob/dev/README.md#unreleased

Thanks again!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-:-LAg3PRl4zzVRe6zuSqI:bl0dkxf)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Tests/Unit/TestHelper.Tests.ps1, line 335 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-LAg5fOq0hreu23OIali:-LAg5fOq0hreu23OIalj:b-6q5dkf) ([raw file](https://github.com/powershell/dscresource.tests/blob/96d5a33f2ea6e06ce74b1755b0ff278dd9c2c6c6/Tests/Unit/TestHelper.Tests.ps1#L335)):*
> ```
> Get-PSModulePathItem
> ```

On second thought - I think we should you make this change in the helper function [`Get-PSModulePathItem`](https://github.com/PowerShell/DscResource.Tests/blob/dev/TestHelper.psm1#L1008) instead. That way we can also make a regression test for this change in the [unit test of `Get-PSModulePathItem`](https://github.com/PowerShell/DscResource.Tests/blob/dev/Tests/Unit/TestHelper.Tests.ps1#L328).

You think you could do that instead?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221)*

**Comment by pvs043** [comment]
@johlju, changes is done!

**Comment by johlju** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 618 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-LAgu-Va5lL-jiEaDK5T:-LAgu-Va5lL-jiEaDK5U:b-ihwwtd) ([raw file](https://github.com/powershell/dscresource.tests/blob/e9c6d2235b5a30c97d32f335bf91ffaa256999f7/README.md#L618)):*
> ```
> Trim
> ```

Could we write lower-case 't' on 'trim'?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221)*

**Comment by johlju** [comment]
@pvs043 Awesome! Could you please go into Reviewable and write 'Done' (or click the 'Done' button) on each comment? In this case it is only one comment, After that click the big green Publish button at the top. You find a link to Reviewable in the big purple button in the PR description. 
Writing done on the comments allow me to acknowledge them. 

Thanks!

**Comment by pvs043** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 618 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-LAgu-Va5lL-jiEaDK5T:-LAlANZe30fKQFX9Sxhb:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e9c6d2235b5a30c97d32f335bf91ffaa256999f7/README.md#L618)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Trim
> ```

Could we write lower-case 't' on 'trim'?
</blockquote></details>

Done.

---

*[Tests/Unit/TestHelper.Tests.ps1, line 335 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-LAg5fOq0hreu23OIali:-LAlAbzn7-Ay_g_sG62b:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96d5a33f2ea6e06ce74b1755b0ff278dd9c2c6c6/Tests/Unit/TestHelper.Tests.ps1#L335)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Get-PSModulePathItem
> ```

On second thought - I think we should you make this change in the helper function [`Get-PSModulePathItem`](https://github.com/PowerShell/DscResource.Tests/blob/dev/TestHelper.psm1#L1008) instead. That way we can also make a regression test for this change in the [unit test of `Get-PSModulePathItem`](https://github.com/PowerShell/DscResource.Tests/blob/dev/Tests/Unit/TestHelper.Tests.ps1#L328).

You think you could do that instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-:-LAlA2y88gUUXj-OhxXh:b-896fix)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/221#-:-LAmrjs6BLny8IZ__od2:bnfp4nl)*

**Comment by pvs043** [comment]
@johlju,
This is a great project and I want to participate in its development.
Thank Your!

**Comment by johlju** [comment]
You are more than welcome back! 🙂 There are a lot of issues still needing to be resolved 😀

**Pull request merged**
