### PR TITLE
moved $nugetPath = $tempNugetPath out of if clause to account for situation where nuget.exe exists in the temp path

### LINKED ISSUE #301: Bug in Install-ModuleFromPowerShellGallery. Does not use temp Nuget Path if the path exists
#### Details of the problem, bug, or enhancement

When nuget.exe is not available, but exists in the temp path, the Install-ModuleFromPowerShellGallery does not use the temp path.

#### Suggested solution to the issue

Move line 177 ($nugetPath = $tempNugetPath) outside of the if clause so that it runs when Nuget.exe exists in the temp path and when it needs to be downloaded

### PR DESCRIPTION
**Pull request by boscoedash**
#### This Pull Request (PR) fixes the following issues

- Fixes #301 

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)

### CODE REVIEW

**Review by PlagueHO — APPROVED** [review]
Thanks for submitting this @boscoedash - can you add an entry to the CHANGELOG.MD with this change (and link to issue etc) and also update the tests so that they pass?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302#-:-LOb3r201YU7dSbGG6N5:b-tuuwy9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by boscoedash** [comment]
@johlju It looks like something is wrong with the Appveyor build. It looks like it fails immediately after it kicks off. Any ideas how to fix this issue?

**Comment by johlju** [comment]
PR https://github.com/PowerShell/DscResource.Tests/pull/304 is trying to solve the problem. 🙂

**Comment by PlagueHO** [comment]
Can you fix the merge conflicts? The tests should now pass after that.

**Comment by PlagueHO** [comment]
I'm going to close and reopen the PR to trigger AppVeyor to start again.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: all files reviewed, 7 unresolved discussions (waiting on @boscoedash)

___
*[CHANGELOG.md, line 9 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUrMsg0ck7Ppslne58:-LPUrMsh0f6GHp8xEwRA:b-h4knp0) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/CHANGELOG.md#L9)):*
> ```Markdown
>   ([issue #219](https://github.com/PowerShell/DscResource.Tests/issues/219)).
> - Added functionality to Install-ModuleFromPowerShellGallery helper function to allow using Nuget.exe
>   when it is already installed in the temp path. Addresses issue ([issue #301](https://github.com/PowerShell/DscResource.Tests/issues/301)).
> ```

Can you remove the 'issue' from 'Addresses issue' because it already appears in the link. Otherwise it shows 'Addresses issue issue #301'.
___
*[TestHelper.psm1, line 182 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUr_XSAl8zUgZUxfAe:-LPUr_XSAl8zUgZUxfAf:b-bp7wyw) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/TestHelper.psm1#L182)):*
> ```PowerShell
>         }
> 
>         $nugetPath = $tempNugetPath        
> ```

Nitpick, can you trim the trailing spaces on this line? Suggest using VS Code and configuring it to autotrim trailing spaces on save.
___
*[TestHelper.psm1, line 190 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsWDY-lao4qhdMcxC:-LPUsWDY-lao4qhdMcxD:b2f7koz) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/TestHelper.psm1#L190)):*
> ```PowerShell
> 
>     # Use Nuget.exe to install the module
> ```

Can you remove this blank line?
___
*[TestHelper.psm1, line 191 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUs4ph-L_6wYCKupi5:-LPUs4ph-L_6wYCKupi6:b-uxgwo0) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/TestHelper.psm1#L191)):*
> ```PowerShell
>     # Use Nuget.exe to install the module
> 
>     $arguments = "install $ModuleName -source $nugetSource -outputDirectory $moduleOutputDirectory -ExcludeVersion"
> ```

Nitpick: Can you use an array of arguments here instead of a string? 
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1208 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsu99Bv9peAZhH4Wm:-LPUsu99Bv9peAZhH4Wn:bkfvcu6) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1208)):*
> ```PowerShell
>                 }
> 
>                 Mock -CommandName 'Get-Command' -MockWith {$mockGetCommand}
> ```

Can you use { and } on new lines. E.g.
```powershell
-MockWith {
    $mockGetCommand
}
```

And througout (in ParameterFilter and MockWith parameters). See previous tests.
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1216 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsd_16vuI4ApTV_bg:-LPUsd_16vuI4ApTV_bh:bypv1ms) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1216)):*
> ```PowerShell
>                 Assert-MockCalled -CommandName 'Get-Command' -Exactly -Times 1 -Scope It
>             }
>             
> ```

Can you trim whitespace from this line?
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1220 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsotR3nk8O7uRbJJO:-LPUsotR3nk8O7uRbJJP:b-hd0xk2) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1220)):*
> ```PowerShell
>                 $tempPath = Join-Path -Path $env:temp -ChildPath 'Nuget.exe'
>                 Mock -CommandName 'Get-Command'
>                 Mock -CommandName 'Start-Process' -ParameterFilter {$FilePath -eq $tempNugetPath}  -MockWith {@{ExitCode = 0}}
> ```

Can you use the

**Review by boscoedash — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: all files reviewed, 7 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 9 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUrMsg0ck7Ppslne58:-LQg92UJ3Z1vVoyMJfga:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/CHANGELOG.md#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove the 'issue' from 'Addresses issue' because it already appears in the link. Otherwise it shows 'Addresses issue issue #301'.
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 182 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUr_XSAl8zUgZUxfAe:-LQg9FP08cN--NSk5Tjq:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/TestHelper.psm1#L182)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick, can you trim the trailing spaces on this line? Suggest using VS Code and configuring it to autotrim trailing spaces on save.
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 190 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsWDY-lao4qhdMcxC:-LQg9Zif5jJ64QUi2ZXp:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/TestHelper.psm1#L190)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this blank line?
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 191 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUs4ph-L_6wYCKupi5:-LQgA1ExC5hp8Wn7Soxl:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/TestHelper.psm1#L191)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Can you use an array of arguments here instead of a string? 
</blockquote></details>

Done.
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1208 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsu99Bv9peAZhH4Wm:-LQgAIpf02717GfaBx9a:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1208)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use { and } on new lines. E.g.
```powershell
-MockWith {
    $mockGetCommand
}
```

And througout (in ParameterFilter and MockWith parameters). See previous tests.
</blockquote></details>

Done.
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1216 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsd_16vuI4ApTV_bg:-LQgASvaC7G6vJsCHCPp:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1216)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you trim whitespace from this line?
</blockquote></details>

Done.
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1220 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsotR3nk8O7uRbJJO:-LQgAeBvDwzcaQIV0Fco:b-fzfnqv) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1220)):*
>               
The what?

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: all files reviewed, 3 unresolved discussions (waiting on @boscoedash)

___
*[TestHelper.psm1, line 10 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LQr2EbO237BbiRRljSi:-LQr2EbO237BbiRRljSj:b2d0zf1) ([raw file](https://github.com/powershell/dscresource.tests/blob/b69cbf523739442ebdc4c14f24cc69e70f07acb4/TestHelper.psm1#L10)):*
> ```PowerShell
>     if not load all the helper types.
> #>
> if (-not ('Microsoft.DscResourceKit.Test' -as [Type])) {
> ```

Actually, all the { should be on the following line - as you previously had it -are you able to revert that? It is possible you have a .VSCode setting enabled to force this?
___
*[TestHelper.psm1, line 184 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LQr2TEGDnCqStJQVgQ6:-LQr2TEGDnCqStJQVgQ7:bmeibe5) ([raw file](https://github.com/powershell/dscresource.tests/blob/b69cbf523739442ebdc4c14f24cc69e70f07acb4/TestHelper.psm1#L184)):*
> ```PowerShell
>         "-source $nugetSource" `
>         "-outputDirectory $moduleOutputDirectory" `
>         "-ExcludeVersion"
> ```

Can you use single quotes around just this string?
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1220 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsotR3nk8O7uRbJJO:-LQr3MOw1u5gnb6HhMr3:b-v31a98) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1220)):*
<details><summary><i>Previously, boscoedash wrote…</i></summary><blockquote>

>               
The what?
</blockquote></details>

Doh! Sorry - not sure what happened to the rest of that comment. But what I mean to say, can you use this format:
```powershell
Mock -CommandName 'Start-Process' -ParameterFilter {
    $FilePath -eq $tempNugetPath
}  -MockWith {
    @{ExitCode = 0}
}
```

**Review by boscoedash — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[TestHelper.psm1, line 10 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LQr2EbO237BbiRRljSi:-LRI0G7x8oea9c1twNek:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/b69cbf523739442ebdc4c14f24cc69e70f07acb4/TestHelper.psm1#L10)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Actually, all the { should be on the following line - as you previously had it -are you able to revert that? It is possible you have a .VSCode setting enabled to force this?
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 184 at r5](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LQr2TEGDnCqStJQVgQ6:-LRI0a8Q2WA2WLq54QEX:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/b69cbf523739442ebdc4c14f24cc69e70f07acb4/TestHelper.psm1#L184)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes around just this string?
</blockquote></details>

Done.
___
*[Tests/Unit/TestHelper.Tests.ps1, line 1220 at r4](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LPUsotR3nk8O7uRbJJO:-LRI0vpyAHhJEXCMAj65:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/edd08c253d597311452f5065f12d22a89fe829ca/Tests/Unit/TestHelper.Tests.ps1#L1220)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Doh! Sorry - not sure what happened to the rest of that comment. But what I mean to say, can you use this format:
```powershell
Mock -CommandName 'Start-Process' -ParameterFilter {
    $FilePath -eq $tempNugetPath
}  -MockWith {
    @{ExitCode = 0}
}
```
</blockquote></details>

Done.

**Comment by johlju** [comment]
This PR is not abandoned, it's waiting for the review to continue. 🙂 

/cc @PlagueHO

**Comment by johlju** [comment]
@boscoedash Could you rebase this PR against dev,  since another PR was merged making this PR out-of-date against the base branch (dev). 🙂

**Comment by PlagueHO** [comment]
Thanks @johlju - removed abandoned tag and updating the branch.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: all files reviewed, 1 unresolved discussion (waiting on @boscoedash)

___
*[TestHelper.psm1, line 93 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LV-jyzX4h-xoEdjZD-G:-LV-jyzX4h-xoEdjZD-H:butdq5x) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2279f84b515a32ca4ac0a3fd7376a71e6ac6b2f/TestHelper.psm1#L93)):*
> ```PowerShell
> "@
> 
>     if (-not [String]::IsNullOrEmpty($LicenseUrl)) 
> ```

Nitpick: Can you trim the whitespace from the end of these lines? Suggest using Visual Studio Code and enabling the Files: Trim Trailing Whitespace setting.

**Review by boscoedash — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[TestHelper.psm1, line 93 at r7](https://reviewable.io/reviews/powershell/dscresource.tests/302#-LV-jyzX4h-xoEdjZD-G:-LV4O2b-C0lW4tpzsMMN:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/e2279f84b515a32ca4ac0a3fd7376a71e6ac6b2f/TestHelper.psm1#L93)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Can you trim the whitespace from the end of these lines? Suggest using Visual Studio Code and enabling the Files: Trim Trailing Whitespace setting.
</blockquote></details>

Done.

**Comment by PlagueHO** [comment]
Hi @boscoedash - looks like there is some errors in the tests:
https://ci.appveyor.com/project/PowerShell/dscresource-tests/builds/21308992#L246

Also some spelling errors in the markdown are showing up.

**Review by PlagueHO — APPROVED** [review]
Great stuff @boscoedash

:lgtm:

> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302#-:-LVPr3d0ErXoHblziCHi:bedyfkd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/302)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
