### PR TITLE
Automatic install integration test module dependencies

### PR DESCRIPTION
**Pull request by johlju**
- Changes to common tests
  - Code was moved from the example tests into a new helper function `Install-DependentModule` (issue #168). Fixed bug with Version, where Install-Module would not use the correct variable for splatting.
- Changes to integration tests
  - Enable so that missing required modules for integration tests is installed if running in AppVeyor or show warning if run by user (issue #168).

This was tested OK, see below.

Installed dependent modules for integration tests: https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.823.0#L40
And the integration test run fine: https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.823.0#L1490

This was also tested OK for the new code for the old test (compiling examples) in xCertificate.
https://ci.appveyor.com/project/johlju/xcertificate/build/2.3.2.0#L328

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/172)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Would you mind doing a review of this, since you are familiar with the code? 😄 The tests looks okay at least!

**Comment by PlagueHO** [comment]
@Johlju - great job! Only some trivial non-blocking issues.

So:

:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 397 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy-IAep8UuTbAU16W2:-Kpy-IAf0VqU_m2eOC_d:b3stugs) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/README.md#L397)):*
> ```Markdown
>   ([issue #169](https://github.com/PowerShell/DscResource.Tests/issues/169)).
> * Code was moved from the example tests into a new helper function Install-DependentModule
>   ([issue #168](https://github.com/PowerShell/DscResource.Tests/issues/168)). Fixed bug with Version, where Install-Module would not use the correct
> ```

Could you maybe split this line so it doesn't wrap (e.g. less than 80 chars or whatever)? Not a blocker.

---

*[TestHelper.psm1, line 1157 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy-Tn5sbLegHJEf6PY:-Kpy-Tn5sbLegHJEf6PZ:b-gsuhsb) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/TestHelper.psm1#L1157)):*
> ```PowerShell
>     .SYNOPSIS
>         Installs dependent modules in the user scope, if not already available
>         and only if run on a AppVeyor build worker. If not run on a AppVeyor
> ```

Nitpick (:grin: sorry):
...not run on _an_ AppVeyor...

---

*[TestHelper.psm1, line 1229 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy01tw2jPgZQtZNYRX:-Kpy01txvMfw9IE-cOVF:by4s6wf) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/TestHelper.psm1#L1229)):*
> ```PowerShell
>             {
>                 # Warn the user that the test fill fail
>                 Write-Warning -Message ("To be able to compile a configuration the resource module $requiredModuleName is required but it is not installed on this computer. " + `
> ```

Not required: split this string so that it doesn't wrap (e.g. just after $requiredModuleName). Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-:-Kpy0Q2ES_s-N_LQcuGX:b-33neb)*

**Comment by johlju** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 397 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy-IAep8UuTbAU16W2:-Kq6c3jQgYAL2HDJ_3k_:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/README.md#L397)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you maybe split this line so it doesn't wrap (e.g. less than 80 chars or whatever)? Not a blocker.
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1157 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy-Tn5sbLegHJEf6PY:-Kq6c4nOPTmtOEdCLfQs:brl9f68) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/TestHelper.psm1#L1157)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick (:grin: sorry):
...not run on _an_ AppVeyor...
</blockquote></details>

Done. Again, thanks for proof reading! :smile: 

---

*[TestHelper.psm1, line 1229 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy01tw2jPgZQtZNYRX:-Kq6cC-4K4KMZPN5V_9B:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/TestHelper.psm1#L1229)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Not required: split this string so that it doesn't wrap (e.g. just after $requiredModuleName). Not a blocker.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/172)*

**Comment by PlagueHO** [comment]
Great stuff as always @johlju - do you ever sleep? :grin:

:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[TestHelper.psm1, line 1157 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-Kpy-Tn5sbLegHJEf6PY:-Kq6tUl9tRT4tMVw0Cgt:bl4cmvk) ([raw file](https://github.com/powershell/dscresource.tests/blob/cdc7060a243f9337bb0b414624f3ce1d92039805/TestHelper.psm1#L1157)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Again, thanks for proof reading! :smile: 
</blockquote></details>

A pleasure!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-:-Kq6tZvrDLBu4Mv0s0Sl:b-1eit32)*

**Comment by johlju** [comment]
@PlagueHO haha 😆 Actually, I was surprised how fast I put all these things together, coding in three repos in just a few hours, reviewing PR's and looking into user issues 😄

I love doing this. Think what could be accomplished I could do this full time 😀

**Comment by johlju** [comment]
@kwirkykat As soon as PR #174 is merged we can merge this one. But I might need to rebase in-between.

**Comment by johlju** [comment]
@kwirkykat It should have been PR #175 so the tests can pass.

**Comment by PlagueHO** [comment]
@johlju - tell me about it! We'd have all the tech debt gone in a day if you did this full time :grin:

**Comment by johlju** [comment]
@kwirkykat this is ready for review, after rebase, tests are passing.

@PlagueHO can you review the last file after rebase?

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/172#-:-Kr59keIDjtptBC3Ivpz:bnfp4nl)*

**Pull request merged**
