### PR TITLE
Keyword check- suggested corrections

### PR DESCRIPTION
**Pull request by SSvilen**
#### Pull Request (PR) description
I have added correction for the keyword checks (capital letters and missing single space between keyword and parenthesis).
May be this would help someone in the future.
Let me know what you think.

#### This Pull Request (PR) fixes the following issues
None.

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/350)

### CODE REVIEW

**Comment by SSvilen** [comment]
Hi @PlagueHO,

would you have the time to review this one? It's a relatively small change.

**Comment by PlagueHO** [comment]
Hi @SSvilen - can you fix the conflicts on this one and I'll get it through. Sorry about the recent delays.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/350)* status: all files reviewed, 3 unresolved discussions (waiting on @SSvilen)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1048 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/350#-Lt42tIZ7YCOJRPOmo6F:-Lt42tIZ7YCOJRPOmo6G:byrbasc) ([raw file](https://github.com/powershell/dscresource.tests/blob/a5999156abb6d6f57141c7d4930df756d2d92cae/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1048)):*
> ```PowerShell
>             $script:diagnosticRecord['Extent'] = $item.Extent
>             $script:diagnosticRecord['Message'] = $localizedData.StatementsContainsUpperCaseLetter -f $item.Text
>             $suggestedCorrections = New-Object Collections.Generic.List[Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.CorrectionExtent]
> ```

Can you use -TypeName?
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1048 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/350#-Lt43WXA3H4XcR_S3bnR:-Lt43WXA3H4XcR_S3bnS:b-cfedzi) ([raw file](https://github.com/powershell/dscresource.tests/blob/a5999156abb6d6f57141c7d4930df756d2d92cae/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1048)):*
> ```PowerShell
>             $script:diagnosticRecord['Extent'] = $item.Extent
>             $script:diagnosticRecord['Message'] = $localizedData.StatementsContainsUpperCaseLetter -f $item.Text
>             $suggestedCorrections = New-Object Collections.Generic.List[Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.CorrectionExtent]
> ```

Is it possible to move this block into it's own function? That would reduce the code duplication.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1067 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/350#-Lt43-Os0omRhOsLDnbo:-Lt43-Os0omRhOsLDnbp:byrbasc) ([raw file](https://github.com/powershell/dscresource.tests/blob/a5999156abb6d6f57141c7d4930df756d2d92cae/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1067)):*
> ```PowerShell
>             $script:diagnosticRecord['Extent'] = $item.Extent
>             $script:diagnosticRecord['Message'] = $localizedData.OneSpaceBetweenKeywordAndParenthesis
>             $suggestedCorrections = New-Object Collections.Generic.List[Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.CorrectionExtent]
> ```

Can you use -TypeName?

**Comment by gaelcolas** [comment]
Also, @SSvilen we're moving AnalyzerRules to its own modules, so please submit a similar PR for dsccommunity/DscResource.AnalyzerRules before this can be merged.

Thanks, and sorry for the overhead.

**Review by SSvilen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/350)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1048 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/350#-Lt42tIZ7YCOJRPOmo6F:-Lt9uZI31h8wy60YD20N:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a5999156abb6d6f57141c7d4930df756d2d92cae/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1048)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use -TypeName?
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1048 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/350#-Lt43WXA3H4XcR_S3bnR:-LtGX93C0e59d4R8Bz7z:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a5999156abb6d6f57141c7d4930df756d2d92cae/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1048)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to move this block into it's own function? That would reduce the code duplication.
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1067 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/350#-Lt43-Os0omRhOsLDnbo:-LtGX9be29okIrLNFbgB:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/a5999156abb6d6f57141c7d4930df756d2d92cae/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1067)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use -TypeName?
</blockquote></details>

Done.

**Comment by gaelcolas** [comment]
Reflecting the comment from the `DscResource.AnalyzerRules`, you're missing unit tests for `New-SuggestedCorrection` function.

**Comment by PlagueHO** [comment]
Hi @gaelcolas, @SSvilen - where are we at with this one? Is it still waiting changes?

**Comment by SSvilen** [comment]
Hi @PlagueHO - this is already implemented in DscResource.AnalyzerRules and I think it does not make sense to merge it here also. (as this module will be retired).
I'm closing this one.

**Pull request closed without merging**
