### PR TITLE
Enable integration tests to run in order - Fixes #184

### LINKED ISSUE #184: Running integration test that are dependent on another integration test
When doing integration tests in xSQLServer I would really like to be able to control the order the integration tests are run. 
The first integration tests that should run is "install" using xSQLServerSetup, then all other integration test follow that. The first xSQLServerSetup integration tests sets up all the accounts and installs an instance to run tests on.

I like the order to something like this:

- (order 1) xSQLServerSetup (install)
- (order 2) xSQLServerLogin 
- (order 2) xSQLServerAlwaysOnService
- (order 3) xSQLServerPermission
- (order 4) xSQLServerSetup (uninstall)
- (unordered) xSQLServerAlias

Today integration test for xSQLServerAlwaysOnService is run before xSQLServerSetup which means the integration test fails.
See https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.845.0#L1384.

I could make one file with all the test in them, in order. But that file would be terrible to make changes to and review.

Or, I think it would be possible to separate all files without '.Tests.' in the name ('*MSFT_xSQLServerSetup.Integration.ps1*' and '*MSFT_xSQLServerAlwaysOnService.Integration.ps1*')  and dot source all the files in correct order into a '*xSQLServer.Integration.Tests.ps*' file.

Another thought I had is adding a new switch parameter `-OrderedTest` to function `Invoke-AppveyorTestScriptTask` which defaults to `$false`. If set to `$true`, and using the "default"-model, instead of calling `Invoke-Pester` once for all tests, `Invoke-Pester` is called several times. The number of times depends on how many "order numbers" there are.
I thought of adding a Order property to the configuration, but the configuration in the current design is not on disk. But we might need to but them on disk instead for this to work. 
Another way is add a number to the filename, ie '*1_MSFT_xSQLServerSetup.config*' and '*2_MSFT_xSQLServerAlwaysOnService.config.ps1*'.

Thoughts?

### PR DESCRIPTION
**Pull request by johlju**
- Add opt-in parameter RunTestInOrder for the helper function Invoke-AppveyorTestScriptTask
  which enables running integration tests in order (issue #184).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/186)

### CODE REVIEW

**Comment by johlju** [comment]
This is tested here; https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.854.0#L43

**Comment by johlju** [comment]
@kwirkykat When trying to fix a bug over at xSQLServer (https://github.com/PowerShell/xSQLServer/issues/774), I hit another problem with the integration test that I think I can fix with a little tweak to this PR. Instead of running the integration tests before the unit tests, I need the integration tests to run _after_ the unit tests.

It has to do with our mocking of the assembly. Integration tests load the SMO assembly resulting in that our mock of SMO fails to load with `Add-Type`.

I let you know when this is ready to review again!

**Comment by johlju** [comment]
@kwirkykat Okay, so fixed to the new order, ready for review again. So when you have a chance, please review this one 😄 
 
Added one test, but I will get back to adding more tests once things quite down over at xSQLServer.

**Comment by johlju** [comment]
Forgot to add this test link. Tested OK here (see order of list of tests)
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.891.0#L42

_Please ignore that the tests are failing, has nothing to do with this change._

**Comment by johlju** [comment]
@PlagueHO Maybe you can do an initial review this one to help out @kwirkykat a bit?

**Comment by PlagueHO** [comment]
Hi @Johlju - I've had a look through this and it has occurred to me there might be another solution to this: Create a custom decorator.

With a custom decorator you could add this to the beginning of the *.config.ps1. E.g.
```PowerShell
[DSCIntegrationTestOrder(1)]
```

You could then still use your `Get-DscIntegrationTestOrderNumber` cmdlet to pull the order out of the *.config.ps1 file, but it would work regardless of if a hashtable existed. You could use the AST to extract this more easily too I think.

To support the custom decorator you'd need to declare the Custom attribute class for the `DSCIntegrationTestOrder` attribute somewhere in the DSCResource.tests code:
```powershell
Class DSCIntegrationTestOrder : Attribute {
    [string]$Order

    DSCIntegrationTestOrder([int]$Order)
    {
        $this.Order = $Order
    }
}
```
Note: The above code would probably need to be changed to support WMF4.

This sort of method might be extended in future to support other metadata we'd need to include in tests.

What do you think?

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[README.md, line 338 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7sxTgabIlkJV-RGjg:-Ks7sxTgabIlkJV-RGjh:buao0n2) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L338)):*
> ```Markdown
> ## Run integration tests in order
> 
> This is only available for resource modules that are using the "Default"-model,
> ```

Non-blocking: Could we use something like `shared AppVeyor module model` rather than `Default-model`? 

---

*[README.md, line 340 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7t84LfY6WwgwVjVmY:-Ks7t84LfY6WwgwVjVmZ:bcfl3y7) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L340)):*
> ```Markdown
> This is only available for resource modules that are using the "Default"-model,
> meaning those resource modules that are calling the helper function
> `Invoke-AppveyorTestScriptTask` either without the parameter 'Type', or has
> ```

Non-blocking: Perhaps put parameter in back ticks with a dash to make it clear that is is a parameter `-Type`. Same on next line.

---

*[README.md, line 343 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7tSxbiqB6QQASPxxY:-Ks7tSxbiqB6QQASPxxZ:b3fhhvi) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L343)):*
> ```Markdown
> assigned the value 'Default' to parameter `Type`.
> 
> >**Note:** Resource modules using the "Harness"-model must add this functionality
> ```

Non-blocking: Could add an example (e.g. SharePointDsc) to make it clear what a "Harness"-model is?

---

*[README.md, line 350 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7tdUM8t5aZLQiIdYM:-Ks7tdUM8t5aZLQiIdYN:byhu99d) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L350)):*
> ```Markdown
> `-RunTestInOrder`.
> 
> Also, in each integration test configuration file ('*.config.ps1'), there must be
> ```

Many integration test resources actually pass the Hash table in using a `-ConfigurationData` parameter (e.g https://github.com/PowerShell/xStorage/blob/dev/Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1#L60). It might be worth pointing out that in these cases a hash table will need to be added to the config regardless.

---

*[README.md, line 351 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7sobr8zzuczIFoVjQ:-Ks7sobr8zzuczIFoVjR:b-nnw0n7) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L351)):*
> ```Markdown
> 
> Also, in each integration test configuration file ('*.config.ps1'), there must be
> a hash table containing a name-value pair named 'DscIntegrationTestOrder' and be
> ```

Non-blocking: Should `name-value` be `key-value`?

---

*[README.md, line 369 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7scp2t-H1G_3m5Lvy:-Ks7scp3Owq_nMrBpcTg:b-nnw0n7) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L369)):*
> ```Markdown
> is always run as one of the first tests.
> 
> >**Note:** It is not necessary for the name-value pair 'DscIntegrationTestOrder' to be in the
> ```

Non-blocking: Should `name-value` be `key-value`?

---

*[Tests/Unit/TestHelper.Tests.ps1, line 18 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7txMDcpAU1YhEiOCF:-Ks7txMEbnVPZfxCYqgS:b6asjf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/Tests/Unit/TestHelper.Tests.ps1#L18)):*
> ```PowerShell
> 
>                 '@()' | `
>                     Out-File $filePath_NoHashTable
> ```

Can we change to named parameter?

---

*[Tests/Unit/TestHelper.Tests.ps1, line 21 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7u0Wc78CsH4-5mZE-:-Ks7u0Wc78CsH4-5mZE0:b6asjf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/Tests/Unit/TestHelper.Tests.ps1#L21)):*
> ```PowerShell
> 
>                 '@{}' | `
>                     Out-File $filePath_EmptyHashTable
> ```

Can we change to named parameter?

---

*[Tests/Unit/TestHelper.Tests.ps1, line 24 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7u1N_b-jAsXJnM6_P:-Ks7u1N_b-jAsXJnM6_Q:b6asjf3) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/Tests/Unit/TestHelper.Tests.ps1#L24)):*
> ```PowerShell
> 
>                 '@{DscIntegrationTestOrder=2}' | `
>                     Out-File $filePath_HashTableWithCorrectValue
> ```

Can we change to named parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-:-Ks7xzQG-y9xsQ4ftBn3:b-bec7xn)*

**Comment by PlagueHO** [comment]
Oops- should be:
```powershell
Class DSCIntegrationTestOrder : Attribute {
    [int]$Order

    DSCIntegrationTestOrder([int]$Order)
    {
        $this.Order = $Order
    }
}
```

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-:-Ks7zvZ_qNJsBtrpI7Bd:b-pb660c)*

**Comment by johlju** [comment]
@PlagueHO your suggestion using a custom attribute is so cool! I built a prototype. It's fully working, and should support PowerShell 4.0? Should I switch to this?

**Configuration script:**
```powershell
[Microsoft.DscResourceKit.DSCIntegrationTestOrder(OrderNumber = 2)]
param()

configuration MSFT_xSQLServerSetup_InstallSqlEngineAsSystem_Config
{
    # ... Configuration code
}
```
**Custom attribute (DSCIntegrationTestOrder.cs):**

```csharp
// Custom Attribute for determining the order a test should run in.
// Used to decorate a DSC configuration file with for example [DSCIntegrationTestOrder(OrderNumber = 1)].

using System;

namespace Microsoft.DscResourceKit
{
    [System.AttributeUsage(System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    sealed class DSCIntegrationTestOrder : System.Attribute
    {
        // See the attribute guidelines at
        // http://go.microsoft.com/fwlink/?LinkId=85236
        readonly int orderNumber;

        // This is a positional argument
        public DSCIntegrationTestOrder(int orderNumber)
        {
            this.orderNumber = orderNumber;
        }

        public int OrderNumber
        {
            get { return orderNumber; }
        }

        // This is a named argument
        //public int NamedInt { get; set; }
    }
}
```

**`Get-DscIntegrationTestOrderNumber` helper function:**
```powershell
function Get-DscIntegrationTestOrderNumber
{
    [CmdletBinding()]
    [OutputType([System.UInt32])]
    param
    (
        [Parameter()]
        [ValidateNotNullOrEmpty()]
        [String]
        $Path
    )

    <#
        Will always return $null if the attribute
        'DscIntegrationTestOrder' is not found.
    #>
    $returnValue = $null

    # Change WarningAction so it not output a warning for the sealed class.
    Add-Type -Path (Join-Path -Path $PSScriptRoot -ChildPath 'DSCIntegrationTestOrder.cs') -WarningAction SilentlyContinue

    $scriptBlockAst = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref] $null, [ref] $null)

    $findDSCIntegrationTestOrderAttributeFilter = {
        $args[0] -is [System.Management.Automation.Language.AttributeAst] `
        -and (
            $args[0].TypeName.FullName -eq 'DSCIntegrationTestOrder' `
            -or $args[0].TypeName.FullName -eq 'Microsoft.DscResourceKit.DSCIntegrationTestOrder'
        )
    }

    # Get DSCIntegrationTestOrder attribute in the file if it exist.
    [System.Management.Automation.Language.Ast[]] $dscIntegrationTestOrderAttributeAst = `
        $scriptBlockAst.Find($findDSCIntegrationTestOrderAttributeFilter, $true)

    if ($dscIntegrationTestOrderAttributeAst)
    {
        $findOrderNumberNamedAttributeArgumentFilter = {
            $args[0] -is [System.Management.Automation.Language.NamedAttributeArgumentAst] `
            -and $args[0].ArgumentName -eq 'OrderNumber'
        }

        [System.Management.Automation.Language.Ast[]] $orderNumberNamedAttributeArgumentAst = `
            $dscIntegrationTestOrderAttributeAst.Find($findOrderNumberNamedAttributeArgumentFilter, $true)

        if ($orderNumberNamedAttributeArgumentAst)
        {
            $returnValue = $orderNumberNamedAttributeArgumentAst.Argument.Value
        }
    }

    return $returnValue
}
```

**Comment by johlju** [comment]
@PlagueHO I refactored this according to your suggestion. It improved the usage a lot. I tried to get PowerShell 4.0 compatibility, I hope the method I used will work with PowerShell 4.0. I have not tested that, I have no machine with PowerShell 4.0 available.
Please suggest other namespace, attribute, named attribute arguments names if there are better.

Tested OK here; https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.924.0#L43

---

Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 338 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7sxTgabIlkJV-RGjg:-KsEhRaufnZnOW8Nx9s0:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L338)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking: Could we use something like `shared AppVeyor module model` rather than `Default-model`? 
</blockquote></details>

Done.

---

*[README.md, line 340 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7t84LfY6WwgwVjVmY:-KsEhShhrOZkhNGyB3cj:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L340)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking: Perhaps put parameter in back ticks with a dash to make it clear that is is a parameter `-Type`. Same on next line.
</blockquote></details>

Done.

---

*[README.md, line 343 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7tSxbiqB6QQASPxxY:-KsEhUQkGx_vGuxhmurM:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L343)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking: Could add an example (e.g. SharePointDsc) to make it clear what a "Harness"-model is?
</blockquote></details>

Done.

---

*[README.md, line 350 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7tdUM8t5aZLQiIdYM:-KsEhXx6QdfVgbDnIqOf:b-cxchxo) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L350)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Many integration test resources actually pass the Hash table in using a `-ConfigurationData` parameter (e.g https://github.com/PowerShell/xStorage/blob/dev/Tests/Integration/MSFT_xDiskAccessPath.Integration.Tests.ps1#L60). It might be worth pointing out that in these cases a hash table will need to be added to the config regardless.
</blockquote></details>

No longer relevant.

---

*[README.md, line 351 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7sobr8zzuczIFoVjQ:-KsEhe1N_NjgmE9IDo6D:b-cxchxo) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L351)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking: Should `name-value` be `key-value`?
</blockquote></details>

No longer relevant.

---

*[README.md, line 369 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7scp2t-H1G_3m5Lvy:-KsEhfDE9l8Epi6GWmpZ:b-cxchxo) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/README.md#L369)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking: Should `name-value` be `key-value`?
</blockquote></details>

No longer relevant.

---

*[Tests/Unit/TestHelper.Tests.ps1, line 18 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7txMDcpAU1YhEiOCF:-KsEhsNWj0gHnQsbrqOF:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/Tests/Unit/TestHelper.Tests.ps1#L18)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we change to named parameter?
</blockquote></details>

Done.

---

*[Tests/Unit/TestHelper.Tests.ps1, line 21 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7u0Wc78CsH4-5mZE-:-KsEhs5n8Q1epjkUDFZV:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/Tests/Unit/TestHelper.Tests.ps1#L21)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we change to named parameter?
</blockquote></details>

Done.

---

*[Tests/Unit/TestHelper.Tests.ps1, line 24 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-Ks7u1N_b-jAsXJnM6_P:-KsEhrXlUbfvFGd9vJr_:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/96a09f3a1f5682cff2bd1bdec2d0c01019754cee/Tests/Unit/TestHelper.Tests.ps1#L24)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we change to named parameter?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-:-KsEgaWB3ckw8I3QyHvW:b-1zxjlb)*

**Comment by PlagueHO** [comment]
Fantastic stuff @johlju - really awesome as always. I'm just traveling at the moment but will be able to review on Friday night. But really awesome and this is very cool!

**Comment by johlju** [comment]
Thanks! 😄 This will help a lot in xSQLServer, hopefully we can improve on this for other stuff to :) 

Please let me know if we should rename the names of the namespace, attribute etc. I had poor imagination when I tried to figure what would be the best names in the long run 😄

**Comment by PlagueHO** [comment]
Only some minor spelling/grammar things! Looking great! :grin:

---

Reviewed 1 of 1 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[AppVeyor.psm1, line 312 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNEyeFvPaxpbCKOtQk:-KsNEyeGUnGWVBpl8bdD:b-7y5y61) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/AppVeyor.psm1#L312)):*
> ```PowerShell
>                 $integrationTestConfigurationFiles = Get-ChildItem @getChildItemParameters
> 
>                 # In each file, search for existens of key value pair 'DscIntegrationTestOrder'.
> ```

This comment needs to be updated to match new attribute method

---

*[README.md, line 351 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHDzOJdkg-6gN0oC-:-KsNHDzOJdkg-6gN0oC0:b-h49aj9) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/README.md#L351)):*
> ```Markdown
> 
> Also, each integration test configuration file ('*.config.ps1') must be decorated
> with a attribute 'IntegrationTest' containing a name attribute argument
> ```

with *an* attribute

Also, could the attribute full name be used here and perhaps in back ticks? E.g.

with an attribute `Microsoft.DscResourceKit.IntegrationTest` ..

---

*[README.md, line 359 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHgPgq6r_aq70z2Vo:-KsNHgPhHPZoCDtEAoiN:b-7e20uk) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/README.md#L359)):*
> ```Markdown
> value 1 will be run before integration tests with value 2. If an integration test
> does not have a assigned order, it will be run unordered after all ordered tests
> has been run.
> ```

*have* been run.

---

*[README.md, line 366 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHqKIuVle-ZRJTJJz:-KsNHqKJTX62EcautNW0:bmc5zu5) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/README.md#L366)):*
> ```Markdown
> and the integration test file is named 'MSFT_xSQLServerSetup.Integration.Tests.ps1'.
> 
> Example how the configuration file could look like to make sure a integration test
> ```

make sure *an* integration test

---

*[TestHelper.psm1, line 1258 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHxlikaV6a3u99pN2:-KsNHxlikaV6a3u99pN3:b-ajbfd5) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1258)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Returns the integration test order number if it exist in the attribute
> ```

if it *exists* in the attribute

---

*[TestHelper.psm1, line 1259 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNI0Lm8XE6OkRdM3U3:-KsNI0Lm8XE6OkRdM3U4:b6x04zu) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1259)):*
> ```PowerShell
>     .SYNOPSIS
>         Returns the integration test order number if it exist in the attribute
>         'IntegrationTest' with the named attribute argument 'OrderNumber'.
> ```

Maybe include the full name of the attribute Microsoft.DscResourceKit.IntegrationTest

---

*[TestHelper.psm1, line 1279 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNI7igTAviuSX4j9eE:-KsNI7igTAviuSX4j9eF:b-1xam4k) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1279)):*
> ```PowerShell
> 
>     <#
>         Will always return $null if the attribute 'IntegrationTest'
> ```

Use the full name? Microsoft.DscResourceKit.IntegrationTest

---

*[TestHelper.psm1, line 1284 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNIBia6i6gaBh_B10W:-KsNIBia6i6gaBh_B10X:bdmu8xd) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1284)):*
> ```PowerShell
>     $returnValue = $null
> 
>     # Change WarningAction so it not output a warning for the sealed class.
> ```

so it *does* not output

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-:-KsNJ26j1JRhcvWIQUJ0:bmfxzqt)*

**Comment by johlju** [comment]
I changed a variable that also used the old attribute name.

---

Review status: 2 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[AppVeyor.psm1, line 312 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNEyeFvPaxpbCKOtQk:-KsPZobhVtMUnwe0xVMq:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/AppVeyor.psm1#L312)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This comment needs to be updated to match new attribute method
</blockquote></details>

Done.

---

*[README.md, line 351 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHDzOJdkg-6gN0oC-:-KsPZs0vZewYacUmXLjv:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/README.md#L351)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

with *an* attribute

Also, could the attribute full name be used here and perhaps in back ticks? E.g.

with an attribute `Microsoft.DscResourceKit.IntegrationTest` ..
</blockquote></details>

Done.

---

*[README.md, line 359 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHgPgq6r_aq70z2Vo:-KsPZuiWdGVSpokLa9Ke:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/README.md#L359)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

*have* been run.
</blockquote></details>

Done.

---

*[README.md, line 366 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHqKIuVle-ZRJTJJz:-KsPZvaNmJh8ng4bYPC6:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/README.md#L366)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

make sure *an* integration test
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1258 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNHxlikaV6a3u99pN2:-KsPZxxcpnIlTJI8e2ce:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1258)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

if it *exists* in the attribute
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1259 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNI0Lm8XE6OkRdM3U3:-KsPZySZ5s6ON59umldz:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1259)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Maybe include the full name of the attribute Microsoft.DscResourceKit.IntegrationTest
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1279 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNI7igTAviuSX4j9eE:-KsP_5d9EiRd0R3yOO3i:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1279)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Use the full name? Microsoft.DscResourceKit.IntegrationTest
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 1284 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-KsNIBia6i6gaBh_B10W:-KsP_6qkpommg5yyOeeE:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/efe0e8bae2b4afba770f3f93be5a13c1e1bc7b69/TestHelper.psm1#L1284)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

so it *does* not output
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-:-KsP_LYt_Yo5i_Qi4gPk:bxkyq7l)*

**Comment by PlagueHO** [comment]
Nice job @Johlju !

:lgtm:

@KwirkyKat - any chance of a merge if you're OK with this?

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/186#-:-KsQUjDxYgnfb4lJs0Pr:bxmv655)*

**Comment by johlju** [comment]
@kwirkykat do you have a chance to look this over? Would love to get this merged so I can continue my work over at xSQLServer, which depends on this.

**Pull request merged**
