### PR TITLE
Refactored the class IntegrationTest - Fixes #191

### LINKED ISSUE #191: RunTestInOrder non-working all of the sudden
For some reason the class Microsoft.DscResourceKit.IntegrationTest cannot be loaded when dot-sourcing the configuration files. This did work when the PR was tested. But those tests that worked before, does no longer work either. This is really strange 🤔 
Maybe it was just luck that it worked before, or if I did a mistake in the testing. I don't know. Either way it is broken. :)

The error:
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.927.0#L5627

Something strange has happened, because it can no longer see the sealed class. It seems that making this a public class it starts to find it. But then it reports it does not have a constructor with zero arguments. But we are passing in one argument.

```
PS > . .\MSFT_xSQLServerSetup.config.ps1
Cannot find an overload for ".ctor" and the argument count: "0".
At V:\Source\xSqlServer\Tests\Integration\MSFT_xSQLServerSetup.config.ps1:2 char:1
+ [Microsoft.DscResourceKit.IntegrationTest(OrderNumber = 1)]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

Adding a constructor with zero arguments gives this error
```
PS > . .\MSFT_xSQLServerSetup.config.ps1
'OrderNumber' is a ReadOnly property.
At V:\Source\xSqlServer\Tests\Integration\MSFT_xSQLServerSetup.config.ps1:2 char:1
+ [Microsoft.DscResourceKit.IntegrationTest(OrderNumber = 1)]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyIsReadOnly
```

Finally adding a new named property, instead of using a positional seems to work.

```
namespace Microsoft.DscResourceKit
{
    // See the attribute guidelines at http://go.microsoft.com/fwlink/?LinkId=85236
    [System.AttributeUsage(System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    public sealed class IntegrationTest : System.Attribute
    {
        public IntegrationTest() {}

        public int OrderNumber { get; set; }
    }
}
```

I really need for this to work, so I will refactor the class to this, if it passes the tests, I will send in a PR to change to this.

### PR DESCRIPTION
**Pull request by johlju**
- Changes to ordered tests
   - Refactored the class IntegrationTest to fix issue #191.

I checked, doubled checked, triple checked and fourth checked. This _should_ work now! 😄

**Prior to this PR tests failed** for a pending PR working branches here
* Branch xSQLServer/fix-issue-649:
  https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.927.0#L5627
* Branch xSQLServer/xSQLServerAlwaysOnService-integration-test:
  https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.931.0#L5608

**With this fix, it's Tested OK** for the pending PR working branches here: 
* Branch xSQLServer/fix-issue-649 (testing against this fix PR) : 
  https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.934.0#L5582
* Branch xSQLServer/test-orderedtests-issue191 (branched from xSQLServer/xSQLServerAlwaysOnService-integration-test, to test against this fix PR):
  https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.932.0#L5614
  _Note: Other tests still fails, but unrelated, because it is dependent on the previous working branch._

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/192)

### CODE REVIEW

**Comment by johlju** [comment]
@kwirkykat Would you be so kind to look over this and merge this fix?

I was hoping to spend this weekend perfecting the integration tests in xSQLServer, so I'm hoping you can get this merged. It will not impact any other repos since none is running ordered tests yet (and they couldn't since it's broken ;).
If you don't have time I fully understand. Thanks! 😄

**Comment by PlagueHO** [comment]
:lgtm:

Would you mind merging this if you get a chance @KwirkyKat ?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/192#-:-Ksz3oXmVDv01j2VEx4t:b-8iumyp)*

**Comment by johlju** [comment]
@PlagueHO Can you sign off on the README.md after rebase?

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/192#-:-KtQZlNNWGb43jZHSCFO:bnfp4nl)*

**Comment by johlju** [comment]
@PlagueHO Can you sing off on the README.md again? Rebased and made it more descriptive.

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/192#-:-KtVIWa0zzFy6Yr4Qffp:bnfp4nl)*

**Pull request merged**
