### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by TravisEz13**
Fix formatting per second issue in
#88

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/116)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@PlagueHO @johlju  Please review

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/116#-:-KcjZjwssf3oCKJ-POvy:bnfp4nl)*

**Comment by TravisEz13** [comment]
@PlagueHO I saw you have another PR that fixes some of the same issues.  are you ok with me merging? You'll have to fix your PR.

**Comment by PlagueHO** [comment]
@TravisEz13 - sure! No problem!

**Pull request merged**
