### PR TITLE
Turning on Custom Script Analyzer Rules meta tests

### PR DESCRIPTION
**Pull request by SSvilen**
#### Pull Request (PR) description
With this PR I would like to turn on the Custom Script Analyzer Rules meta tests for this repo and also turn on the custom rules for VSCode. 

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/351)

### CODE REVIEW

**Comment by SSvilen** [comment]
Hi @PlagueHO  @johlju ,

Do you thinkg this PR would bring any value?

**Comment by johlju** [comment]
Absolutely! We just haven’t been able to get to it yet :) 

I have been so busy over at xWebAdministration :)

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Great stuff @SSVilen - just some minor bits and pieces.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/351#-:-LqxKy8qEkGd-0lLAFVD:blb4gwm)* status: all files reviewed, 14 unresolved discussions (waiting on @SSvilen)

___
*[Meta.Tests.ps1, line 50 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxIeGa7E42_LRQvflO:-LqxIeGb9q9CrX1MK_0S:bpppyzs) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/Meta.Tests.ps1#L50)):*
> ```PowerShell
> $dscResourcesFolderFilePath = Join-Path -Path $moduleRootFilePath -ChildPath 'DscResources'
> 
> if (-not (Test-Path $dscResourcesFolderFilePath))
> ```

Can you change to named parameter?
___
*[Meta.Tests.ps1, line 938 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxInye5GC6899h5UPh:-LqxInye5GC6899h5UPi:b-p95y3d) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/Meta.Tests.ps1#L938)):*
> ```PowerShell
>                     if ($dscResourcesFolderFilePath -eq $moduleRootFilePath)
>                     {
>                         #reverting back to defaults
> ```

Can you add a space after # and make capital letter?
___
*[Meta.Tests.ps1, line 940 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxIliz3XgvYyE9jsmQ:-LqxIliz3XgvYyE9jsmR:bgeuuxq) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/Meta.Tests.ps1#L940)):*
> ```PowerShell
>                         #reverting back to defaults
>                         $dscResourcesFolderFilePath = Join-Path -Path $moduleRootFilePath -ChildPath 'DscResources'
>                     }
> ```

Can you add blank line after this one?
___
*[TestHelper.psm1, line 60 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxIvE_EwHeA9WK3f3q:-LqxIvE_EwHeA9WK3f3r:b-y3gqwb) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L60)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [String]
> ```

Non-blocking nitpick: Can you change these to remove type accelerators? E.g. use [System.String]
___
*[TestHelper.psm1, line 531 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxJ80T0wbfbc6ocRI-:-LqxJ80T0wbfbc6ocRI0:b-q74hj3) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L531)):*
> ```PowerShell
>     $fileAst = [System.Management.Automation.Language.Parser]::ParseFile($FilePath, [ref]$null, [ref]$null)
> 
>     foreach ($fileAttributeAst in $fileAst.FindAll( { $args[0] -is [System.Management.Automation.Language.AttributeAst] }, $false))
> ```

Is it possible to reduce the line length here by assigning the list to a value first (as is done further on).
___
*[TestHelper.psm1, line 863 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxJcGQ9ZBaI9IUMaiT:-LqxJcGQ9ZBaI9IUMaiU:bsg9ftk) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L863)):*
> ```PowerShell
>     foreach ($attributeAst in $attributeAsts)
>     {
>         if ([System.Diagnostics.CodeAnalysis.SuppressMessageAttribute].FullName.ToLower().Contains($attributeAst.TypeName.FullName.ToLower()))
> ```

 Is there any way to reduce the length of this line?
___
*[TestHelper.psm1, line 1673 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxJtRF9UAYYayuqEoT:-LqxJtRF9UAYYayuqEoU:b-z1na2r) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L1673)):*
> ```PowerShell
>     )
> 
>     $curentColor = $host.ui.RawUI.ForegroundColor
> ```

Nitpick: use capital letters for UI object. ANd the following lines.
___
*[TestHelper.psm1, line 2058 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxK7zQ1NAg55DndGoh:-LqxK7zQ1NAg55DndGoi:b30ocp2) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L2058)):*
> ```PowerShell
>     {
>         Write-Warning -Message "The following PSScriptAnalyzer rule '$($ruleNameGroup.Name)' errors need to be fixed:"
>         foreach ($rule in $ruleNameGroup.Group)
> ```

Can you add a blank line before this one?
___
*[DscResource.CodeCoverage/CodeCovIo.psm1, line 43 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKH0e7CvLCtitQfmv:-LqxKH0e7CvLCtitQfmw:b30ocp2) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.CodeCoverage/CodeCovIo.psm1#L43)):*
> ```PowerShell
>     # file paths need to be relative to repo root when querying GIT
>     Push-Location -LiteralPath $RepoRoot
>     try
> ```

Can you add a blank line before this one?
___
*[DscResource.Container/DscResource.Container.psm1, line 726 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKRiMEI_URS816Cry:-LqxKRiMEI_URS816Crz:b-ukhmwv) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.Container/DscResource.Container.psm1#L726)):*
> ```PowerShell
> 
>         [PSCustomObject[]] $MissedCommand = $MissedCommand |
>         Select-Object -Property @{
> ```

I think this block needs to be indented (VS Code autoformatting broke this I suspect)
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 407 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKhtVDRE7aW8cZLSS:-LqxKhtVDRE7aW8cZLST:b-ielsrc) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L407)):*
> ```PowerShell
>     {
>         Write-Verbose -Message $script:localizedData.ConfigGlobalGitMessage
>         Invoke-Git -Arguments 'config --global core.autocrlf true'
> ```

Can we change these to an array as well?
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 411 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKdjM27Cvh300SckQ:-LqxKdjM27Cvh300SckR:b-bwwesv) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L411)):*
> ```PowerShell
>         $wikiRepoName = "https://github.com/$RepoName.wiki.git"
>         Write-Verbose -Message ($script:localizedData.CloneWikiGitRepoMessage -f $WikiRepoName)
>         Invoke-Git -Arguments 'clone', "$wikiRepoName" , "$path" , '--quiet'
> ```

I don't think the double quotes around the variables are required here.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 462 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKlbX1egjg6_ntWFF:-LqxKlbX1egjg6_ntWFG:brisaox) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L462)):*
> ```PowerShell
> 
>         Write-Verbose -Message $script:localizedData.ConfigLocalGitMessage
>         Invoke-Git -Arguments 'config', '--local', 'user.email', "$GitUserEmail"
> ```

I don't think the double quotes around the $GituserEmail variable is needed here.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 463 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKrhu2f2BEaHtkWWS:-LqxKrhu2f2BEaHtkWWT:b-xm2fvi) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L463)):*
> ```PowerShell
>         Write-Verbose -Message $script:localizedData.ConfigLocalGitMessage
>         Invoke-Git -Arguments 'config', '--local', 'user.email', "$GitUserEmail"
>         Invoke-Git -Arguments 'config', '--local', 'user.name', "$GitUserName"
> ```

I don't think the double quotes around the $GituserName variable is needed here.

**Review by SSvilen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/351)* status: all files reviewed, 14 unresolved discussions (waiting on @PlagueHO)

___
*[Meta.Tests.ps1, line 50 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxIeGa7E42_LRQvflO:-Lr4jHCz5xOQvrZyy0zE:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/Meta.Tests.ps1#L50)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to named parameter?
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 938 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxInye5GC6899h5UPh:-Lr4jOTc4zPWCTkn8UmU:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/Meta.Tests.ps1#L938)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a space after # and make capital letter?
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 940 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxIliz3XgvYyE9jsmQ:-Lr4jRg04EZlNXu_nEs6:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/Meta.Tests.ps1#L940)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add blank line after this one?
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 60 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxIvE_EwHeA9WK3f3q:-Lr4jjV259h9Mujss34v:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L60)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Non-blocking nitpick: Can you change these to remove type accelerators? E.g. use [System.String]
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 531 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxJ80T0wbfbc6ocRI-:-Lr4k4Gv8jUGo3mZ1VvV:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L531)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to reduce the line length here by assigning the list to a value first (as is done further on).
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 863 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxJcGQ9ZBaI9IUMaiT:-Lr4kNwN1FKurCKIpRr6:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L863)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

 Is there any way to reduce the length of this line?
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 1673 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxJtRF9UAYYayuqEoT:-Lr4k_L91mlPPQMc0QQ2:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L1673)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: use capital letters for UI object. ANd the following lines.
</blockquote></details>

Done.
___
*[TestHelper.psm1, line 2058 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxK7zQ1NAg55DndGoh:-Lr4keoi3RhQOkHEFYCY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/TestHelper.psm1#L2058)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this one?
</blockquote></details>

Done.
___
*[DscResource.CodeCoverage/CodeCovIo.psm1, line 43 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKH0e7CvLCtitQfmv:-Lr4kt57-pduIY2LBwpX:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.CodeCoverage/CodeCovIo.psm1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line before this one?
</blockquote></details>

Done.
___
*[DscResource.Container/DscResource.Container.psm1, line 726 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKRiMEI_URS816Cry:-Lr4lZfk3bWu4L9apGqC:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.Container/DscResource.Container.psm1#L726)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this block needs to be indented (VS Code autoformatting broke this I suspect)
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 407 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKhtVDRE7aW8cZLSS:-Lr4lv1e5erxQ0yrVele:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L407)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we change these to an array as well?
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 411 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKdjM27Cvh300SckQ:-Lr4sSH_Blw92fK645jt:bveea0c) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L411)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I don't think the double quotes around the variables are required here.
</blockquote></details>

Hm..I'm sure I had some sort of idea about that..
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 462 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKlbX1egjg6_ntWFF:-Lr4soHQ6u0Nec_JEmWA:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L462)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I don't think the double quotes around the $GituserEmail variable is needed here.
</blockquote></details>

Done.
___
*[DscResource.DocumentationHelper/WikiPages.psm1, line 463 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/351#-LqxKrhu2f2BEaHtkWWS:-Lr4sovQ8FKS29owhacp:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/2b72134860233d381e283f6dfb802b737b43601f/DscResource.DocumentationHelper/WikiPages.psm1#L463)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I don't think the double quotes around the $GituserName variable is needed here.
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
Great job!

:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/351#-:-LrVHzGF6VjYwNoci08x:b-wl13fc)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/351#-:-LrVI74MAcBiVukLAUu9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
