### PR TITLE
Updated so that module files are checked for Byte Order Mark (BOM) - Fixes #143

### LINKED ISSUE #143: Test for Byte Order Mark (BOM) on module files
Module files (.psm1) should be UTF-8, and not UTF-8 with BOM.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-file-encoding

I have at least one resource that has BOM in it's module file, in xSQLServer.

Should we do a check for BOM for this files as well, like we do with markdown files?
Any other file types?

### PR DESCRIPTION
**Pull request by johlju**
- Changes to common tests
  - Updated so that checking for Byte Order Mark (BOM) in markdown file lists the full path so it easier to distinguish when filenames are equal in different locations.
  - Updated It-blocks for File Parsing tests so that they are more descriptive for the AppVeyor "Tests-view".
  - Updated so that module files (.psm1) are checked for Byte Order Mark (BOM) (issue #143).
- Removed Byte Order Mark (BOM) from the module file TestRunner.psm1.

**There was a lot of module files in xSQLServer that had BOM. Maybe the same in other repositories. So this PR, when approved, might be best to merged after next release.**

This is tested here:
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.747.0#L106

This PR also improves the output in the "Tests-view" in AppVeyor.

image

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/153)

### CODE REVIEW

**Comment by johlju** [comment]
@kwirkykat Maybe I should add so that this new test needs to be opt-in using the file '.MetaTestOptIn.json'? What do you think?

```json
[
    "Common Tests - Validate Module Files"
]
```

**Comment by PlagueHO** [comment]
@johlju - I was just thinking about this problem this morning. I think there are many common tests that aren't being applied to the "helper" module files - for example, PSSA.

I think we should be applying these to the common helper modules as well. I'll raise this in a separate issue.

**Comment by johlju** [comment]
@PlagueHO I agree. At least this test (and the previous test in the same Context-block) runs on all module files under module root using `Get-Psm1FileList -FilePath $moduleRootFilePath`.

**Comment by johlju** [comment]
I will add so that you need to opt-in for this one. I think that is better, otherwise there might be technical debt in resource that is not as highly maintained.

**Comment by johlju** [comment]
This is ready for review again.

I had to move out the test to it's own Describe-block to enable opt-in. I didn't want the previous test to be opt-in (the test above the new test).

Tested OK here when repo has opted-out (the default).
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.758.0#L193

And tested OK here when the repo has opt-in (failing the tests correctly).
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.759.0#L193

**Comment by PlagueHO** [comment]
Only some tiny style nitpicks. Tiny! But other than that looking awesome! :grin:

---

Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[TestHelper.psm1, line 937 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRNEANkgI1J9I8EAJ:-KoxRNEANkgI1J9I8EAK:bf19wz2) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L937)):*
> ```PowerShell
> function Test-FileHasByteOrderMark
> {
>     Param(
> ```

Should be:
```
param
(
```

---

*[TestHelper.psm1, line 964 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRWZDgYr1htxa939K:-KoxRWZE3wt_2VzbHX38:bf19wz2) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L964)):*
> ```PowerShell
> function Get-RelativePathFromModuleRoot
> {
>     Param(
> ```

Should be:
```
param
(
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-:-KoxRkvUiO1V1L7krzzg:bxi3hps)*

**Comment by johlju** [comment]
Thanks for catching those! :smile: 

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[TestHelper.psm1, line 937 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRNEANkgI1J9I8EAJ:-KoxVIX3kyzfBgQtWb4v:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L937)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be:
```
param
(
```

</blockquote></details>

Done.

---

*[TestHelper.psm1, line 964 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRWZDgYr1htxa939K:-KoxVJKr5aNeCcomFmgw:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L964)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be:
```
param
(
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-:-KoxVMBkUL9HPnzlxhFe:b-jw6m1c)*

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[TestHelper.psm1, line 937 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRNEANkgI1J9I8EAJ:-Kox_ODaUjdzyxaJAbaU:bxoi8uq) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L937)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Open bracket should be on the next line :grin: So sorry! 

---

*[TestHelper.psm1, line 964 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRWZDgYr1htxa939K:-Kox_TteAZVVp4An8XZl:bxoi8uq) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L964)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Open bracket should be on the next line :grin: So sorry! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/153)*

**Comment by johlju** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[TestHelper.psm1, line 937 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRNEANkgI1J9I8EAJ:-Koxc6O1HdCM7-EpEyZe:b-g6jj7x) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L937)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Open bracket should be on the next line :grin: So sorry! 
</blockquote></details>

Done. Ah! Missed that. :/ I think it's time to watch some TV and prepare for bed than code at this hour :laughing: 

---

*[TestHelper.psm1, line 964 at r2](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-KoxRWZDgYr1htxa939K:-KoxcWPFiq1iEWa8_mxe:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/aca816680d6cbc5f353789f6390757bd19a8dc89/TestHelper.psm1#L964)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Open bracket should be on the next line :grin: So sorry! 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/153)*

**Comment by PlagueHO** [comment]
All good @johlju - you always do such a great job, but it is good that I can occasionally pick something up :grin:

:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-:-Kp8GY66nNNS_A7Eu0UM:bc9y27r)*

**Comment by johlju** [comment]
Rebased. Resulted in some white space changes in recently merged code.

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/153#-:-KpH6IOaT0Nl1t3hSnzo:bnfp4nl)*

**Comment by johlju** [comment]
@kwirkykat Whenever you have time, could you look this over?

**Pull request merged**
