### PR TITLE
Add localization tests

### LINKED ISSUE #145: Validating localization files
I think we need a common test that validates the localization strings. With that I mean a test that takes the English localization file and then verifies that against all the keys in the other localization files. This is to find missing keys in either files.

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Add common tests for localization, these tests is opt-in (issue #145).
  - Should have an en-US localization folder.
  - The en-US localization folder should have the correct casing.
  - Should exist a resource file with the correct name in the localization folder.
  - The resource or module should use all the localization string keys from the localization resource file.
  - The localization resource file should not be missing any localization string key that are used in the resource or module.
  - If there are other localization folders (other than en-US)
    - They should contain a resource file with the correct name.
    - The folders should use the correct casing.
    - All en-US resource file localized string keys must also exist in the resource file.
    - There should be no additional localized string keys in the resource file that does not exist in the en-US resource file.

#### This Pull Request (PR) fixes the following issues
- Fixes #145 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/319)

### CODE REVIEW

**Comment by johlju** [comment]
Not opt-in:
https://ci.appveyor.com/project/johlju/computermanagementdsc/builds/23939476?fullLog=true#L913

Opt-in and failing:
https://ci.appveyor.com/project/johlju/computermanagementdsc/builds/23940614?fullLog=true#L913

Not having a passing test yet, I thought I fix that in ComputerManagementDsc and will send in a PR which I will link to here. Fixing this in ComputerManagementDsc will shown bugs in this PR.

**Comment by johlju** [comment]
Opt-in and passing:
https://ci.appveyor.com/project/PowerShell/computermanagementdsc/builds/23948903?fullLog=true#L916

**Comment by johlju** [comment]
@PlagueHO I think this is ready for review now.

**Comment by PlagueHO** [comment]
Awesome! Will get onto it now! Can you resolve conflicts @johlju ?

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/319)* status: all files reviewed, 20 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 38 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhSHQC0YCicOMabdy7:-LdhSHQC0YCicOMabdy8:b-xf7qid) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L38)):*
> ```Markdown
>   use AllowClobber
>   ([issue #310](https://github.com/PowerShell/DscResource.Tests/issues/310)).
> - Add common tests for localization, these tests is opt-in ([issue #145](https://github.com/PowerShell/DscResource.Tests/issues/145)).
> ```

Could rewrite as: Added common opt-in tests for localization
___
*[CHANGELOG.md, line 41 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhS_Su1FcrOpV2zG7V:-LdhS_Su1FcrOpV2zG7W:beyh4ea) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L41)):*
> ```Markdown
>   - Should have an en-US localization folder.
>   - The en-US localization folder should have the correct casing.
>   - Should exist a resource file with the correct name in the localization folder.
> ```

-> A resource file  with the correct name should exist in the localization folder.
___
*[CHANGELOG.md, line 43 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhStqe7jDTr0cX08ZT:-LdhStqe7jDTr0cX08ZU:b-7quwvw) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L43)):*
> ```Markdown
>   - Should exist a resource file with the correct name in the localization folder.
>   - The resource or module should use all the localization string keys from the localization resource file.
>   - The localization resource file should not be missing any localization string key that are used in the resource or module.
> ```

string key that are used -> string key that is used
___
*[CHANGELOG.md, line 48 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhT28Q8DXP-B3q4zbD:-LdhT28Q8DXP-B3q4zbE:by3j59k) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L48)):*
> ```Markdown
>     - The folders should use the correct casing.
>     - All en-US resource file localized string keys must also exist in the resource file.
>     - There should be no additional localized string keys in the resource file that does not exist in the en-US resource file.
> ```

that does not -> that do not
___
*[Meta.Tests.ps1, line 1259 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhUvD26GVk1ajf8rTx:-LdhUvD26GVk1ajf8rTy:bc3qr3) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1259)):*
> ```PowerShell
>         Context 'When a resource or module should have localization files' {
>             BeforeAll {
>                 $testCases = @()
> ```

Nitpick: Is it worth changing the `$testCases` to something more descriptive like `$foldersToTest`?
___
*[Meta.Tests.ps1, line 1321 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhUVfXCYtfaZV2KP6_:-LdhUVfXCYtfaZV2KP6a:b-yabe43) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1321)):*
> ```PowerShell
>                 $localizationResourceFilePath = Join-Path -Path (Join-Path -Path $Path -ChildPath 'en-US') -ChildPath "$Folder.strings.psd1"
> 
>                 Test-Path -Path $localizationResourceFilePath | Should -BeTrue -Because 'the there must exist a string resource file in the localization folder en-US'
> ```

the there must -> there must
___
*[Meta.Tests.ps1, line 1330 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhVXy37JuT0_8GjRkJ:-LdhVXy37JuT0_8GjRkK:bcsxr9z) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1330)):*
> ```PowerShell
> 
>                 $testCases_LocalizedKeys = @()
>                 $testCases_UsedLocalizedKeys= @()
> ```

Needs space after =
___
*[Meta.Tests.ps1, line 1392 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhYk9a03T5yq5gruPh:-LdhYk9a03T5yq5gruPi:b-n6tkgi) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1392)):*
> ```PowerShell
> 
>                 Context ('When validating resource/module {0}' -f $testCase.Folder) {
>                     It 'Should use the localized string key <LocalizedKey>, from the localization resource file' -TestCases $testCases_LocalizedKeys -Skip:$skipTest_LocalizedKeys {
> ```

comma not required :grin:

I feel like I never get to give you very useful review comments :grin:
___
*[Meta.Tests.ps1, line 1400 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhWmlX5ZFFPtYSAsSP:-LdhWmlX5ZFFPtYSAsSQ:b-m423fn) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1400)):*
> ```PowerShell
>                         )
> 
>                         $usedLocalizationKeys | Should -Contain $LocalizedKey -Because 'the key exist in the localized string resource file'
> ```

the key exist -> the key exists
___
*[Meta.Tests.ps1, line 1403 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhYCB46ccLGs573N3Z:-LdhYCB46ccLGs573N3_:b-c1lh1p) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1403)):*
> ```PowerShell
>                     }
> 
>                     It 'Should not be missing the localized string key <LocalizedKey>, in the localization resource file' -TestCases $testCases_UsedLocalizedKeys -Skip:$skipTest_UsedLocalizedKeys {
> ```

...string key <LocalizedKey>, in the localization resource file -> ...string key <LocalizedKey> from the localization resource file
___
*[Meta.Tests.ps1, line 1444 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhcKuhAblZPzHl6ydg:-LdhcKuj9K83xV7S1R7R:bwv9e2f) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1444)):*
> ```PowerShell
> 
>             # Only run these tests if there are test cases to be tested.
>             if ($testCases)
> ```

Could you use:

```$skipTests = -not $testCases```

To replace the entire block?
___
*[Meta.Tests.ps1, line 1453 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-Ldhd01-BiNjso2CS-xR:-Ldhd01-BiNjso2CS-xS:b-yzwi5h) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1453)):*
> ```PowerShell
>             }
> 
>             It 'Should have localization string resource file for the resource/module <Folder> and localization folder <LocalizationFolder>' -TestCases $testCases -Skip:$skipTests {
> ```

Should have localization -> Should have a localization
___
*[Meta.Tests.ps1, line 1471 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhcnLPBzqJwkTkymnN:-LdhcnLPBzqJwkTkymnO:b-9o6qt7) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1471)):*
> ```PowerShell
>                 $localizationResourceFilePath = Join-Path -Path (Join-Path -Path $Path -ChildPath $LocalizationFolder) -ChildPath "$Folder.strings.psd1"
> 
>                 Test-Path -Path $localizationResourceFilePath | Should -BeTrue -Because ('the there must exist a string resource file in the localization folder {0}' -f $LocalizationFolder)
> ```

the there -> there
___
*[Meta.Tests.ps1, line 1474 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhcuGZ0npcGujQtsqF:-LdhcuGZ0npcGujQtsqG:b9q48o6) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1474)):*
> ```PowerShell
>             }
> 
>             It 'Should have the localization folder with the correct casing for the resource/module <Folder> and localization folder <LocalizationFolder>' -TestCases $testCases -Skip:$skipTests {
> ```

Should have the -> Should have a
___
*[Meta.Tests.ps1, line 1548 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdEcoCMjE1mJloU14:-LdhdEcoCMjE1mJloU15:b-yae3mr) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1548)):*
> ```PowerShell
>                         )
> 
>                         $localizedStrings.Keys | Should -Contain $LocalizedKey -Because 'the key exist in the en-US localization resource file'
> ```

exist -> exists
___
*[Meta.Tests.ps1, line 1551 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdUAr4hQqkeKxkEfJ:-LdhdUAt4iBIXBSV80Wu:b-eav1tm) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1551)):*
> ```PowerShell
>                     }  -ErrorVariable itBlockError
> 
>                     # If the It-block did not pass the test, output the a text explaining hwo to resolve the issue.
> ```

hwo -> how
___
*[Meta.Tests.ps1, line 1564 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdHwqDPyntJ5V4_Ol:-LdhdHwqDPyntJ5V4_Om:bnkueg5) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1564)):*
> ```PowerShell
>                     }
> 
>                     It "Should not be missing the localization string key <LocalizedKey> in the english resource file for the resource/module <Folder>" -TestCases $testCases_MissingEnglishLocalizedKeys {
> ```

in the english -> from the English
___
*[Meta.Tests.ps1, line 1580 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdMOB4bS54ax4mUAw:-LdhdMOB4bS54ax4mUAx:b-yae3mr) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1580)):*
> ```PowerShell
>                         )
> 
>                         $englishLocalizedStrings.Keys | Should -Contain $LocalizedKey -Because ('the key exist in the resource file for the location folder {0}' -f $LocalizationFolder)
> ```

exist -> exists
___
*[README.md, line 188 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhSkplAa-m-FBgAzcR:-LdhSkplAa-m-FBgAzcS:bdpwqh4) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/README.md#L188)):*
> ```Markdown
> #### Common Tests - Validating Localization
> 
> These tests validate the localization folders and files, and also so that
> ```

and also so that -> and also that
___
*[README.md, line 190 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhX1tk-f6U9woHHn7n:-LdhX1tk-f6U9woHHn7o:bvyuve5) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/README.md#L190)):*
> ```Markdown
> These tests validate the localization folders and files, and also so that
> each localization string key is used and there are no missing or extra
> localization string keys.
> ```

It might be worth mentioning that these tests will only work if the localization variable is $script:localizedData
___
*[README.md, line 194 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhTUvmCPmoEV81Wg1L:-LdhTUvmCPmoEV81Wg1M:b-sbg8hd) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/README.md#L194)):*
> ```Markdown
> - Should have an en-US localization folder.
> - The en-US localization folder should have the correct casing.
> - Should exist a resource file with the correct name in the localization folder.
> ```

See corrections in CHANGELOG.MD

**Review by johlju — COMMENTED** [review]
I have also fixed a bug that I did not see until now. I managed to resolve a lot of localization in SqlServerDsc, so when I rerun this I realized it didn't run the tests on all the files due to it filtered the AST wrong. Before it actually failed with an error, but that error was hidden within all other pester failing test errors. Now when I was expecting mostly green I didn't even see the files in the tests. :smile: 
I will re-run the ComputerManagementDsc PR too, to make sure it didn't fail with this change.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/319#-:-LdintfV4fe8Atr0A0e_:b-n7lr60)* status: 0 of 3 files reviewed, 20 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 38 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhSHQC0YCicOMabdy7:-Ldilxac1PbPOKIMno4t:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L38)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could rewrite as: Added common opt-in tests for localization
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 41 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhS_Su1FcrOpV2zG7V:-LdilyRfDLuyMxRrEMhm:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L41)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

-> A resource file  with the correct name should exist in the localization folder.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 43 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhStqe7jDTr0cX08ZT:-Ldim0Tg3_xqMA79KspV:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

string key that are used -> string key that is used
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 48 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhT28Q8DXP-B3q4zbD:-Ldim3rt1CpNtAqo1bNR:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/CHANGELOG.md#L48)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

that does not -> that do not
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1259 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhUvD26GVk1ajf8rTx:-Ldim6cH-BYyxyILWIit:b9sut5q) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1259)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Is it worth changing the `$testCases` to something more descriptive like `$foldersToTest`?
</blockquote></details>

Agree. Like more descriptive variable names. Let me know if you think anyone else should be renamed. :slightly_smiling_face: 
___
*[Meta.Tests.ps1, line 1321 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhUVfXCYtfaZV2KP6_:-LdimJ2l2A0P-yYlskxO:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1321)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

the there must -> there must
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1330 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhVXy37JuT0_8GjRkJ:-LdimJgb7kb6PZOaxe1L:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1330)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs space after =
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1392 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhYk9a03T5yq5gruPh:-LdimLAW4lL7K6iLOJqq:biepalv) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1392)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

comma not required :grin:

I feel like I never get to give you very useful review comments :grin:
</blockquote></details>

Done. These was all great comment! All of them making the PR better :grin: 
___
*[Meta.Tests.ps1, line 1400 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhWmlX5ZFFPtYSAsSP:-LdimVzFBTCxJI0zY_va:byjsff0) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1400)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

the key exist -> the key exists
</blockquote></details>

Done. Also improved some of these texts so they read better when Pester output them.
___
*[Meta.Tests.ps1, line 1403 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhYCB46ccLGs573N3Z:-LdinVyn1ZMffIUW-d7t:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1403)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

...string key <LocalizedKey>, in the localization resource file -> ...string key <LocalizedKey> from the localization resource file
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1444 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhcKuhAblZPzHl6ydg:-LdinXUxBj_MIdbq2QWd:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1444)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you use:

```$skipTests = -not $testCases```

To replace the entire block?
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1453 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-Ldhd01-BiNjso2CS-xR:-LdinYmOEao6sGkHR0OY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1453)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should have localization -> Should have a localization
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1471 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhcnLPBzqJwkTkymnN:-Ldin_0y5w0s1j2R8fYc:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1471)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

the there -> there
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1474 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhcuGZ0npcGujQtsqF:-Ldina7t1k2lq2tHw9TY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1474)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should have the -> Should have a
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1548 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdEcoCMjE1mJloU14:-LdindrZ7elwl97X2qfN:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1548)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

exist -> exists
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1551 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdUAr4hQqkeKxkEfJ:-LdinfVa9E5YQkugrNhF:b-f554su) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1551)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

hwo -> how
</blockquote></details>

Done. Strange that the spelling extension did not caught this typo. :thinking: 
___
*[Meta.Tests.ps1, line 1564 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdHwqDPyntJ5V4_Ol:-LdinocFAGFeMT3Oi8Lb:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1564)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

in the english -> from the English
</blockquote></details>

Done.
___
*[Meta.Tests.ps1, line 1580 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdMOB4bS54ax4mUAw:-LdinpUCCm4nVX4u-INF:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1580)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

exist -> exists
</blockquote></details>

Done.
___
*[README.md, line 188 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhSkplAa-m-FBgAzcR:-LdinqTS9LDQ8uhQMN9u:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/README.md#L188)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

and also so that -> and also that
</blockquote></details>

Done.
___
*[README.md, line 190 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhX1tk-f6U9woHHn7n:-Ldinr6JEXUayBaSHR1S:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/README.md#L190)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

It might be worth mentioning that these tests will only work if the localization variable is $script:localizedData
</blockquote></details>

Done.
___
*[README.md, line 194 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhTUvmCPmoEV81Wg1L:-Ldinrc445ptw1ZDptdM:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/README.md#L194)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See corrections in CHANGELOG.MD
</blockquote></details>

Done.

**Comment by johlju** [comment]
Tests passing for PR in ComputerManagementDsc:  https://ci.appveyor.com/project/PowerShell/computermanagementdsc/builds/24208335?fullLog=true#L916

**Comment by johlju** [comment]
Tests for SqlServerDsc correctly tests all files (that exist), and correctly fails on tests (as far as I can see).
https://ci.appveyor.com/project/johlju/sqlserverdsc/builds/24208427/job/7ymkt1lflidt8co7?fullLog=true#L2183

**Comment by johlju** [comment]
I think these tests will be really helpful! Hopefully they are verbose enough for new contributors to understand how to resolve the errors. They are very helpful for me! 😄

**Review by PlagueHO — APPROVED** [review]
Awesome! Very keen to get this in and start using it.

:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/319#-:-Ldzi-hr5p1qVszRShXL:b2clyfo)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Meta.Tests.ps1, line 1551 at r3](https://reviewable.io/reviews/powershell/dscresource.tests/319#-LdhdUAr4hQqkeKxkEfJ:-LdzhiJg5zW6MttllTQH:bb71fg7) ([raw file](https://github.com/powershell/dscresource.tests/blob/ea718ad298e61e521e4eb05842d1e3e6e0b71e3b/Meta.Tests.ps1#L1551)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Strange that the spelling extension did not caught this typo. :thinking: 
</blockquote></details>

Odd!

**Pull request merged**
