### PR TITLE
Update calls to Install-Module in AppVeyor.psm1 to use AllowClobber.

### LINKED ISSUE #310: Continuous Integration Setup Periodically Fails With: Install-Package : A command with name 'Find-Package' is already available on this system
#### Details of the scenario you tried and the problem that is occurring
I've noticed a handful of times in the past week where AppVeyor based test jobs fail almost immediately due to trying to import a cmdlet that has already been imported. Generally just resubmitting the job is enough to get it to work. This appears to be a transient issue of some sort.

#### Verbose logs showing the problem
From [this](https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/builds/22146629/job/7ju3n2ftu8t5gyp7):
```
[00:00:00] Build started
[00:00:00] git clone -q https://github.com/PowerShell/xPSDesiredStateConfiguration.git C:\projects\xpsdesiredstateconfiguration
[00:00:02] git fetch -q origin +refs/pull/526/merge:
[00:00:03] git checkout -qf FETCH_HEAD
[00:00:03] Running Install scripts
[00:00:03] git clone https://github.com/PowerShell/DscResource.Tests
[00:00:03] Cloning into 'DscResource.Tests'...
[00:00:04] $moduleName = 'xPSDesiredStateConfiguration'
[00:00:04] Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
[00:00:04] Invoke-AppveyorInstallTask
[00:00:04] 
[00:00:04] [Build Info] [UTC 02/05/2019 19:51:33] Installing the latest NuGet package provider.
[00:00:06] 
[00:00:06] Name  ProviderName Version  
[00:00:06] ----  ------------ -------  
[00:00:06] NuGet NuGet        2.8.5.208
[00:00:06] 
[00:00:06] 
[00:00:06] [Build Info] [UTC 02/05/2019 19:51:35] Installing the latest PowerShellGet from the PowerShell Gallery.
[00:00:14] PackageManagement\Install-Package : A command with name 'Find-Package' is already available on this system. This module 'PackageManagement' may override the existing commands. If you still want to install this module 
[00:00:14] 'PackageManagement', use -AllowClobber parameter.
[00:00:14] At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
[00:00:14] + ...          $null = PackageManagement\Install-Package @PSBoundParameters
[00:00:14] +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:00:14]     + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
[00:00:14]     + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
[00:00:14]  
[00:00:14] [Build Info] [UTC 02/05/2019 19:51:43] Installing nuget.exe to enable package creation.
```

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Update calls to Install-Module in AppVeyor.psm1 to use AllowClobber.

#### This Pull Request (PR) fixes the following issues
- Fixes #310 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/311)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/311)* status: all files reviewed, 3 unresolved discussions (waiting on @mhendric)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_u1T482Oqqib_O9N:-LYS_u1T482Oqqib_O9O:b-tgpjcd) (no related file):*
Can you please do a test run using this branch (for example for xPSDesiredStateConfiguration) so we can see that it works.

---
___
*[AppVeyor.psm1, line 75 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_alJ-_P7qZfV1RWn:-LYS_alJ-_P7qZfV1RWo:b-hojo4y) ([raw file](https://github.com/powershell/dscresource.tests/blob/6519a164a192f2fa85415257f1b4c0c02b3618f0/AppVeyor.psm1#L75)):*
> ```PowerShell
>     }
> 
>     $installPesterParameters.Add('AllowClobber', $true)
> ```

Maybe we should not add this unless we see a problem with this later? Adding this might give other problems?
___
*[README.md, line 759 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_Q0M5l1rYR46EJM8:-LYS_Q0M5l1rYR46EJM9:b-cowsdc) ([raw file](https://github.com/powershell/dscresource.tests/blob/6519a164a192f2fa85415257f1b4c0c02b3618f0/README.md#L759)):*
> ```Markdown
> > as the end-of-line (eol) characters.
> 
> ```plaintext
> ```

This was part of the quote, maybe just rewrite to remove the quote altogether since we must always do this?

**Review by mhendric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/311)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju and @mhendric)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_u1T482Oqqib_O9N:-LYSbkPP7NvtUGw8917H:b-eqwn8h) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can you please do a test run using this branch (for example for xPSDesiredStateConfiguration) so we can see that it works.
</blockquote></details>

Will do. Got any tips on the best way to test this though? I do have my AppVeyor setup to build xPSDesiredStateConfiguration. What would be the easiest way to update a xPSDesiredStateConfiguration branch to clone this particular branch of DscResource.Tests?

---
___
*[AppVeyor.psm1, line 75 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_alJ-_P7qZfV1RWn:-LYSbwjM4vp34JhAZgOf:batx4gr) ([raw file](https://github.com/powershell/dscresource.tests/blob/6519a164a192f2fa85415257f1b4c0c02b3618f0/AppVeyor.psm1#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we should not add this unless we see a problem with this later? Adding this might give other problems?
</blockquote></details>

Works for me. Will update.
___
*[README.md, line 759 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_Q0M5l1rYR46EJM8:-LYSc9gI8kYsxYAW0dee:bcuyz1y) ([raw file](https://github.com/powershell/dscresource.tests/blob/6519a164a192f2fa85415257f1b4c0c02b3618f0/README.md#L759)):*
Just to make sure I'm clear, are you suggesting removing the entire block quoted below?
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> > **Note:** There was a problem running `Test-ScriptFileInfo` on the AppVeyor
> > build worker, because the build worker has the setting `core.autocrlf=input`
> > which result in the files checked out only have LF as as the end-of-line (eol)
> > character.
> > `Test-ScriptFileInfo` is unable to parse the files with just LF. To solve this,
> > the best option is to add a `.gitattributes` file to the root of the repository,
> > with the following content. This will always make git checkout files with CRLF
> > as the end-of-line (eol) characters.
>  
> ```
</details>
plaintext
> * text eol=crlf
> ```

**Review by mhendric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/311)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @johlju and @mhendric)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_u1T482Oqqib_O9N:-LYSj7P61OzOUSnthOM2:b-3nqpo) (no related file):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Will do. Got any tips on the best way to test this though? I do have my AppVeyor setup to build xPSDesiredStateConfiguration. What would be the easiest way to update a xPSDesiredStateConfiguration branch to clone this particular branch of DscResource.Tests?
</blockquote></details>

I think I figured out how to do this. I'll just update the AppVeyor.yml, and any other calls to git clone to clone my branch/fork specifically.

---
___
*[AppVeyor.psm1, line 75 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_alJ-_P7qZfV1RWn:-LYSj5YL732E8kkvf9Bm:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/6519a164a192f2fa85415257f1b4c0c02b3618f0/AppVeyor.psm1#L75)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Works for me. Will update.
</blockquote></details>

Done.

**Comment by mhendric** [comment]
Testing looks good to me:

Branch:
https://github.com/mhendric/xPSDesiredStateConfiguration/tree/TestTests

Test Results:
https://ci.appveyor.com/project/mhendric/xpsdesiredstateconfiguration/builds/22284997

**Review by PlagueHO — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/311)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju and @mhendric)

*[a discussion](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_u1T482Oqqib_O9N:-LYf4Q_-A-LtNH5SkG7j:bnfp4nl) (no related file):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

I think I figured out how to do this. I'll just update the AppVeyor.yml, and any other calls to git clone to clone my branch/fork specifically.
</blockquote></details>

:lgtm:

---
___
*[README.md, line 759 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/311#-LYS_Q0M5l1rYR46EJM8:-LYf4KMSCy7Vg_-B8rR1:b-4rvy49) ([raw file](https://github.com/powershell/dscresource.tests/blob/6519a164a192f2fa85415257f1b4c0c02b3618f0/README.md#L759)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Just to make sure I'm clear, are you suggesting removing the entire block quoted below?

> ```
> > **Note:** There was a problem running `Test-ScriptFileInfo` on the AppVeyor
> > build worker, because the build worker has the setting `core.autocrlf=input`
> > which result in the files checked out only have LF as as the end-of-line (eol)
> > character.
> > `Test-ScriptFileInfo` is unable to parse the files with just LF. To solve this,
> > the best option is to add a `.gitattributes` file to the root of the repository,
> > with the following content. This will always make git checkout files with CRLF
> > as the end-of-line (eol) characters.
>  
> ```plaintext
> * text eol=crlf
> ```
</blockquote></details>

I think what you've done here looks right.

**Pull request merged**
