### PR TITLE
Add opt-Ins flags to enable failing PSSA tests to fail build - Fixes #161

### LINKED ISSUE #161: Enable Opting In to Failing on Required and Flagged PSSA Rules
Currently DSCResource.Tests ignores any PSSA required or flagged rules because:
| Automatically passing this test since it may break several resource modules at the moment. Automatic pass to be removed Jan-Feb 2017.

This was obviously meant to be removed in Jan-Feb 2017 but has not been.

What I propose is that we add some more Opt in settings:
Common Tests - Required Script Analyzer Rules
Common Tests - Flagged Script Analyzer Rules

If these are set then we skip this line:
https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L377

or this line:
https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L401

I noticed this when implementing #86 (custom PSSA rules for validating style guidelines). We'll need the ability to opt in to these custom PSSA rules as many resources will contain lots of violations - and we'll want these to be just notifications until a resource opts-in.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds 4 new opt-in flags for enabling failing the build if PSSA rules fail. See #161.

It should only affect a repo once it has opted-in with the new flags. Otherwise the behavior won't change except for the message saying how to enable the flag (see screenshot below).

Details:

* Added Get-OptInStatus function to enable retrieving of an opt-in status
  by name. This is required for implementation of PSSA opt-in rules where
  the describe block contains multiple opt-ins in a single block.
* Added new opt-in flags to allow enforcement of script analyzer rules ([issue #161](https://github.com/PowerShell/DscResource.Tests/issues/161))
* Updated year in DscResources.Tests.psd1 manifest to 2018.

The following opt-in flags have been specified:

* **Common Tests - Required Script Analyzer Rules**: fail tests if any required
  script analyzer rules are violated.
* **Common Tests - Flagged Script Analyzer Rules**: fail tests if any flagged
  script analyzer rules are violated.
* **Common Tests - New Error-Level Script Analyzer Rules**: fail tests if any
  new error-level script analyzer rules are violated.
* **Common Tests - Custom Script Analyzer Rules**: fail tests if any
  custom script analyzer rules are violated.

This is what you'll see when you haven't opted-in to these PSSA tests but they are violated:
image

This is what you'll see when you opt-in to the PSSA custom flag but fail a custom rule test:
image

I've tested this with the following repos using the specified conditions (click the links to jump to the AppVeyor results):

* xNetworking - [No opt-ins, with no failed tests](https://ci.appveyor.com/project/PlagueHO/xnetworking/build/3.1.766.0?fullLog=true#L4618)
* xNetworking - [No opt-ins, with a failed PSSA test](https://ci.appveyor.com/project/PlagueHO/xnetworking/build/3.1.769.0?fullLog=true#L4795)
* xNetworking - [All opt-ins enabled, with no failed tests](https://ci.appveyor.com/project/PlagueHO/xnetworking/build/3.1.767.0?fullLog=true#L4671)
* xNetworking - [All opt-ins enabled, with a failed PSSA test](https://ci.appveyor.com/project/PlagueHO/xnetworking/build/3.1.768.0?fullLog=true#L4786)
* SQLServerDsc - [No opt-ins, with failed PSSA tests](https://ci.appveyor.com/project/PlagueHO/sqlserverdsc/build/9.0.1.0?fullLog=true#L889)
* SQLServerDsc - [All opt-ins enabled, with a failed PSSA test](https://ci.appveyor.com/project/PlagueHO/sqlserverdsc/build/9.0.2.0?fullLog=true#L889)
* xActiveDirectory - [No opt-ins, with failed PSSA tests](https://ci.appveyor.com/project/PlagueHO/xactivedirectory/build/2.16.39.0?fullLog=true#L377)
* xActiveDirectory - [All opt-ins enabled, with a failed PSSA test](https://ci.appveyor.com/project/PlagueHO/xactivedirectory/build/2.16.40.0?fullLog=true#L386)

@johlju - would you mind reviewing this for me?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/215)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8gziJQ1ht9XJHOXAPP:-L8gziJQ1ht9XJHOXAPQ:b-52uqql) (no related file):*
Minor: For cleaner commit history, could you rebase with interactive to remove the 'merge...dev' commits? :)

---

*[Meta.Tests.ps1, line 466 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8h0AvRCS8ySHDgEeQj:-L8h0AvRCS8ySHDgEeQk:behha6x) ([raw file](https://github.com/powershell/dscresource.tests/blob/2c30595c5c47abc1e0d32ea0b36053fe115243d1/Meta.Tests.ps1#L466)):*
> test there were no violations

Maybe 'test that there...' ? Throughout if so.

---

*[TestHelper.psm1, line 930 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8h-M4M-B1bu6XwOQ8K:-L8h-M4M-B1bu6XwOQ8L:bc7olyo) ([raw file](https://github.com/powershell/dscresource.tests/blob/2c30595c5c47abc1e0d32ea0b36053fe115243d1/TestHelper.psm1#L930)):*
> with named.

Named what? :thinking: :smile: 

---

*[TestHelper.psm1, line 953 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8h0oKQ6jHP3oyrEUhl:-L8h0oKQ6jHP3oyrEUhm:b-2eqmc1) ([raw file](https://github.com/powershell/dscresource.tests/blob/2c30595c5c47abc1e0d32ea0b36053fe115243d1/TestHelper.psm1#L953)):*
> ```PowerShell
> 
>     $optIn = $OptIns -icontains $Name
>     if(!$optIn)
> ```

Maybe use `-not`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215)*

**Comment by johlju** [comment]
@PlagueHO Maybe do a test run using "No opt-ins enabled, with a failed PSSA test"? Was looking for the output of that, just to verify.

**Comment by PlagueHO** [comment]
Thanks @johlju - I've made the changes as required. I'll add the new test run (No opt-ins enabled, with a failed PSSA test) into the main PR comment with the others. I'm using xNetworking for this as I'd already got output of that test for SQLServerDsc and xActiveDirectory (both have failing PSSA tests - so the no-optin covers that). I've also added the output of the SQLServerDsc and xActiveDirectory as well (because it completed :grin: )

---

Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Meta.Tests.ps1, line 466 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8h0AvRCS8ySHDgEeQj:-L8kIKIm8cvxlF2l_kEb:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/1f54a5b9d2c551e6775ce934cfa8b5b24fa50831/Meta.Tests.ps1#L466)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> test there were no violations

Maybe 'test that there...' ? Throughout if so.
</blockquote></details>

Done.

---

*[TestHelper.psm1, line 930 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8h-M4M-B1bu6XwOQ8K:-L8kI_gu88TJh-1H8YNC:b-v9nrto) ([raw file](https://github.com/powershell/dscresource.tests/blob/1f54a5b9d2c551e6775ce934cfa8b5b24fa50831/TestHelper.psm1#L930)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> with named.

Named what? :thinking: :smile: 
</blockquote></details>

Hehe. Good catch. Done!

---

*[TestHelper.psm1, line 953 at r1](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8h0oKQ6jHP3oyrEUhl:-L8kIuT91zYuH7LDktag:b-ut0qh3) ([raw file](https://github.com/powershell/dscresource.tests/blob/1f54a5b9d2c551e6775ce934cfa8b5b24fa50831/TestHelper.psm1#L953)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe use `-not`?
</blockquote></details>

Done. I also corrected throughout the file (and then ended up correcting the style in the functions I corrected it in).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-:-L8kJt6JEAee1aZ_Vhzv:bicia66)*

**Comment by PlagueHO** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8gziJQ1ht9XJHOXAPP:-L8kKVU-E_LOElzXfMEq:boqlxor) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: For cleaner commit history, could you rebase with interactive to remove the 'merge...dev' commits? :)
</blockquote></details>

Good point. Struggling with this a bit because the merge...dev commits aren't showing up in the interactive rebase. Not sure why - might have to refork and recreate the branch and the PR. Happy to do this if you want - it'll mean the PR needs to go through again though...

Anyway, I'll have a bit more of a look around and see if I can figure out why I've got all these merges.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215)*

**Comment by PlagueHO** [comment]
@johlju - I fixed up the commit log now (I wasn't paying attention and was rebasing against my fork of the Dev branch instead of the upstream - doh!).

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Meta.Tests.ps1, line 492 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8lbGZ6DoyKD512vMId:-L8lbGZ6DoyKD512vMIe:btbf51o) ([raw file](https://github.com/powershell/dscresource.tests/blob/761d174a862b20d378caff03d15733611aa83ada/Meta.Tests.ps1#L492)):*
> there there

that there

---

*[TestHelper.psm1, line 953 at r2](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-L8lbats2crej4Amq41o:-L8lbats2crej4Amq41p:b-syidqr) ([raw file](https://github.com/powershell/dscresource.tests/blob/761d174a862b20d378caff03d15733611aa83ada/TestHelper.psm1#L953)):*
> if(

Space between if and parenthesis. Throughout. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215)*

**Comment by johlju** [comment]
@PlagueHO commit history looks great now! 😄

**Comment by johlju** [comment]
:lgtm:

@kwirkykat when you have time can you merge this PR if it looks okay to you.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/215#-:-L8q2kDz0aMZHH2-4fNK:bub4mkp)*

**Comment by kwirkykat** [comment]
@PlagueHO @johlju This broke the common tests: https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/build/6.0.1037.0?fullLog=true

**Comment by johlju** [comment]
@kwirkykat found the problem - fails when a repo does not have any entry in the .MetaTestOptIn.json. Looking for a solution.

**Comment by kwirkykat** [comment]
@johlju Thanks! 🙂

**Comment by PlagueHO** [comment]
Oh no - thanks for catching this @kwirkykat - and thanks for resolving @johlju !

**Pull request merged**
