### PR TITLE
DscResource.Tests repository can analyze code coverage for the helper modules - Fixes #208

### LINKED ISSUE #208: Code coverage does not analyze code in all module files in this repository
Currently when this repository is tested, the code coverage is only reported for the module files in the root folder.
Thats because the following code block does not add more than the modules in the root folder. 

https://github.com/PowerShell/DscResource.Tests/blob/f9e3dfd3eb9d7b6a9225e2cfba68b79ffe1cab36/AppVeyor.psm1#L250-L268

Suggest we use the helper function `Test-IsRepositoryDscResourceTests` to see if we are testing this repository, and if so, add all the module files (.psm1) under sub folders as well. So we can get code coverage for all the helper modules like DscResource.AnalyzerRules, DscResource.CodeCoverage and DscResource.DocumentationHelper.

### PR DESCRIPTION
**Pull request by johlju**
- Added more tests for custom Script Analazyer rules to increased code coverage.
  These new tests call the Measure-functions directly.
- Changed so that DscResource.Tests repository can analyze code coverage for the
  helper modules (issue #208).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/209)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO would you mind doing the review on this one too? 😄

**Comment by PlagueHO** [comment]
Wow! That is some epic testing there! Fantastic work! Tiniest grammatical issues it comments, but logic and code is fantastic as usual.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 18 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L4j9RvK7qWCGRlcahXc:-L4j9RvK7qWCGRlcahXd:b-hlelzj) ([raw file](https://github.com/powershell/dscresource.tests/blob/c5ae5aeebe8dff32797b76f6b87a55a6b8caee76/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L18)):*
>  Helper function to return an Ast objects, ->  Helper function to return Ast objects,

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L4j9XUnAal1JklKPCCp:-L4j9XUnAal1JklKPCCq:b-ykcxct) ([raw file](https://github.com/powershell/dscresource.tests/blob/c5ae5aeebe8dff32797b76f6b87a55a6b8caee76/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L19)):*
> ```PowerShell
>     .SYNOPSIS
>         Helper function to return an Ast objects,
>         to be able to test custom rules
> ```

Needs full stop.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 80 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L4jATb_B0Rg3GFoRzpz:-L4jATb_B0Rg3GFoRzq-:bzbx04v) ([raw file](https://github.com/powershell/dscresource.tests/blob/c5ae5aeebe8dff32797b76f6b87a55a6b8caee76/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L80)):*
> ```PowerShell
>                 $record = Measure-ParameterBlockParameterAttribute -ParameterAst $mockAst[0]
>                 ($record | Measure-Object).Count | Should Be 1
>                 $record.Message | Should Be $localizedData.ParameterBlockParameterAttributeMissing
> ```

I'll ignore the Pester V3 formatting in this file as I've raised as something to fix in a separate issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-:-L4jDTvnVFovHHCl5bgk:bnmw0oi)*

**Comment by johlju** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 18 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L4j9RvK7qWCGRlcahXc:-L4kzFDw8Fck-iUWavo8:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c5ae5aeebe8dff32797b76f6b87a55a6b8caee76/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L18)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

>  Helper function to return an Ast objects, ->  Helper function to return Ast objects,
</blockquote></details>

Done.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L4j9XUnAal1JklKPCCp:-L4kzGko6lG1jaGDzmFk:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/c5ae5aeebe8dff32797b76f6b87a55a6b8caee76/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L19)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Needs full stop.
</blockquote></details>

Done.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 80 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L4jATb_B0Rg3GFoRzpz:-L4kzVZwBw6vG5ZSjSEy:b3jaojr) ([raw file](https://github.com/powershell/dscresource.tests/blob/c5ae5aeebe8dff32797b76f6b87a55a6b8caee76/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L80)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'll ignore the Pester V3 formatting in this file as I've raised as something to fix in a separate issue.
</blockquote></details>

Yes, I ignored it too, was my thought as well to do that in a separate issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/209)*

**Comment by johlju** [comment]
@PlagueHO when you have time, could you look over this PR again? I had to make some changes because of newly merged PR's.

**Comment by PlagueHO** [comment]
Just non-blocking nitpick.

:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[AppVeyor.psm1, line 238 at r3](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-L8Q8jyLYV8DJOfkMQSA:-L8Q8jyNguDW40l72FRn:b-tn3dou) ([raw file](https://github.com/powershell/dscresource.tests/blob/5e7a7d0a5ef8ec2df7dd1f621f4505137f35a08a/AppVeyor.psm1#L238)):*
> ```PowerShell
>                 }
>             }
>             
> ```

Trim spaces? Non-blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/209#-:-L8Q99hDrFXXdrNSbkl0:bhh4la4)*

**Comment by johlju** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[AppVeyor.psm1, line 238 at r3](https://beta.reviewable.io/reviews/powershell/dscresource.tests/209#-L8Q8jyLYV8DJOfkMQSA:-L8T4rwv2Pg4qOIe7Phk:both5h4) ([raw file](https://github.com/powershell/dscresource.tests/blob/5e7a7d0a5ef8ec2df7dd1f621f4505137f35a08a/AppVeyor.psm1#L238)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Trim spaces? Non-blocking.
</blockquote></details>

Done. Used another computer to edit this. Apparently I hadn't added the correct VS Code settings.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/209)*

**Comment by PlagueHO** [comment]
:lgtm:

@KwirkyKat - are you able to merge if you're happy. Thanks @Johlju

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/209#-:-L8Vw66F5GNDmIhJ2kIX:b2ys7o2)*

**Comment by PlagueHO** [comment]
@johlju - onto this now! Sorry for taking so long :cry:

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresource.tests/209#-:-LAftEUY0uugywTDWgXJ:bnfp4nl)*

**Comment by johlju** [comment]
@PlagueHO No worries! I know how busy you been lately! Thanks for taking the time! 😃

**Pull request merged**
