### PR TITLE
Added function for checking lower case format for all keywords

### PR DESCRIPTION
**Pull request by SSvilen**
#### Pull Request (PR) description
I have allowed myself creating a new PSScriptAnalyzer function, which checks if all PowerShell keywords are in lower case.  
I saw that there are checks for the most used keywords, but I decided to do one for all keywords. 
Let me know what you think. 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Unit tests added/updated.
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346)

### CODE REVIEW

**Comment by johlju** [comment]
I will help review this as soon as possible, but will be later in the week.

**Comment by johlju** [comment]
Awesome job @SSvilen! 😃

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346)* status: all files reviewed, 8 unresolved discussions (waiting on @SSvilen)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 38 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvJFIoAiJYVaj7Y9CR:-LnvJFIq47ezEI98_IN0:b-f117wp) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L38)):*
> ```PowerShell
>         None
> #>
> function Measure-ParameterBlockParameterAttribute {
> ```

It looks like your VS Code is configured to use a different format for the brace style. Are you able to change back to having all the open braces on the line following? https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 917 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvKMUA1uFW_BGbBIF9:-LnvKMUA1uFW_BGbBIFA:b-11moxx) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L917)):*
> ```PowerShell
>         $script:diagnosticRecord['RuleName'] = $PSCmdlet.MyInvocation.InvocationName
> 
>         $upperCaseTokens = $Token.Where( { $_.TokenFlags.HasFlag([System.Management.Automation.Language.TokenFlags]::Keyword) -and
> ```

Are you able to reduce the line length of this line to under around 100 chars to prevent wrapping?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 67 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvK_dn83bUxUFcHYJH:-LnvK_dn83bUxUFcHYJI:b2f7koz) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L67)):*
> ```PowerShell
>     .PARAMETER ScriptDefinition
>         The script definition to return ast for.
> ```

Can you remove this blank line?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3297 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLc3T51R5RP-cMCV1:-LnvLc3UDeAKfHa2DOfy:bv4cdmn) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3297)):*
> ```PowerShell
> 
> Describe 'Measure-Keyword' {
>     Context "When calling the function directly" {
> ```

Can you use single quotes around this string?
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3302 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLejT4hLs-VxTTdFt:-LnvLejVD9A16zdUtiQY:b-ssw2r3) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3302)):*
> ```PowerShell
>         }
> 
>         Context "When function definition contains upper case letters" {
> ```

Can you use single quotes around this string?

Nitpick: You could say" When keyword contains upper case letters" for the context because technically the test is assessing if a keyword contains uppercase. But just a nitpick.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3302 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvM0ou8my7FlUw_QAp:-LnvM0ou8my7FlUw_QAq:b-k98wts) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3302)):*
> ```PowerShell
>         }
> 
>         Context "When function definition contains upper case letters" {
> ```

Can you also add a negative test? E.g. When the function does not contain upper case letter.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3303 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLfMoCOGp4crC8UQM:-LnvLfMoCOGp4crC8UQN:br9ax97) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3303)):*
> ```PowerShell
> 
>         Context "When function definition contains upper case letters" {
>             It "Should write the correct error record" {
> ```

Can you use single quotes around this string? And throughout.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3326 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLmJFAMy73AzJbhCq:-LnvLmJFAMy73AzJbhCr:b-10emr9) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3326)):*
> ```PowerShell
>             }
>             $ruleName = "$($script:ModuleName)\Measure-Keyword"
>         }
> ```

Can you add a blank line after this one?

**Review by SSvilen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @PlagueHO)

___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 38 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvJFIoAiJYVaj7Y9CR:-Lo1cvhZ8VLn-Kh_KVp-:bnnsw56) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L38)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

It looks like your VS Code is configured to use a different format for the brace style. Are you able to change back to having all the open braces on the line following? https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces
</blockquote></details>

I had a settings.json at the begging for that and deleted it at some point and then had to re-design the check and forgot to add it.. I've created it now and will do commit it - just to avoid that in the future.  let me know if this is ok.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 917 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvKMUA1uFW_BGbBIF9:-Lo1f-d49NVQYom4SAhD:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L917)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Are you able to reduce the line length of this line to under around 100 chars to prevent wrapping?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 67 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvK_dn83bUxUFcHYJH:-Lo1fAF11tAAJ-AzJ3U_:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L67)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this blank line?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3297 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLc3T51R5RP-cMCV1:-Lo1f_9n4llhKB_xDjjA:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3297)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes around this string?
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3302 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLejT4hLs-VxTTdFt:-Lo1fnbc9y32uViW9qtJ:b-95txdl) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3302)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes around this string?

Nitpick: You could say" When keyword contains upper case letters" for the context because technically the test is assessing if a keyword contains uppercase. But just a nitpick.
</blockquote></details>


Done
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3302 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvM0ou8my7FlUw_QAp:-Lo1hb0kDh0yQMGRPVIt:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3302)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also add a negative test? E.g. When the function does not contain upper case letter.
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3303 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLfMoCOGp4crC8UQM:-Lo1hc1M-EJCdFR7zbJY:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3303)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use single quotes around this string? And throughout.
</blockquote></details>

Done.
___
*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 3326 at r1](https://reviewable.io/reviews/powershell/dscresource.tests/346#-LnvLmJFAMy73AzJbhCq:-Lo1hnQFC6lrCgVqirq_:b-nhmqqf) ([raw file](https://github.com/powershell/dscresource.tests/blob/4e837a8e9a8a8bb8d5a5e35efe20a510d3080593/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L3326)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done. May be I can create a check for that too.. I have that way too often in my PRs :)

**Review by PlagueHO — CHANGES_REQUESTED** [review]
This is looking really good @SSvilen - one thing I'm going to suggest we do is run some of the HQRM repos against your branch here and see how many of them start failing the builds due to violating these new tests. @Johlju - would you be able to run SqlServerDsc and ActiveDirectoryDsc? I'll do my repos + SharePointDsc

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346#-:-Lo7ieajDhSg5aOgmGSf:b2f6ejg)* status: all files reviewed, 3 unresolved discussions (waiting on @SSvilen)

___
*[.vscode/settings.json, line 3 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/346#-Lo7hnEK0hI3VDZ_HOu9:-Lo7hnEL5klKrqvUIOVW:b-qidn7n) ([raw file](https://github.com/powershell/dscresource.tests/blob/4eabe4edf58266eb435b1abf287b7d342c4763f8/.vscode/settings.json#L3)):*
> ```JSON
> {
>     "powershell.codeFormatting.preset": "Allman"
> }
> ```

Do you want to grab the .VSCode settings from the DSCResources.Template repo instead: https://github.com/PowerShell/DscResource.Template/tree/master/.vscode
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1040 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/346#-Lo7iQw_7DzEqNZ6PS48:-Lo7iQw_7DzEqNZ6PS49:bfi0cle) ([raw file](https://github.com/powershell/dscresource.tests/blob/4eabe4edf58266eb435b1abf287b7d342c4763f8/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1040)):*
> ```PowerShell
>         $keywordFlag = [System.Management.Automation.Language.TokenFlags]::Keyword
>         $upperCaseTokens = $Token.Where( { $_.TokenFlags.HasFlag($keywordFlag) -and $_.Text -cmatch '[A-Z]+' })
>         foreach ($item in $upperCaseTokens)
> ```

Minor nitpick - can you add a blank line before this one?
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1046 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/346#-Lo7iUIt0TM93YjJhpiI:-Lo7iUIuDlc2CDpFCdYv:b2f7koz) ([raw file](https://github.com/powershell/dscresource.tests/blob/4eabe4edf58266eb435b1abf287b7d342c4763f8/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1046)):*
> ```PowerShell
>             $script:diagnosticRecord -as $diagnosticRecordType
>         } #if
> ```

Can you remove this blank line?

**Comment by johlju** [comment]
@PlagueHO yes I can test those repos against this branch, think I do xWebAdministration too. Will report back during he day. :)

**Review by PlagueHO — COMMENTED** [review]
Cool! Thanks @Johlju

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346#-:-Lo8tFdL2RSWdqD4nFas:bzgn7ka)* status: all files reviewed, 3 unresolved discussions (waiting on @SSvilen)

**Comment by johlju** [comment]
@SSvilen Thank you for this PR! This has already help me in my maintainer role! Keep these rules coming, please! 😄 

**I will resolve the below failing repos as soon as this PR is merged.**

- [x] ActiveDirectoryDsc: **Passed**
- [x] ActiveDirectoryCSDsc: **Fixed**
- [x] CertificateDsc: **Passed**
- [x] ComputerManagementDsc: **Fixed**
- [x] DFSDsc: **Passed**
- [x] FileContentDsc: **Passed**
- [x] FSRMDsc: **Fixed**
- [x] iSCSIDsc: **Fixed**
- [x] NetworkingDsc: **Fixed**
- [x] SecurityPolicyDsc: **Needs fixing** - PR Raised - Merged
- [x] SqlServerDsc: **Needs fixing** - PR Raised - Merged
- [x] StorageDsc: **Passed**
- [x] WmiNamespaceSecurityDsc: **Untestable due to Class Based resources**
- [x] WSManDsc: **Passed**
- [x] xBitlocker: **Passed**
- [x] xExchange: **Needs fixing** - PR Raised by @SSvilen - Merged
- [x] xFailOverCluster: **Passed** - Not opted in.
- [x] xPSDesiredStateConfiguration: **Fixed**
- [x] xWebAdministration: **Passed**

All others are not opted into `Common Tests - Custom Script Analyzer Rules`.

**Review by SSvilen — COMMENTED** [review]
All should be good know. I'm glad that my rule helps! It's my very first one.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346#-:-LoAxnvT3O7tb-lv4kUv:bvf7w2c)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[.vscode/settings.json, line 3 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/346#-Lo7hnEK0hI3VDZ_HOu9:-LoAxBca3rH1JXhWclEo:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4eabe4edf58266eb435b1abf287b7d342c4763f8/.vscode/settings.json#L3)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Do you want to grab the .VSCode settings from the DSCResources.Template repo instead: https://github.com/PowerShell/DscResource.Template/tree/master/.vscode
</blockquote></details>

Done.
___
*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 1046 at r2](https://reviewable.io/reviews/powershell/dscresource.tests/346#-Lo7iUIt0TM93YjJhpiI:-LoAxl768XQ-Ayf1AQmV:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/4eabe4edf58266eb435b1abf287b7d342c4763f8/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L1046)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this blank line?
</blockquote></details>

Done.

**Review by SSvilen — COMMENTED** [review]
> know
*now.

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346#-:-LoAyMQuDF0oaoP2ZIno:bsl8ciy)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

**Comment by johlju** [comment]
Created a script to loop through all repos https://gist.github.com/johlju/411dcea4703d2b6e47230661e1d00bad

In progress running through all repos. WIll update list above accordingly.

**Comment by johlju** [comment]
All the repos have been tested. The list have been updated. I didn't bother enter those that passed. I just added SharePointDsc as that one is a bit important.

@PlagueHO If you merge this PR tonight (my time) I will start fixing all repos tomorrow. I rather have this PR merged so I know I don't miss any change when I merged a PR in the other repos.

/cc @gaelcolas

**Comment by PlagueHO** [comment]
@johlju - I ran my [DSCResource.Analysis](https://github.com/PlagueHO/DscResource.Analysis/blob/master/README.md#example-1) over all modules in the DSC Resource Kit and the following are the ones which are opted in to 'Common Tests - Custom Script Analyzer Rules':
image

ActiveDirectoryCSDsc
ActiveDirectoryDsc
CertificateDsc
ComputerManagementDsc
DFSDsc
FileContentDsc
FSRMDsc
iSCSIDsc
NetworkingDsc
SecurityPolicyDsc
SqlServerDsc
StorageDsc
WmiNamespaceSecurityDsc
WSManDsc
xBitlocker
xExchange
xPSDesiredStateConfiguration
xWebAdministration

So these are the only ones we need to worry about testing.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346#-:-LoHGHuc-gA9ZTq-ucqY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@SSvilen If you want to work on another rule, then space after a keyword would be great to get in, for example `if(` -> `if (`. Another I see often.

**Comment by PlagueHO** [comment]
Also after for/foreach/while too

**Comment by johlju** [comment]
Maybe all keywords that are followed by a space? 🤔

**Review by SSvilen — COMMENTED** [review]
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-space-between-keyword-and-parenthesis 
I'm on it. 

> *[Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/346#-:-LoMWJs05clpJ4uGC8d3:b6f7eqa)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PlagueHO** [comment]
Ok! Good work everyone - all repos have been updated to pass these new tests!

**Comment by johlju** [comment]
Cool! This rule will help a lot in future! 😃

**Pull request merged**
