### PR TITLE
New PSSA custom rule for opening braces - Fixes #27

### LINKED ISSUE #27: Add a test for Egyptian braces Meta.tests.ps1 and a fixer to Meta.Fixers.ps1
There is a StyleGuideline that states that [Egyptian Braces](http://blog.codinghorror.com/new-programming-jargon/) shouldn't be used - e.g. code block open braces should appear on a new line.

It would be good if Meta.Tests.ps1 could include a test identified this problem.

Ideally, an automatic fixer for this could also be provided in Meta.Fixers.ps1.

### PR DESCRIPTION
**Pull request by johlju**
- Add Script Analyzer custom rule to test functions and statements so that
  opening braces are set according to the style guideline (issue #27).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresource.tests/180)

### CODE REVIEW

**Comment by johlju** [comment]
This is tested okay here: https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.235.0#L282

Measure-FunctionBlockBraces:
```
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xCluster.psm1 (Line 413): Functions should not have the open brace on the same line as the function name. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces
MSFT_xCluster.psm1 (Line 469): Opening brace on function should be followed by a new line. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
MSFT_xCluster.psm1 (Line 488): Opening brace on functions should only be followed by one new line. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
```

Measure-StatementBlockBraces:
```
MSFT_xCluster.psm1 (Line 449): Statements should not have the open brace on the same line as the statement. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-before-braces
MSFT_xCluster.psm1 (Line 459): Opening brace on statements should be followed by a new line. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
MSFT_xCluster.psm1 (Line 463): Opening brace on statements should only be followed by one new line. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#one-newline-after-opening-brace
```

**Comment by johlju** [comment]
Please let me know if I use wrong terminology for the function names and variables. And/or if they should be named differently.

**Comment by johlju** [comment]
@PlagueHO Can you look this one over when you got a chance? 😄

**Comment by PlagueHO** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 157 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-E90m9wYByP-d4_S:-KqX-E91HUaC3F9wUMfP:b-k83b83) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L157)):*
> ```PowerShell
>                     Remove carriage return since the file is different depending if it's run in
>                     AppVeyor or locally. Locally it contains both '\r\n', but when cloned in
>                     AppVeyor it only contain '\n'.
> ```

contain -> contains

:grin:

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 200 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-Ww9J3ovK0hZA0zc:-KqX-WwAGuTrhY3tjUhJ:byja86t) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L200)):*
> ```PowerShell
>                 {
>                     # Check so that an opening brace is followed by only one new line.
>                     if ($functionExtentRows[2].Trim() -eq '')
> ```

Could we use `[String]::IsNullOrEmpty(functionExtentRows[2].Trim())` ?

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 286 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-soiteVVmHj8Dcm9:-KqX-soiteVVmHj8DcmA:b-k83b83) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L286)):*
> ```PowerShell
>                             Remove carriage return since the file is different depending if it's run in
>                             AppVeyor or locally. Locally it contains both '\r\n', but when cloned in
>                             AppVeyor it only contain '\n'.
> ```

contain -> contains

:grin:

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 318 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-zR5UQXlc3n4l5nD:-KqX-zR5UQXlc3n4l5nE:bm05yd9) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L318)):*
> ```PowerShell
>                             Remove carriage return since the file is different depending if it's run in
>                             AppVeyor or locally. Locally it contains both '\r\n', but when cloned in
>                             AppVeyor it only contain '\n'.
> ```

contain -> contains

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 344 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX03lnR4LKsHmKGpiw:-KqX03lnR4LKsHmKGpix:b-e151fi) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L344)):*
> ```PowerShell
>                         {
>                             # Check so that an opening brace is followed by only one new line.
>                             if ($statementExtentRows[1].Trim() -eq '')
> ```

Maybe use `[String]::IsNullOrEmpty()`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180)*

**Comment by johlju** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 157 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-E90m9wYByP-d4_S:-KqYh4OEQl6A_61Phw_w:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L157)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

contain -> contains

:grin:
</blockquote></details>

Done.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 200 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-Ww9J3ovK0hZA0zc:-KqYh66HeZBrfHKI_ork:b-m5zyuh) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L200)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could we use `[String]::IsNullOrEmpty(functionExtentRows[2].Trim())` ?
</blockquote></details>

Done. This works. Empty string and $null returns false.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 286 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-soiteVVmHj8Dcm9:-KqYhLPL3ikCB9Ykvd4F:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L286)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

contain -> contains

:grin:
</blockquote></details>

Done.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 318 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX-zR5UQXlc3n4l5nD:-KqYhMCYJbxbZLU9yH0U:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L318)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

contain -> contains
</blockquote></details>

Done.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1, line 344 at r1](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KqX03lnR4LKsHmKGpiw:-KqYhNTGQa5oM3OkXgpx:b-m5zyuh) ([raw file](https://github.com/powershell/dscresource.tests/blob/47556e23bc06f7ecbaacf99f6a450edd1811d124/DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1#L344)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Maybe use `[String]::IsNullOrEmpty()`? 
</blockquote></details>

Done. This works. Empty string and $null returns false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180)*

**Comment by johlju** [comment]
Changes was tested here; https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.238.0#L283

**Comment by PlagueHO** [comment]
:lgtm:

Nice work @Johlju ! These rules are going to be a fantastic help!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-:-KqaTh-WMdSIX9gc48qa:bag51vo)*

**Comment by PlagueHO** [comment]
@KwirkyKat - can you merge if you get a chance?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-:-KqaToMW-4PJ8wdOkzo6:b8w9op6)*

**Comment by johlju** [comment]
@kwirkykat this is ready for review, after rebase, tests are passing.

@PlagueHO can you review the last file after rebase?

**Comment by PlagueHO** [comment]
@johlju - ill review these tonight :grin: will be awesome to get them in. Ill also rebase my PR.

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-:-Kr59Ov45yG9jznqNJQx:bnfp4nl)*

**Comment by johlju** [comment]
This PR should be refactored according to https://github.com/PowerShell/DscResource.Tests/issues/185. I will close this and re-open when I'm done.

**Comment by johlju** [comment]
Opening this to rebase against dev.

**Comment by johlju** [comment]
Closing this and wait for dependent PR #187 to be merged.

**Comment by johlju** [comment]
Opening this to rebase against dev (unsure if force push will make it unable to reopen).

**Comment by johlju** [comment]
@PlagueHO Do you mind review this again after I refactored the code? I will run a manual integration test tomorrow on this code. But the unit tests are passing at least.

**Comment by PlagueHO** [comment]
Oh wow! That is some awesome work! Fantastic! I've begun the review (haven't found a single issue yet) - but won't have time to finish till Friday night (my time) as I'm traveling for work at the moment.

---

Reviewed 1 of 3 files at r4, 2 of 4 files at r5.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-:-KsFSkw00t4CFKSwjMSv:b-rfn8l4)*

**Comment by johlju** [comment]
No worries! No hurry. :)
Found a bug, squashed it - also tested this manually. Looks like it works 😄 

https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.257.0#L477

I double checked the entries against the code:

https://github.com/johlju/xFailOverCluster/blob/c6356014997781e10d40df66b1f9a2b46e9d8cc8/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L413-L732

**Comment by PlagueHO** [comment]
Hi @Johlju - just doing a bit of testing and come across a false-positive:
https://ci.appveyor.com/project/PlagueHO/xnetworking/build/3.1.660.0#L3406

It is reporting this as a violation:
```powershell
            if (-not $defaultRoutes.Where( { $_.NextHop -eq $Address } ))
            {
```

I think though that many of the rules will be affected by a similar false positive. E.g. Foreach, Until, While, Switch

Amazing job BTW!

---

Reviewed 1 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 448 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQe30i1JJ7PYqtWDV1:-KsQe30i1JJ7PYqtWDV2:baqpwg7) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L448)):*
> ```PowerShell
>         }
> 
>         Context 'When function follow style guideline' {
> ```

nitpick: `follow` -> `follows`

This occurs in a few places - non-blocking. Fix if you wish! :grin:

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 480 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQeEyCGMAGpfc889hn:-KsQeEyCGMAGpfc889ho:bpwo4yc) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L480)):*
> ```PowerShell
>         }
> 
>         Context 'When if-statement has an opening brace on the same line' {
> ```

Suggest adding a new test for false-positive:
```powershell
$invokeScriptAnalyzerParameters['ScriptDefinition'] = '
function Get-Something
{
  if (Get-Command | Where-Object -FilterScript { $_.Name -eq 'Get-Help' } ) {
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-:-KsQbdoQg3ojPe6DAC9I:b-40mork)*

**Comment by johlju** [comment]
@PlaugueHO Good catch! I didn't think about that. :/ Think we have to check if the string ends with something that match ').{' (regex). I will look at making this more sturdy. If you have a suggestion for regex, let me know. It is not my strongest skill yet :)

**Comment by PlagueHO** [comment]
@johlju - this should work:
`'{[\s]*$'`
It'll match { at the end of a line even if there are spaces or tabs between the { and the end of the line.

**Comment by johlju** [comment]
@PlagueHO Thank you! I really need to learn regex more, because every time I try to use it I feel I have to re-learn the basics, even using a regex tester doesn't help if you don't understand the basics. Any book or material you can recommend? 😄

**Comment by johlju** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 448 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQe30i1JJ7PYqtWDV1:-KsTUC4T0dnnKdLQSJub:b-t7ewpc) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L448)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nitpick: `follow` -> `follows`

This occurs in a few places - non-blocking. Fix if you wish! :grin:
</blockquote></details>

Done.

Always want to fix spelling! :smile: I learn to spell more correct every time you comment on these :smile: 

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 480 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQeEyCGMAGpfc889hn:-KsTULvaWxOG2Bqx_B5J:b-cqwnrc) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L480)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Suggest adding a new test for false-positive:
```powershell
$invokeScriptAnalyzerParameters['ScriptDefinition'] = '
function Get-Something
{
  if (Get-Command | Where-Object -FilterScript { $_.Name -eq 'Get-Help' } ) {
  }
}
```
</blockquote></details>

Done.

Added regression test, which failed. Changed the regex in the helper function and the test passed.
All of the Measure-*Statement (and CatchClause) uses the same helper function, so this should resolve this issue for all.
I only added one regression test for the If-statement, seemed unnecessary to add the same test to all (?). Or, maybe I should make the regression test to test the actual helper function instead?  What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180)*

**Comment by PlagueHO** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 7 at r7](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-Ksc0USq8sTiPO4UMYXK:-Ksc0USruxGUdc83A1LT:brd13x8) ([raw file](https://github.com/powershell/dscresource.tests/blob/3831b2168baa505df8a42f421498c40416a54504/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L7)):*
> ```PowerShell
> 
>     .EXAMPLE
>         Test-StatementOpeningBraceOnSameLine -StatementBlock $ScriptBlockAst.Extent
> ```

I think this example needs to be updated.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 448 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQe30i1JJ7PYqtWDV1:-Ksc-sVp065ZVMXh9JTB:b-cqfpsq) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L448)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.

Always want to fix spelling! :smile: I learn to spell more correct every time you comment on these :smile: 
</blockquote></details>

I wish I knew Swedish (I do love listening to Swedish death metal but I don't understand the words :grin: ) - but glad my nitpicks are helpful :grin:

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 480 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQeEyCGMAGpfc889hn:-Ksc0OVJFDDh6_FN6pz2:b-xdmi2h) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L480)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.

Added regression test, which failed. Changed the regex in the helper function and the test passed.
All of the Measure-*Statement (and CatchClause) uses the same helper function, so this should resolve this issue for all.
I only added one regression test for the If-statement, seemed unnecessary to add the same test to all (?). Or, maybe I should make the regression test to test the actual helper function instead?  What do you think?
</blockquote></details>

I'd be tempted to add a regression test for the for the helper function. But I don't think it's a showstopper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180)*

**Comment by johlju** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1, line 7 at r7](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-Ksc0USq8sTiPO4UMYXK:-KsnsKVjD00-j81ckAT8:b-896fix) ([raw file](https://github.com/powershell/dscresource.tests/blob/3831b2168baa505df8a42f421498c40416a54504/DscResource.AnalyzerRules/DscResource.AnalyzerRules.Helper.psm1#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this example needs to be updated.
</blockquote></details>

Done.

---

*[Tests/Unit/DscResource.AnalyzerRules.Tests.ps1, line 480 at r6](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-KsQeEyCGMAGpfc889hn:-Ksntm158mB7SnPh3jIP:bddj1bp) ([raw file](https://github.com/powershell/dscresource.tests/blob/c12f78b37a8f50235b0746ce7b10d4ac7bc9697d/Tests/Unit/DscResource.AnalyzerRules.Tests.ps1#L480)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'd be tempted to add a regression test for the for the helper function. But I don't think it's a showstopper.
</blockquote></details>

Done. Added tests for the helper functions! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180)*

**Comment by johlju** [comment]
@PlagueHO The tests is failing. Looking at it now.

**Comment by johlju** [comment]
Hmm.. I seem to have copy/paste a file in the wrong place 😞 I need to do some git magic here...

**Comment by johlju** [comment]
@PlagueHO All good for review again! 😄

**Comment by PlagueHO** [comment]
Awesome! :lgtm:

@KwirkyKat - any chance you could sign off if you have a moment? :grin:

---

Reviewed 1 of 1 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresource.tests/180#-:-Ksz9hC6OWyoAcxHnvQe:b-aa78k1)*

**Pull request merged**
